### ISSUE TITLE
Crashes during startup due to Forge Loading Screen

### ISSUE THREAD

**Issue by Slikrick** [MrCrayfish/MrCrayfishFurnitureMod#10]
Here is the full log: https://gist.github.com/slikrick98/b4fb6390db70b11b6b9b
Log with debug info: https://gist.github.com/slikrick98/e19279b49536460ddf3f

Using forge 1389. Only your mod installed, only happens on versions with the loading screen.

**Comment by TheSchwa** [comment]
Same issue on Forge 1403 with only this mod installed. The FML devs suggested it's a problem with this mod causing their splash screen to throw some Font Rendering errors? I got this on Ubuntu 14.04, but my friend was able to load it successfully using Forge 1403 on Windows 8.1.

My log (fml-1403, linux, java-7): https://gist.github.com/TheSchwa/dc7b5efebc30d9802e66

One other log from the FML issue page (https://github.com/MinecraftForge/FML/issues/644):

@ray10k (fml-1395, win7, java-8): https://gist.github.com/ray10k/c199fe5ea965d622a637

**Comment by toxicpsion** [comment]
This also occurs with Forge 1394 on 1.7.10 on debian with Java 8. Same error as above, same trace as above. slightly different versions.

**Comment by TBoshoven** [comment]
Same for Forge 1403 on 1.7.10, Arch Linux, x86-64,  jre8-openjdk 8.u45, Fastcraft installed (The Dark Trilogy modpack).

**Comment by toxicpsion** [comment]
Traced problem to non-ascii chars in mcmod.info, seems the font parser in FML is puking on the "§" char. manually editing them out allowed me to load properly.

**Comment by p455w0rd** [comment]
that sucks..i'm not getting why it would only do it on *nix...do any of you run any other mods that have colors in the names (under Mod list in client)? If so, which mods? § is just formatting n i wanna check other mods n see if like the charset is different or something..I'll install ubuntu on virtualbox in a bit and look into this

**Comment by p455w0rd** [comment]
well..i figured just escape 'em..but they already are..at least in build version..i guess for *nix it might be worth taking out formatting..rly not important

**Comment by 8wgremlin** [comment]
I have this now with a MAC osX 

toxicpsion do you have your version available?
or could we get the owner to change it.

**Comment by p455w0rd** [comment]
try this: http://p455w0rd.net/assets/files/MrCrayfishFurnitureModv3.4.7-build8.1(1.8).jar
