### ISSUE TITLE
NullPointerException at TileEntityFridge

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [MrCrayfish/MrCrayfishFurnitureMod#100]
Hi there,

my Minecraft server was running when it suddenly shut down due to the exception pasted below. I am not able to get it running anymore (neither as server nor client-only). I am using Minecraft 1.8.9 and the problem occurs with version 4.0 and 4.0.1 of FurnitureMod.

See attached file for crash report with exception and stacktrace.
[crash-2016-07-06_17.23.45-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/350239/crash-2016-07-06_17.23.45-server.txt)

Are you able to fix this?

**Comment by MrCrayfish** [comment]
I don't support 1.8.9 anymore
