### ISSUE TITLE
Item duplication with presents

### ISSUE THREAD

**Issue by lucom** [MrCrayfish/MrCrayfishFurnitureMod#105]
By putting items into stacks of presents you can duplicate those items.
Steps to reproduce:
- Create at least 2 presents
- Put both as a stack into item slot 1 and use them
- The present GUI opens. Here you can insert some precius gems and stuff into the present
- Close the present and go to your inventory
- Right click (drag) the presents stack through your inventory to split that stack
- Now every present should contain the same stuff

Minecraft 1.8, Forge 1563, cfm 4.0.1, SSP,  probably also SMP

**Comment by MrCrayfish** [comment]
Fixed in f9b667b8365e5b020ed65d9275a337fce097cc34
