### ISSUE TITLE
[1.10]java.lang.NoClassDefFoundError: com/mrcrayfish/furniture/items/ItemHedge

### ISSUE THREAD

**Issue by Rycory** [MrCrayfish/MrCrayfishFurnitureMod#106]
I checked up and down and i think this won't be a double post of an issue. I get the error in the title when trying to run my tiny family server with this mod. Here is the lastest log i pulled from the server.

http://pastebin.com/qxuNQ5cK

**Comment by MrCrayfish** [comment]
Fixed in latest commit
