### ISSUE TITLE
Private Server - Calling Client-Side Classes on Server-Side (ItemHedge @ net.minecraft.client.renderer.color.IItemColor)

### ISSUE THREAD

**Issue by JonnyBrando** [MrCrayfish/MrCrayfishFurnitureMod#108]
Hello,

CFM compiled for 1.10 (and 1.10 compiled for 1.9.4) works fine in SP mode. When trying to use the mod on the Private Server side it errors.

It appears to be an issue with calling Client-Side classes from the Server-Side.

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
>   IC2core (industrialcraft-2-2.6.26-ex110.jar)
>   CreativePatchingLoader (CreativeCore v1.5.1 mc1.10.2.jar)
>   FMLPlugin (InventoryTweaks-1.61-58.jar)
>   MMFMLCorePlugin (MultiMine-1.10.jar)
>   MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
>   PlayerAPIPlugin (PlayerAPI-1.10.2-1.0.jar)
>   SCFMLCorePlugin (StalkerCreepers-1.10.jar)
>   ItemPatchingLoader (ItemPhysic Full 1.3.2 mc1.10.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // Everything's going to plan. No, really, that was supposed to happen.
> 
> Time: 9/12/16 3:54 PM
> Description: Exception in server tick loop
> 
> net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/mrcrayfish/furniture/items/ItemHedge
>   at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
>   at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:610)
>   at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
>   at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
>   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NoClassDefFoundError: com/mrcrayfish/furniture/items/ItemHedge
>   at com.mrcrayfish.furniture.MrCrayfishFurnitureMod.preInit(MrCrayfishFurnitureMod.java:83)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
>   at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
>   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
>   at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:607)
>   ... 5 more
> Caused by: java.lang.ClassNotFoundException: com.mrcrayfish.furniture.items.ItemHedge
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   ... 32 more
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/color/IItemColor
>   at java.lang.ClassLoader.defineClass1(Native Method)
>   at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
>   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
>   ... 34 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.color.IItemColor
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   ... 38 more
> Caused by: java.lang.NullPointerException
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
>   ... 40 more
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.10.2
>   Operating System: Windows 8.1 (amd64) version 6.3
>   Java Version: 1.8.0_74, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 188119216 bytes (179 MB) / 650383360 bytes (620 MB) up to 8563130368 bytes (8166 MB)
>   JVM Flags: 7 total; -Xms350m -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:+AggressiveOpts -Xmn256M
>   IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>   FML: MCP 9.32 Powered by Forge 12.18.1.2045 45 mods loaded, 45 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
>   UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2045-universal.jar) 
>   UCH Forge{12.18.1.2045} [Minecraft Forge](forge-1.10.2-12.18.1.2045-universal.jar) 
>   UCH creativecoredummy{1.0.0} [CreativeCoreDummy](minecraft.jar) 
>   UCH itemphysic{1.3.0} [ItemPhysic](minecraft.jar) 
>   UCH PlayerAPI{1.0} [Player API](minecraft.jar) 
>   UCE cfm{4.0.1} [MrCrayfish's Furniture Mod]([1.10]cfm-universal-4.0.1.jar) 
>   UCH movillages{1.5.2} [Mo' Villages]([1.9.4]Mo' Villages-1.5.2.jar) 
>   UCH bagginses{2.4.2d} [Bagginses](Bagginses-1.10-3.0.0c.jar) 
>   UCH BetterAchievements{0.3.0.30} [Better Achievements](BetterAchievements-1.10.2-0.3.0.30.jar) 
>   UCH betteragriculture{0.16} [Better Agriculture](BetterAgriculture_%28MC-1.10%29-0.16.jar) 
>   UCH BetterFoliage{2.1.0} [Better Foliage](BetterFoliage-MC1.10-2.1.0.jar) 
>   UCH BiomesOPlenty{4.1.0.2052} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2052-universal.jar) 
>   UCH chiselsandbits{11.7} [Chisels & Bits](chiselsandbits-11.7.jar) 
>   UCH IC2{2.6.26-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.26-ex110.jar) 
>   UCH JEI{3.7.9.236} [Just Enough Items](jei_1.10.2-3.7.9.236.jar) 
>   UCH forestry{5.2.5.217} [Forestry](forestry_1.10.2-5.2.5.217.jar) 
>   UCH gravestone{1.5.4} [Gravestone](GraveStone Mod 1.5.4.jar) 
>   UCH LunatriusCore{1.1.2.36} [LunatriusCore](LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
>   UCH InGameInfoXML{2.8.1.85} [InGame Info XML](InGameInfoXML-1.10.2-2.8.1.85-universal.jar) 
>   UCH Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
>   UCH InventoryPets{1.4.8.1} [Inventory Pets](inventorypets-1.10-1.4.8.1.jar) 
>   UCH inventorysorter{0.10.0+42} [Simple Inventory sorting](inventorysorter-1.10-0.10.0+42.jar) 
>   UCH inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
>   UCH journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
>   UCH lucky{7.3.0} [Lucky Block](LuckyBlock_1-10-2_v7-3-0.jar) 
>   UCH malisiscore{1.9.4-4.0.2} [MalisisCore](malisiscore-1.9.4-4.0.2.jar) 
>   UCH malisisblocks{1.9.4-4.0.1} [Malisis Blocks](malisisblocks-1.9.4-4.0.1.jar) 
>   UCH malisisdoors{1.9.4-5.0.1} [MalisisDoors](malisisdoors-1.9.4-5.0.1.jar) 
>   UCH RadixCore{1.10.2-2.1.2} [RadixCore](RadixCore-1.10.2-2.1.2-universal.jar) 
>   UCH MCA{1.10.2-5.2.1} [Minecraft Comes Alive](MCA-1.10.2-5.2.1-universal.jar) 
>   UCH AS_MultiMine{1.5.4} [Multi Mine](MultiMine-1.10.jar) 
>   UCH harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2a.jar) 
>   UCH parachutemod{1.5.2} [Parachute Mod](parachutemod-ng-1.10.2-1.5.2-409.jar) 
>   UCH progressiveautomation{1.6.48} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.48.jar) 
>   UCH Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
>   UCH AS_Ruins{16.2} [Ruins Spawning System](Ruins-1.10.jar) 
>   UCH SophisticatedWolves{3.6.1} [SophisticatedWolves](SophisticatedWolves-3.6.2.jar) 
>   UCH Chameleon{1.9.4-2.1.6} [Chameleon](Chameleon-1.9.4-2.1.6.jar) 
>   UCH StorageDrawers{1.9.4-3.2.1} [Storage Drawers](StorageDrawers-1.9.4-3.2.1.jar) 
>   UCH mantle{1.10.2-0.10.4.jenkins163} [Mantle](Mantle-1.10.2-0.10.4.jar) 
>   UCH tconstruct{1.10.2-2.4.0.jenkins312} [Tinkers' Construct](TConstruct-1.10.2-2.4.0.jenkins312.jar) 
>   UCH Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
>   UCH WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.10-1.1.7.jar) 
>   UCH creativecore{1.5.0} [CreativeCore](CreativeCore v1.5.1 mc1.10.2.jar) 
>   Loaded coremods (and transformers): 
> BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
>   mods.betterfoliage.loader.BetterFoliageTransformer
> IC2core (industrialcraft-2-2.6.26-ex110.jar)
> 
> CreativePatchingLoader (CreativeCore v1.5.1 mc1.10.2.jar)
> 
> FMLPlugin (InventoryTweaks-1.61-58.jar)
>   invtweaks.forge.asm.ContainerTransformer
> MMFMLCorePlugin (MultiMine-1.10.jar)
>   atomicstryker.multimine.common.fmlmagic.MMTransformer
> MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
>   net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
>   net.malisis.core.util.chunkblock.ChunkBlockTransformer
>   net.malisis.core.renderer.transformer.MalisisRendererTransformer
>   net.malisis.core.renderer.icon.asm.TextureMapTransformer
>   net.malisis.core.util.clientnotif.ClientNotifTransformer
> PlayerAPIPlugin (PlayerAPI-1.10.2-1.0.jar)
>   api.player.forge.PlayerAPITransformer
> SCFMLCorePlugin (StalkerCreepers-1.10.jar)
>   atomicstryker.stalkercreepers.common.SCTransformer
> ItemPatchingLoader (ItemPhysic Full 1.3.2 mc1.10.2.jar)
>   com.creativemd.itemphysic.ItemTransformer
>   Pulsar/tconstruct loaded Pulses: 
>       - TinkerCommons (Enabled/Forced)
>       - TinkerWorld (Enabled/Not Forced)
>       - TinkerTools (Enabled/Not Forced)
>       - TinkerSmeltery (Enabled/Not Forced)
>       - TinkerGadgets (Enabled/Not Forced)
>       - TinkerOredict (Enabled/Forced)
>       - TinkerIntegration (Enabled/Forced)
>       - TinkerFluids (Enabled/Forced)
>       - TinkerMaterials (Enabled/Forced)
>       - chiselsandbitsIntegration (Enabled/Not Forced)
>       - WailaIntegration (Enabled/Not Forced)
> 
>   Profiler Position: N/A (disabled)
>   Is Modded: Definitely; Server brand changed to 'fml,forge'
>   Type: Dedicated Server (map_server.txt)

**Comment by MrCrayfish** [comment]
Fixed. Thank you for the report
