### ISSUE TITLE
( 1.8.9 ) Encountering 4 Bugs.

### ISSUE THREAD

**Issue by AgentHani** [MrCrayfish/MrCrayfishFurnitureMod#111]
Using Forge 1.8.9-11.15.1.1902 w/ Furniture Mod 1.8.9

I've found 4 Bugs ( I dont if the last one is considered as a bug or not)

~ Grand Chair :

Bug occurs when sitting in the grand chair and then breaking it while sitting.. result is that it makes you get stuck in your place when u sit and break the chair at the same time.

~ JukeBox :

Sound Bug occurs when placing a customized music disc into the jukebox, Result = Music plays multiple times and glitches out suddenly, breaking the jukebox wont even stop the music.

~ TV :

Sound Bug occurs when i tried extending the channel_4.ogg to a bit long version of the music, Result = Song is still playing in the background even when the TV is already destroyed.

~ Stereo:

For Multiplayer case, Stereo cant be heard by other players but only by you, Plus when trying to customize music discs, stereo will most likely also play a song multiple times in the background.
# 

I've tried digging some source codes in the 1.8.9 file, but i think i couldnt find any solution related to my problem (correct me if i am wrong because i am new to github and have not enough knowledge towards source coding)

**Comment by MrCrayfish** [comment]
I'll look into the issues. Thanks for the report

**Comment by AgentHani** [comment]
Is the issue solved or yet pending :p ?
