### ISSUE TITLE
crash when breaking cabinets (1.10.2)

### ISSUE THREAD

**Issue by Hypsellis** [MrCrayfish/MrCrayfishFurnitureMod#113]
I get sometimes this crash when trying to break cabinets, it seems Furnitures mess with ActuallyAdditions. http://pastebin.com/3Gn8vjwM

**Comment by Hypsellis** [comment]
https://github.com/Ellpeck/ActuallyAdditions/issues/492

**Comment by MrCrayfish** [comment]
I'm not sure why this is crashing. There is nothing special about cabinet. It's literally the chest code.

**Comment by MrCrayfish** [comment]
Actually, I fixed this issue.
