### ISSUE TITLE
(1.11.2) Shift-clicking items into and out of Kitchen Cabinet causes crash

### ISSUE THREAD

**Issue by mewzurui** [MrCrayfish/MrCrayfishFurnitureMod#116]
[crash-2017-01-09_16.00.03-client.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/694789/crash-2017-01-09_16.00.03-client.txt)

Crash log is attached and also pasted below. Shift clicking into other modded inventories causes no issue so I am assuming it is on MCFM's side. I apologise if I have misinterpreted and if I have what may be the issue?
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.6.jar)
  CAFMLPlugin ([1.11]CraftableAnimals v2.7.0.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  IvToolkit (IvToolkit-1.3.1.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 1/9/17 6:05 PM
Description: Updating screen events

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at com.mrcrayfish.furniture.tileentity.TileEntityFurniture.func_70299_a(TileEntityFurniture.java:113)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at com.mrcrayfish.furniture.gui.containers.ContainerCabinet.func_82846_b(ContainerCabinet.java:88)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:237)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at com.mrcrayfish.furniture.tileentity.TileEntityFurniture.func_70299_a(TileEntityFurniture.java:113)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at com.mrcrayfish.furniture.gui.containers.ContainerCabinet.func_82846_b(ContainerCabinet.java:88)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:237)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)

-- Affected screen --
Details:
	Screen name: com.mrcrayfish.furniture.gui.GuiKitchenCabinet

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Mewzurui'/179, l='MpServer', x=-1637.34, y=65.00, z=817.19]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-60,64,240), Chunk: (at 4,4,0 in -4,15; contains blocks -64,0,240 to -49,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1415841 game time, 182313 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 41 total; [EntityChicken['Chicken'/192, l='MpServer', x=-1620.15, y=64.00, z=854.58], EntityChicken['Chicken'/193, l='MpServer', x=-1619.49, y=64.00, z=854.93], EntityChicken['Chicken'/194, l='MpServer', x=-1620.53, y=64.00, z=855.44], EntityChicken['Chicken'/195, l='MpServer', x=-1619.86, y=64.00, z=855.97], EntitySheep['Sheep'/196, l='MpServer', x=-1620.93, y=64.00, z=848.92], EntityItem['item.item.egg'/9413, l='MpServer', x=-1620.29, y=64.00, z=853.75], EntityPig['Pig'/197, l='MpServer', x=-1631.55, y=64.00, z=859.80], EntitySheep['Sheep'/198, l='MpServer', x=-1618.08, y=64.00, z=848.92], EntityCow['Cow'/199, l='MpServer', x=-1631.48, y=64.00, z=848.82], EntitySheep['Sheep'/200, l='MpServer', x=-1619.81, y=64.00, z=848.48], EntityItem['item.item.egg'/201, l='MpServer', x=-1619.36, y=64.00, z=854.93], EntityItem['item.item.egg'/202, l='MpServer', x=-1619.32, y=64.00, z=853.75], EntityCow['Cow'/204, l='MpServer', x=-1633.04, y=64.00, z=850.83], EntityCow['Cow'/205, l='MpServer', x=-1632.06, y=64.00, z=850.97], EntityCow['Cow'/206, l='MpServer', x=-1631.08, y=64.00, z=851.92], EntityCow['Cow'/207, l='MpServer', x=-1631.08, y=64.00, z=850.92], EntityMinecartChest['Minecart with Chest'/214, l='MpServer', x=-1615.50, y=39.06, z=816.50], EntityPig['Pig'/217, l='MpServer', x=-1633.93, y=64.00, z=859.92], EntityPig['Pig'/218, l='MpServer', x=-1633.55, y=64.00, z=859.00], EntityItem['item.item.egg'/15514, l='MpServer', x=-1620.17, y=64.00, z=854.72], EntityPig['Pig'/219, l='MpServer', x=-1632.58, y=64.00, z=859.29], EntityCow['Cow'/220, l='MpServer', x=-1633.93, y=64.00, z=851.92], EntityCow['Cow'/221, l='MpServer', x=-1632.91, y=64.00, z=851.92], EntityCow['Cow'/222, l='MpServer', x=-1632.01, y=64.00, z=851.92], EntityCow['Cow'/223, l='MpServer', x=-1633.90, y=64.00, z=849.82], EntityCow['Cow'/224, l='MpServer', x=-1631.99, y=64.00, z=849.88], EntityCow['Cow'/225, l='MpServer', x=-1631.08, y=64.00, z=849.88], EntitySheep['Sheep'/226, l='MpServer', x=-1620.56, y=64.00, z=846.76], EntityItem['item.item.egg'/10152, l='MpServer', x=-1621.20, y=64.00, z=855.45], EntityItem['item.item.egg'/27885, l='MpServer', x=-1603.90, y=64.00, z=834.11], EntityPlayerSP['Mewzurui'/179, l='MpServer', x=-1637.34, y=65.00, z=817.19], EntitySquid['Squid'/182, l='MpServer', x=-1630.45, y=61.00, z=780.37], EntityMinecartChest['Minecart with Chest'/248, l='MpServer', x=-1659.50, y=36.06, z=834.50], EntityChicken['Chicken'/184, l='MpServer', x=-1604.18, y=64.00, z=833.67], EntityChicken['Chicken'/185, l='MpServer', x=-1618.83, y=64.00, z=854.91], EntityChicken['Chicken'/186, l='MpServer', x=-1619.42, y=64.00, z=854.32], EntityChicken['Chicken'/187, l='MpServer', x=-1620.93, y=64.00, z=854.98], EntityChicken['Chicken'/188, l='MpServer', x=-1620.87, y=64.00, z=853.82], EntityChicken['Chicken'/189, l='MpServer', x=-1620.33, y=64.00, z=854.02], EntityChicken['Chicken'/190, l='MpServer', x=-1619.13, y=64.00, z=855.49], EntityChicken['Chicken'/191, l='MpServer', x=-1620.41, y=64.00, z=854.99]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 434473344 bytes (414 MB) / 2144862208 bytes (2045 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 103
	FML: MCP 9.38 Powered by Forge 13.20.0.2206 Optifine OptiFine_1.11.2_HD_U_B5 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2206.jar) 
	UCHIJAAAA	forge{13.20.0.2206} [Minecraft Forge] (forge-1.11.2-13.20.0.2206.jar) 
	UCHIJAAAA	ivtoolkit{1.3.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.1.6} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.6.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	craftableanimals{2.7.0} [Craftable Animals] ([1.11]CraftableAnimals v2.7.0.jar) 
	UCHIJAAAA	movillages{1.5.3} [Mo' Villages] ([1.11]MoVillages-1.5.3.jar) 
	UCHIJAAAA	betterachievements{0.4.1.44} [Better Achievements] (BetterAchievements-1.11.2-0.4.1.44.jar) 
	UCHIJAAAA	xaerobetterpvp{1.11.9} [Better PvP] (BetterPvP_1.11.9_Forge_1.11.jar) 
	UCHIJAAAA	biomesoplenty{6.0.1.2132} [Biomes O' Plenty] (BiomesOPlenty-1.11-6.0.1.2132-universal.jar) 
	UCHIJAAAA	cfm{4.1.1} [MrCrayfish's Furniture Mod] (cfm-4.1.1-mc1.11.2.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	endercompass{1.2.5.1} [Ender Compass] (EnderCompass-1.11-1.2.5.1.jar) 
	UCHIJAAAA	findercompass{1.11.2} [Finder Compass] (FinderCompass-1.11.2.jar) 
	UCHIJAAAA	clayspawn{7.0.0} [Fire's Clay Spawn] (FiresClaySpawn-Forge-7.0.0.jar) 
	UCHIJAAAA	harvest{1.11-1.2.0-12} [Harvest] (Harvest-1.11-1.2.0-12.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (InventoryTweaks-1.62-dev-75.jar) 
	UCHIJAAAA	jei{4.2.0.210} [Just Enough Items] (jei_1.11.2-4.2.0.210.jar) 
	UCHIJAAAA	lucky{7.4.0} [Lucky Block] (LuckyBlock_1-11_v7-4-0.zip) 
	UCHIJAAAA	minecolonies{1.11-0.6.2214} [MineColonies] (minecolonies-universal-1.11-0.6.2214.jar) 
	UCHIJAAAA	mysticalagriculture{1.3.8} [Mystical Agriculture] (mysticalagriculture[1.11]-1.3.8a.jar) 
	UCHIJAAAA	reccomplex{1.2.6.1} [Recurrent Complex] (RecurrentComplex-1.2.6.1.jar) 
	UCHIJAAAA	roguelike{1.6.2} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.2.jar) 
	UCHIJAAAA	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.1.jar) 
	UCHIJAAAA	simplyhaxentitydump{1.11} [Simply Hax Entity Dump] (SimplyHax-1.11.2.jar) 
	UCHIJAAAA	simplyhaxflying{1.11} [Simply Hax Flying] (SimplyHax-1.11.2.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar) 
	UCHIJAAAA	storagedrawers{1.11-4.0.1} [Storage Drawers] (StorageDrawers-1.11-4.0.1.jar) 
	UCHIJAAAA	superminer_core{[1.11.2]-2.1.10.114} [SuperMiner] (SuperMiner-[1.11.2]-2.1.10.114.jar) 
	UCHIJAAAA	superminer_captivator{[1.11.2]-2.1.10.114} [SuperMiner Captivator] (SuperMiner-[1.11.2]-2.1.10.114.jar) 
	UCHIJAAAA	superminer_cropinator{[1.11.2]-2.1.10.114} [SuperMiner Copinator] (SuperMiner-[1.11.2]-2.1.10.114.jar) 
	UCHIJAAAA	superminer_excavator{[1.11.2]-2.1.10.114} [SuperMiner Excavator] (SuperMiner-[1.11.2]-2.1.10.114.jar) 
	UCHIJAAAA	superminer_illuminator{[1.11.2]-2.1.10.114} [SuperMiner Illuminator] (SuperMiner-[1.11.2]-2.1.10.114.jar) 
	UCHIJAAAA	superminer_lumbinator{[1.11.2]-2.1.10.114} [SuperMiner Lumbinator] (SuperMiner-[1.11.2]-2.1.10.114.jar) 
	UCHIJAAAA	superminer_shaftanator{[1.11.2]-2.1.10.114} [SuperMiner Shaftanator] (SuperMiner-[1.11.2]-2.1.10.114.jar) 
	UCHIJAAAA	superminer_substitutor{[1.11.2]-2.1.10.114} [SuperMiner Substitutor] (SuperMiner-[1.11.2]-2.1.10.114.jar) 
	UCHIJAAAA	superminer_veinator{[1.11.2]-2.1.10.114} [SuperMiner Veinator] (SuperMiner-[1.11.2]-2.1.10.114.jar) 
	UCHIJAAAA	supplydrop{1.0.0} [Supply Drop] (Supply Drop-1.11.2-1.0.0.jar) 
	UCHIJAAAA	terraqueous{1.3.3} [Terraqueous] (terraqueous-1.11.0-1.3.3.jar) 
	UCHIJAAAA	theoneprobe{1.3.4} [The One Probe] (theoneprobe-1.11-1.3.4.jar) 
	UCHIJAAAA	xaeroworldmap{1.7.1} [Xaero's World Map] (XaerosWorldMap_b1.7.1_Forge_1.11.jar) 
	Loaded coremods (and transformers): 
FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  shetiphian.core.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.6.jar)
  brad16840.common.asm.ClassTransformer
CAFMLPlugin ([1.11]CraftableAnimals v2.7.0.jar)
  naruto1310.craftableAnimals.vanilla.CATransformer
FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  invtweaks.forge.asm.ContainerTransformer
IvToolkit (IvToolkit-1.3.1.jar)
  
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2206
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: mizunos16craft edit3.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B5
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13 V6 Medium.zip
	OpenGlVersion: 4.5.0 NVIDIA 376.33
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MrCrayfish** [comment]
Thank you for the report. This has now been fixed in 6a056e61b075dca2c9744d5be3c50d9e4c8e5375
