### ISSUE TITLE
[1.10.2-4.1.1] crash report player join server

### ISSUE THREAD

**Issue by comdarksider** [MrCrayfish/MrCrayfishFurnitureMod#117]
I use version 4.1.1.  error crash report  when player join or enter server.  server stop automatic.

link error :  http://pastebin.com/SutrbXYv
link error of gist :  https://gist.github.com/comdarksider/58373e47b29bb678b8ad8edcf40ec041

Please fix error.  Thank you very much for working and every comment.

**Comment by MrCrayfish** [comment]
Thank you for the report. This has been fixed in 5465b1bdfbb3f1bbdc74b244536490919bff848f
