### ISSUE TITLE
furnitures suggestion

### ISSUE THREAD

**Issue by Hypsellis** [MrCrayfish/MrCrayfishFurnitureMod#118]
I just wanted to suggest some furnitures which miss really to the furnitures mod.
- iron chairs, tables and cofee tables
- different wood, stone and iron outdoor tables and benches
- deck chairs
- wardrobes
- two blocks high candlesticks and lamps
- chandeliers

**Comment by MrCrayfish** [comment]
This is not a place for suggestions.

**Comment by Hypsellis** [comment]
Oh ok sorry, where should I post the suggestions ?
