### ISSUE TITLE
[1.11.2] Server crashes when players try to join.

### ISSUE THREAD

**Issue by Goldenowner** [MrCrayfish/MrCrayfishFurnitureMod#120]
I installed a minecraft forge server and added the mod (4.1.1), I also installed the mod for my client.
Everything works fine, the server starts up normally and in single player the mod works perfect.
But as soon as I join the server it automatically crashes and shuts down.

**Comment by Goldenowner** [comment]
I see that the last commit was about the server crash fix, but the version on your site is still the same.
I don't know where I can get the latest version from.

**Comment by MrCrayfish** [comment]
It will be released soon. I;m instead doing lots many fixes then releasing a new version rather than small fixes and a release for every fix.

**Comment by Malus-Lupo** [comment]
Is there a work around for this crash, or is it just unusable on servers tell the next update?
