### ISSUE TITLE
[1.10.2]About server crash

### ISSUE THREAD

**Issue by songjiejoy** [MrCrayfish/MrCrayfishFurnitureMod#121]
Thanks a lot for fixed server crash bug in 5465b1b !    Would you please update 'cfm-4.1.1-mc1.10.2.jar'  in 'mrcrayfish.com'?  great Mod !   I like it !

**Comment by MastaC729** [comment]
I can confirm as well. For some reason that build you produced with the version number 4.1.1 isn't the correct build with the correct changes.

**Comment by bentterp** [comment]
Ah, so that's why we get:
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at com.mrcrayfish.furniture.proxy.CommonProxy.isDedicatedServer(CommonProxy.java:50)

**Comment by MrCaira** [comment]
Agreed, I receive the error too..
Using forge build 2122, with sponge server.

Please fix it, as it's one of my fav mods.

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
at com.mrcrayfish.furniture.proxy.CommonProxy.isDedicatedServer(CommonProxy.java:50)

**Comment by MrCrayfish** [comment]
It is fixed. Just not published.
