### ISSUE TITLE
Server crash when client join

### ISSUE THREAD

**Issue by kenijey** [MrCrayfish/MrCrayfishFurnitureMod#123]
only this mod installed. using forge 13.20.0.2214 and using game 1.11.2.
i put this mod to the server, and ran it; and put my client's mods folder, and ran it too, then opened server, works fine, opened client, works fine; when try to join server; "server closed"
and in the crash report, it says wrong side SERVER.
but this mod should be on the server too, right?
please fix this

**Comment by Goldenowner** [comment]
Many people are having this issue, take a look over [here](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/120) for his response.

**Comment by MrCrayfish** [comment]
#120
