### ISSUE TITLE
[1.11.2] Toaster, Recipe Book, and Cup

### ISSUE THREAD

**Issue by Battletested** [MrCrayfish/MrCrayfishFurnitureMod#124]
BEFORE YOU READ: I have no clue how to check the pastebin on curse or minecraft in general

First the toaster, I can put bread slices in just fine, but when I shift-right click it just gives me the slices back.

Next the recipe book, first it is an over sized texture, second I'm unable to open the book.

Lastly the cup, this isn't as important as the last two but when I break a cup it drops a duplicate cup that I'm unable to pick up and this can get very annoying.

**Comment by Battletested** [comment]
I'm also unable to access the plate's GUI

**Comment by MrCrayfish** [comment]
A lot of these have been fixed now
