### ISSUE TITLE
nothing working

### ISSUE THREAD

**Issue by PandorasHeartss** [MrCrayfish/MrCrayfishFurnitureMod#125]
the whole mod isn't working I followed the steps and went on to my Minecraft server and for some reason the mod wont work I can build it just fine but sometimes it would go back to its block form like I made a chair just to test out if it was working on both single player and multiplayer servers and it would disappear into my inventory and back into blocks.

I asked a friend with the same mod if this has happened and they said yes....Note this is the Minecraft 1.11.2

**Comment by MrCrayfish** [comment]
That is strange. From my experience, if you dont have the mod installed on the server, you will still get the crafting showing but the server doesn't know it and will translate it back into blocks. The part that confuses me is that you said it's doing it on singleplayer. I'll look into it. If I dont get anything, I'll need to ask you how to reproduce.
