### ISSUE TITLE
[1.10.2] Some bugs on LAN server

### ISSUE THREAD

**Issue by tetsune** [MrCrayfish/MrCrayfishFurnitureMod#126]
Encountering some minor issues with the 1.10.2 version.

-Couches colors do not retain after dyeing them. I dyed our couches red and they turned white after we logged back on. I also noticed that it turned white again after I left the chunk, but my sister (the LAN Host) could still see it as red until we logged off and on again.

-Chair didn't face the correct way on my game. I placed it a million times and it wouldn't face anywhere but North. To the server host, however, it was perfectly fine.

**Comment by MrCrayfish** [comment]
Already been reported and fixed. New version will be released soon!
