### ISSUE TITLE
TV sound bug

### ISSUE THREAD

**Issue by Diamondblockmc** [MrCrayfish/MrCrayfishFurnitureMod#128]
When right-clicking the TV it plays the wrong sound.
It plays this sound unsynced for all channels.
I'm using mod version 4.1.1 for minecraft 1.10.2.
https://www.youtube.com/watch?v=8tad8ZFvpy0

**Comment by dragon3025** [comment]
I'm also having this problem, I'm using 4.1.2 for minecraft 1.10.2. I get the same think that is shown in the YouTube link that Diamondblockmc posted.

**Comment by lunchboxxx19** [comment]
this bug also happens in the version 4.1.2 for mc 1.11.2

**Comment by OstenTV** [comment]
If you go out of its range while it's playing the sound and go back while it's still playing sound, it will fix it.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/pull/203
