### ISSUE TITLE
[1.10.2 v.4.1.1] Server Crash When Player Joins

### ISSUE THREAD

**Issue by Zundrel** [MrCrayfish/MrCrayfishFurnitureMod#129]
Whenever the player joins the server crashes with this crash log http://puu.sh/tvjHT/810fdc48d9.txt.

It seems you're trying to get Minecraft from the server, which doesn't exist on the server.

If you need any more info I can provide.

**Comment by JoelZBub** [comment]
This has been reported multiple times. Have a look here: https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/120

**Comment by Zundrel** [comment]
My bad. I'll close.
