### ISSUE TITLE
Orientation and colour suddenly change

### ISSUE THREAD

**Issue by Diamondblockmc** [MrCrayfish/MrCrayfishFurnitureMod#130]
Sometimes the orientation of my wooden chairs change to be north.
The same thing happens with my doorbell.
My sofa is changing colour to white insteand of black.
One time the Kitchen Counter Sink has changed orientation.
This is in Furniture Mod version 4.1 and Minecraft version 1.10.2

**Comment by MrCrayfish** [comment]
Already been fixed. Release will be coming soon!
