### ISSUE TITLE
Issue Forge MP 1.10.2 with MrCrayFish Furniture Mod - Crash on login

### ISSUE THREAD

**Issue by Nanoapplics** [MrCrayfish/MrCrayfishFurnitureMod#132]
Hello,

I have a strange issue with this mod everytime i try to add it alone or with others mods.
 
My server load fine, but when i try to connect it just crash with the following crash log. I know that its trying to load a client sided only class but how to fix the problem ? Thanks alot. :

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   IvToolkit (IvToolkit-1.2.9.jar)
> Contact their authors BEFORE contacting forge
> 
> // Don't do that.
> 
> Time: 25/01/17 16:22
> Description: Exception in server tick loop
> 
> java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
> 	at com.mrcrayfish.furniture.proxy.CommonProxy.isDedicatedServer(CommonProxy.java:50)
> 	at com.mrcrayfish.furniture.handler.SyncEvent.onPlayerLogin(SyncEvent.java:33)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_SyncEvent_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:565)
> 	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:228)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 17 more
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@22d7b4f8 from coremod FMLCorePlugin
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
> 	... 19 more
> Caused by: java.lang.RuntimeException: Attempted to load class bcx for invalid side SERVER
> 	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:56)
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249)
> 	... 21 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.10.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_111, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 3439711160 bytes (3280 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
> 	JVM Flags: 2 total; -Xms4096M -Xmx4096M
> 	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
> 	FML: MCP 9.32 Powered by Forge 12.18.3.2221 6 mods loaded, 6 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221-universal.jar) 
> 	UCHIJAAAA	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221-universal.jar) 
> 	UCHIJAAAA	ivtoolkit{1.2.9} [IvToolkit] (minecraft.jar) 
> 	UCHIJAAAA	cfm{4.1} [MrCrayfish's Furniture Mod] (cfm-4.1.1-mc1.10.2.jar) 
> 	UCHIJAAAA	reccomplex{1.2.4} [Recurrent Complex] (RecurrentComplex-1.2.4.jar) 
> 	Loaded coremods (and transformers): 
> IvToolkit (IvToolkit-1.2.9.jar)
>   
> 	Profiler Position: N/A (disabled)
> 	Player Count: 1 / 20; [EntityPlayerMP['NaNoapplics'/176, l='world', x=2,50, y=64,00, z=210,50]]
> 	Is Modded: Definitely; Server brand changed to 'fml,forge'
> 	Type: Dedicated Server (map_server.txt)

**Comment by MrCaira** [comment]
@Nanoapplics I took the liberty to recompile the lastest version of MrCrayfish's code from github to a bugfixed version.. You can use this till he decides to fix it him self, [Download Link](https://dl.dropboxusercontent.com/u/26085901/cfm-4.1.1-mc1.10.2_bugfixes.jar)

**Comment by Nanoapplics** [comment]
Thanks alot, i appreciate !

**Comment by MrCrayfish** [comment]
Already been fixed. Release will be coming soon!
