### ISSUE TITLE
1.10.2 server crash

### ISSUE THREAD

**Issue by comdarksider** [MrCrayfish/MrCrayfishFurnitureMod#136]
Please update plugins for 1.10.2 because version 4.1.1 when player join server.  server crash error report and close automatic.  In website old version.

**Comment by MrCaira** [comment]
Dude check [issue 132](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/132)

**Comment by MrCrayfish** [comment]
Fixed. Download new update!
