### ISSUE TITLE
[1.10.2-4.1.2] Microwave bug !

### ISSUE THREAD

**Issue by comdarksider** [MrCrayfish/MrCrayfishFurnitureMod#139]
Microwave bug !.  Microwave can cook beef to steak only.  Microwave can not cook raw chicken and porkchop.  Please fix bug of microwave.  Thank you very much for working and very comment.

Picture link description  :
https://www.mx7.com/view2/zEcx0Y9oucyMxwQy

**Comment by MrCrayfish** [comment]
This is not a bug. Please check the recipe book for available foods that can be cooekd in the microwave. If you need more, use the RecipeAPI in the config to add more foods.
