### ISSUE TITLE
[1.10.2-4.1.2] Stereo error

### ISSUE THREAD

**Issue by comdarksider** [MrCrayfish/MrCrayfishFurnitureMod#141]
Error Stereo when player right click for play music.  Please fix this error.
Thank you very much for working and every comment.

Full link error  :
1.  In pastebin -  http://pastebin.com/SbDf37Cd
2.  In Github -  https://gist.github.com/comdarksider/438f5ac504e2e61ed95b398a92bb09e4

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/pull/203 for 1.12.2. Please update
