### ISSUE TITLE
Soapy water and dishwasher problems 1.11.2

### ISSUE THREAD

**Issue by IamAlathe** [MrCrayfish/MrCrayfishFurnitureMod#144]
Attempting to craft soapy water crashes the game. This first happened trying to craft it in the Refined Storage crafting grid, but it also happened in Vanilla crafting table and player's default 2x2 crafting area.  I have reproduced this in my default testing world which also has JEI, JER, Hwyla, and Waila Harvestability.  Also reproduced in a new world with only this mod.  Note, I am not shift-clicking.  As soon as I click the soapy water bucket to try to take it, the game crashes.  Crash logs:  http://pastebin.com/UCdBk6k1 http://pastebin.com/DRNXU407 http://pastebin.com/bkdSLwcG http://pastebin.com/NCXs60eL

So I switch to creative mode and cheat in a couple of buckets of soapy water, a dishwasher, a washing machine and some damaged iron gear.  Washing machine works as expected.  Clicking the button on the dishwasher puts the soapy water in the machine, makes a clicking sound, and does nothing else.  Button still shows "Start", indicator still shows "Stopped".  Clicking the button again does nothing different.

**Comment by MentalMouse** [comment]
Confirming, trying to craft soapy water crashes my game too.

**Comment by PenguinMan98** [comment]
Confirmed. Same here.  Furniture Mod version 4.1.2 in Colonial Expansion.

https://www.screencast.com/t/1WgrXwzQ6

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/c91c47021893b51825a17a3d4c8376faadc08c87
