### ISSUE TITLE
Fire Alarm has no sound. [v4.1.2-MC 1.10.2]

### ISSUE THREAD

**Issue by Sandtato** [MrCrayfish/MrCrayfishFurnitureMod#145]
I've been testing this mod recently, and the fire alarm sound does not appear to be working. The fire alarm light comes on as normal, but the sound does not. Below is a list of all the mods I am using currently, just in case it is a mod conflict issue. Running latest version for 1.10.2 on Forge 12.18.3.2185.

Mods:
CoroUtil 1.10.2-1.1.13
Localized Weather Mod 1.10.2-2.4.6
Furniture Mod 1.10.2-4.1.2
Optifine 1.10.2_U_D6

**Comment by MentalMouse** [comment]
I'm not getting any sound either.

**Comment by JacksonPlayz** [comment]
I can confirm on 1.12.2.

**Comment by Rac3rZer0** [comment]
Bug confermed.
