### ISSUE TITLE
printer not working

### ISSUE THREAD

**Issue by HuseyunReis** [MrCrayfish/MrCrayfishFurnitureMod#147]
in the printer menu, when i put ink and enchanted book the progress is not going on. I tried 4.1 and 4.1.2 versions of furniture mod but nothing changed, I Can't use printer.

**Comment by HuseyunReis** [comment]
![2017-02-25_00 29 31](https://cloud.githubusercontent.com/assets/25704079/23321661/12020f38-fae9-11e6-9c8e-5f0d6eb50c4a.png)
this is what happens when i try to copy something.

**Comment by lunchboxxx19** [comment]
this bug is also in the version 4.1.2 for mc 1.11.2

**Comment by MentalMouse** [comment]
Confirming for 1.11.2/4.1.2.

**Comment by josenaldo** [comment]
Confirming for 1.11.2/4.1.1.

**Comment by josenaldo** [comment]
Confirming for 1.11.2/4.1.2.

**Comment by MrCrayfish** [comment]
Seems to be fixed in 1.12.2
