### ISSUE TITLE
Textures missing in JEI Menu

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/MrCrayfishFurnitureMod#148]
There are 8 missing textures that become visible as pink and black checkered texture when viewed in JEI (Just Enough Items) Menu .  There are block ID's with no texture

![capture](https://cloud.githubusercontent.com/assets/22108822/23326546/7c6f771a-facc-11e6-98ff-1da34a75d5ce.PNG)

**Comment by lunchboxxx19** [comment]
this bug is also in the version 4.1.2 for mc 1.11.2
