### ISSUE TITLE
Cannot place door bell on wall

### ISSUE THREAD

**Issue by CollapsedMondas** [MrCrayfish/MrCrayfishFurnitureMod#150]
When I place door bell on wall in lan server, It doesn't places on wall and pops up. I've tested on modded block and vanilla blocks, but it's same. what shall i do

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed issue in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/714f4dc359b53d5fdc31eb47263a0f26b514dd85
