### ISSUE TITLE
fr_FR.lang

### ISSUE THREAD

**Issue by Xandoria** [MrCrayfish/MrCrayfishFurnitureMod#151]
Hello,

I have translated MrCrayfish Furniture mod into French.
Here is the fr_FR.lang file:

https://justpaste.it/149vl

Unfortunately, there are no possibilities at the moment to translate the text inside containers (bedside table, cabinet, oven...) and the recipe book.

-Xandoria-

**Comment by MrCrayfish** [comment]
Please submit as PRs, not Issues
