### ISSUE TITLE
Crash when placing mirror 

### ISSUE THREAD

**Issue by Liiw** [MrCrayfish/MrCrayfishFurnitureMod#156]
Hello!

I was playing on a private spongeforge server and when I placed the mirror from your mod, the client crashed. Upon relogging to the world, client crashed again. I examined the crash report and noticed that there is probably an issue with AtomicStryker's Infernal Mobs. I am attaching the crash report for your viewing:

[crash-2017-03-26_05.47.27-client.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/870534/crash-2017-03-26_05.47.27-client.txt)

**Comment by Ravin890** [comment]
Did you ever test what would happen if you just used infernal mobs and crayfish's furniture mod?

**Comment by Liiw** [comment]
Hello again!

No I have not tested this yet. I will try it next time I update the server.

**Comment by PixelGamerX32** [comment]
I've just had this crash too. It is as Liiw describes it. I place the mirror block down, then my client freezes before crashing.
Here is my crash report of this incident.
[crash-2017-07-23_18.40.54-client.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/1168270/crash-2017-07-23_18.40.54-client.txt)
Hope this helps to find the cause behind this.

**Comment by MrCrayfish** [comment]
I've discovered the problem. It is that mods are not checking if the render view entity is actually an EntityLivingBase. Basically for the mirror to work, I need to be able to capture what the mirror is seeing, that requires changing the view entity to essentially a dummy entity. I then capture that view as a GL texture and render it as a TESR.

It should be noted that the variable Minecraft.renderViewEntity is declared as Entity. Meaning that any entity can be the render view. The mods causing the crash have assumed that the render view entity is always an EntityLivingBase, therefore causing the ClassCastException. I would follow up with the mod authors into adding a check,

**Comment by MrCrayfish** [comment]
Seems to have been fixed in this PR https://github.com/Growlith1223/ArsMagica2/pull/305

**Comment by MrCrayfish** [comment]
#https://github.com/Growlith1223/ArsMagica2/pull/305
