### ISSUE TITLE
[1.7.10] Crash if you add the recipe

### ISSUE THREAD

**Issue by Shurik1236** [MrCrayfish/MrCrayfishFurnitureMod#158]
https://pastebin.com/tWcUdV79

recipe-api {
    # Insert custom recipes here [default: ]
    S:custom-recipes <
        type=minebay,input-item=minecraft:spawn_egg,input-metadata=90,input-amount=1,payment-item=customitems:iron_coin,payment-price=8
     >
}
Пробовал и так.\I tried and true.
recipe-api {
    # Insert custom recipes here [default: ]
    S:custom-recipes <
        type=minebay,input-item=minecraft:spawn_egg:90,input-amount=1,payment-item=customitems:iron_coin,payment-price=8
     >
}
Что не так?\What's wrong?

**Comment by MrCrayfish** [comment]
1.7.10 doesn't use unlocalized names. Instead of writing spawn_egg, you have to write the ID of the item
