### ISSUE TITLE
minebay spawn egg

### ISSUE THREAD

**Issue by Phixaen** [MrCrayfish/MrCrayfishFurnitureMod#161]
The current default egg that is sold on minebay is labeled "spawn" and doesn't spawn anything.
Able to add items on minebay successfully from minecraft and several other addons successfully except for spawn eggs. 

Tried things like 

        type=minebay,input-item=minecraft:spawn_egg,input-metadata=52,input-amount=1,payment-item=minecraft:emerald,payment-price=1
tried without input amount, tried with the names of the items, with the metadata included after spawn_egg:?? and a few other variations located after searching online to no avail.
Am I doing something wrong or is this just an issue with minebay currently ?

**Comment by MentalMouse** [comment]
Spawn egg contents are apparently provided by NBT data.  I'm not sure how to specify NBT data in CFM.  In CraftTweaker, I was doing it as follows, but the WithTag() part is a CraftTweaker function.

`<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:zombie"}}`

**Comment by Phixaen** [comment]
Tried several variations of the above with entitytags, also tried using the same commands that work for a /give with _ for the spaces but of course that would be too easy.  Any other ideas?

**Comment by MrCrayfish** [comment]
I might have to remove NBT type items I was silly and implemented my API poorly as I was inexperienced back when I implemented it. I will most likely be changing it to full JSON and then it will support NBT. I will be closing this for now.
