### ISSUE TITLE
Literally everything crashes client or server in 1.11.2

### ISSUE THREAD

**Issue by Creysys** [MrCrayfish/MrCrayfishFurnitureMod#162]
Im guessing this is known if not i can elaborate on all the different blocks that crash.

**Comment by UndefinedZZK** [comment]
Hi, can you write down what blocks is crashing? I'm now working on to fix some bugs in 1.11.2, and I just made printer and soup water work properly. If you can provide more details, then I can try to make them work.

**Comment by Creysys** [comment]
Unfortunately no. I am no longer playing on a server. From what i know though is that a lot of blocks/items are capable of crashing the whole server if placed/rightclicked.
