### ISSUE TITLE
Getting odd crash to desktop

### ISSUE THREAD

**Issue by xXUnholyWolfXx** [MrCrayfish/MrCrayfishFurnitureMod#163]
Every time i try to make soapy water I crash to Desktop... and the washing mechanic dose not work at all.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.2.0.216-universal.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 5/6/17 10:03 AM
Description: Updating screen events

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:91)
	at com.mrcrayfish.furniture.handler.CraftingHandler.onCrafted(CraftingHandler.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_CraftingHandler_onCrafted_ItemCraftedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:590)
	at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:59)
	at net.minecraft.inventory.SlotCrafting.func_190901_a(SlotCrafting.java:117)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:303)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:551)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:91)
	at com.mrcrayfish.furniture.handler.CraftingHandler.onCrafted(CraftingHandler.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_CraftingHandler_onCrafted_ItemCraftedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:590)
	at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:59)
	at net.minecraft.inventory.SlotCrafting.func_190901_a(SlotCrafting.java:117)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:303)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:551)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiCrafting

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['LegandaryWolfie'/7477, l='MpServer', x=5.76, y=70.00, z=44.20]]
	Chunk stats: MultiplayerChunkCache: 286, 286
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3747 game time, 3747 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 95 total; [EntityLlama['Llama'/6169, l='MpServer', x=-61.22, y=80.00, z=-8.31], EntityLlama['Llama'/6170, l='MpServer', x=-62.56, y=82.00, z=-10.01], EntityLlama['Llama'/6171, l='MpServer', x=-63.60, y=81.00, z=-8.44], EntityLlama['Llama'/6172, l='MpServer', x=-59.62, y=80.00, z=-8.50], EntityCow['Cow'/6173, l='MpServer', x=-64.50, y=68.00, z=2.50], EntityCow['Cow'/6174, l='MpServer', x=-64.50, y=68.00, z=2.50], EntityCow['Cow'/6175, l='MpServer', x=-63.50, y=68.00, z=2.50], EntityCow['Cow'/6176, l='MpServer', x=-61.15, y=68.00, z=5.46], EntityCow['Cow'/6177, l='MpServer', x=-43.50, y=64.00, z=92.50], EntityCow['Cow'/6178, l='MpServer', x=-42.50, y=64.00, z=92.50], EntityCow['Cow'/6179, l='MpServer', x=-41.50, y=64.00, z=91.50], EntityCow['Cow'/6180, l='MpServer', x=-41.50, y=64.00, z=93.50], EntityLlama['Llama'/6187, l='MpServer', x=-32.88, y=68.00, z=-30.14], EntityCow['Cow'/6189, l='MpServer', x=-25.50, y=67.00, z=22.94], EntityCow['Cow'/6190, l='MpServer', x=-26.50, y=68.00, z=29.50], EntityCow['Cow'/6191, l='MpServer', x=-27.50, y=68.00, z=26.50], EntityCow['Cow'/6192, l='MpServer', x=-25.50, y=67.00, z=23.89], EntityCow['Cow'/6193, l='MpServer', x=-24.50, y=64.00, z=116.50], EntityCow['Cow'/6194, l='MpServer', x=-25.50, y=64.00, z=116.50], EntityCreeper['Creeper'/10291, l='MpServer', x=83.50, y=51.00, z=28.50], EntityCow['Cow'/6195, l='MpServer', x=-24.50, y=64.00, z=117.50], EntityCow['Cow'/6196, l='MpServer', x=-26.50, y=64.00, z=115.50], EntityCow['Cow'/6201, l='MpServer', x=-3.50, y=68.00, z=112.50], EntityCow['Cow'/6202, l='MpServer', x=-3.81, y=66.00, z=115.50], EntityCow['Cow'/6203, l='MpServer', x=-3.50, y=67.00, z=114.50], EntityCow['Cow'/6204, l='MpServer', x=-3.50, y=66.00, z=117.50], EntityCow['Cow'/6205, l='MpServer', x=22.50, y=69.00, z=84.50], EntityCow['Cow'/6206, l='MpServer', x=21.48, y=69.00, z=85.40], EntityCow['Cow'/6207, l='MpServer', x=21.83, y=70.00, z=86.42], EntityCow['Cow'/6208, l='MpServer', x=26.32, y=70.00, z=94.15], EntityCow['Cow'/6209, l='MpServer', x=21.50, y=68.00, z=99.50], EntityCow['Cow'/6210, l='MpServer', x=15.50, y=71.00, z=96.50], EntityCow['Cow'/6211, l='MpServer', x=16.50, y=70.00, z=97.50], EntityCow['Cow'/6212, l='MpServer', x=16.50, y=70.00, z=97.50], EntityCow['Cow'/6223, l='MpServer', x=46.41, y=69.00, z=121.32], EntityCow['Cow'/6229, l='MpServer', x=71.50, y=64.00, z=-9.50], EntityCow['Cow'/6230, l='MpServer', x=67.52, y=66.00, z=-19.19], EntityCow['Cow'/6231, l='MpServer', x=67.50, y=65.00, z=-10.50], EntityCow['Cow'/6232, l='MpServer', x=68.56, y=65.00, z=-19.23], EntityCow['Cow'/6233, l='MpServer', x=69.50, y=64.00, z=29.50], EntityCow['Cow'/6234, l='MpServer', x=71.50, y=64.00, z=27.50], EntityCow['Cow'/6235, l='MpServer', x=61.83, y=64.00, z=37.14], EntityCow['Cow'/6236, l='MpServer', x=59.80, y=65.00, z=23.52], EntityRabbit['Rabbit'/6237, l='MpServer', x=57.50, y=73.00, z=96.50], EntityRabbit['Rabbit'/6238, l='MpServer', x=56.50, y=70.00, z=99.50], EntityRabbit['Rabbit'/6239, l='MpServer', x=63.50, y=73.00, z=95.50], EntityRabbit['Rabbit'/6240, l='MpServer', x=63.50, y=73.00, z=96.50], EntityRabbit['Rabbit'/6241, l='MpServer', x=54.83, y=72.00, z=97.53], EntityRabbit['Rabbit'/6242, l='MpServer', x=67.50, y=67.00, z=112.50], EntityRabbit['Rabbit'/6243, l='MpServer', x=60.67, y=71.00, z=109.51], EntityRabbit['Rabbit'/6244, l='MpServer', x=69.50, y=68.00, z=114.50], EntityCow['Cow'/6245, l='MpServer', x=78.50, y=63.00, z=-28.50], EntityCow['Cow'/6246, l='MpServer', x=77.50, y=63.00, z=-28.50], EntityCow['Cow'/6247, l='MpServer', x=75.50, y=63.00, z=-30.50], EntityCow['Cow'/6248, l='MpServer', x=76.50, y=63.00, z=-30.50], EntityCow['Cow'/6249, l='MpServer', x=83.50, y=66.00, z=36.50], EntityCow['Cow'/6250, l='MpServer', x=80.50, y=64.00, z=33.50], EntityCow['Cow'/6251, l='MpServer', x=81.50, y=64.00, z=35.50], EntityCow['Cow'/6252, l='MpServer', x=73.50, y=64.00, z=34.50], EntityCow['Cow'/6253, l='MpServer', x=73.50, y=64.00, z=39.50], EntityCreeper['Creeper'/12440, l='MpServer', x=-23.50, y=28.00, z=-0.50], EntityItem['item.item.seeds'/10407, l='MpServer', x=60.88, y=63.00, z=54.48], EntityItem['item.item.seeds'/10409, l='MpServer', x=-9.52, y=68.00, z=57.33], EntityItem['item.item.seeds'/10412, l='MpServer', x=69.79, y=64.00, z=29.53], EntityCreeper['Creeper'/12512, l='MpServer', x=-16.50, y=36.00, z=-28.50], EntityCreeper['Creeper'/12513, l='MpServer', x=-11.50, y=36.00, z=-30.50], EntityZombie['Zombie'/12909, l='MpServer', x=-31.50, y=40.00, z=-9.50], EntityCreeper['Creeper'/12938, l='MpServer', x=83.50, y=43.00, z=52.50], EntityCreeper['Creeper'/13057, l='MpServer', x=-29.15, y=39.00, z=5.39], EntityBat['Bat'/13077, l='MpServer', x=-13.17, y=13.64, z=-17.42], EntityBat['Bat'/13078, l='MpServer', x=-12.46, y=13.87, z=-16.50], EntityBat['Bat'/13080, l='MpServer', x=-12.28, y=13.58, z=-20.66], EntityCreeper['Creeper'/13085, l='MpServer', x=-22.50, y=23.00, z=-5.50], EntityCreeper['Creeper'/13086, l='MpServer', x=-23.50, y=23.00, z=-5.50], EntityItem['item.item.seeds'/13095, l='MpServer', x=61.32, y=66.00, z=59.17], EntitySkeleton['Skeleton'/13155, l='MpServer', x=33.50, y=41.00, z=109.50], EntityZombie['Zombie'/13180, l='MpServer', x=-60.70, y=13.00, z=4.50], EntitySkeleton['Skeleton'/13181, l='MpServer', x=-60.50, y=13.00, z=3.50], EntitySkeleton['Skeleton'/13182, l='MpServer', x=-61.50, y=13.00, z=3.50], EntitySkeleton['Skeleton'/13183, l='MpServer', x=-59.90, y=13.00, z=4.50], EntityCreeper['Creeper'/13240, l='MpServer', x=75.50, y=53.00, z=20.50], EntityCreeper['Creeper'/13279, l='MpServer', x=-54.50, y=66.00, z=-32.50], EntityCreeper['Creeper'/13311, l='MpServer', x=-29.50, y=18.00, z=-25.50], EntityCreeper['Creeper'/13312, l='MpServer', x=-32.50, y=18.00, z=-27.50], EntitySkeleton['Skeleton'/13317, l='MpServer', x=-26.50, y=17.00, z=-11.50], EntityBat['Bat'/13327, l='MpServer', x=83.67, y=43.46, z=61.36], EntitySkeleton['Skeleton'/13369, l='MpServer', x=23.50, y=23.00, z=105.50], EntitySkeleton['Skeleton'/13370, l='MpServer', x=23.50, y=23.00, z=106.50], EntityZombie['Zombie'/13371, l='MpServer', x=23.50, y=23.00, z=105.50], EntityZombie['Zombie'/13372, l='MpServer', x=25.50, y=21.00, z=112.18], EntityItem['item.item.seeds'/9366, l='MpServer', x=68.51, y=64.00, z=32.71], EntityItem['item.item.seeds'/9369, l='MpServer', x=69.14, y=64.00, z=33.68], EntityItem['item.item.seeds'/11694, l='MpServer', x=66.07, y=66.00, z=59.87], EntityCreeper['Creeper'/11740, l='MpServer', x=-25.50, y=39.00, z=2.50], EntityPlayerSP['LegandaryWolfie'/7477, l='MpServer', x=5.76, y=70.00, z=44.20]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1515185144 bytes (1444 MB) / 4571791360 bytes (4360 MB) up to 7874281472 bytes (7509 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8448m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2294 Optifine OptiFine_1.11.2_HD_U_B8 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2294.jar) 
	UCHIJAAAA	forge{13.20.0.2294} [Minecraft Forge] (forge-1.11.2-13.20.0.2294.jar) 
	UCHIJAAAA	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.9.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
	UCHIJAAAA	baubles{1.4.4} [Baubles] (Baubles-1.11-1.4.4.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJAAAA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	cookingforblockheads{5.3.20} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.20.jar) 
	UCHIJAAAA	cropdusting{0.6} [CropDusting] (CropDusting-0.6-[1.11.2].jar) 
	UCHIJAAAA	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.1.jar) 
	UCHIJAAAA	forestry{5.3.3.96} [Forestry] (forestry_1.11.2-5.3.3.96.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	waila{1.8.13} [Waila] (Hwyla-1.8.13-B26_1.11.jar) 
	UCHIJAAAA	inventorytweaks{1.62+beta.86.e69c6bf} [Inventory Tweaks] (InventoryTweaks-1.62+beta.86.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJAAAA	jei{4.3.4.273} [Just Enough Items] (jei_1.11.2-4.3.4.273.jar) 
	UCHIJAAAA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	mekanism{9.3.0} [Mekanism] (Mekanism-1.11.2-9.3.0.87.jar) 
	UCHIJAAAA	mekanismgenerators{9.3.0} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.0.87.jar) 
	UCHIJAAAA	mekanismtools{9.3.0} [MekanismTools] (MekanismTools-1.11.2-9.3.0.87.jar) 
	UCHIJAAAA	moreplayermodels{1.11.0} [MorePlayerModels] (MorePlayerModels_1.11.2(26jan17).jar) 
	UCHIJAAAA	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJAAAA	mysticalagriculture{1.5.2} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.5.2c.jar) 
	UCHIJAAAA	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.2.0.216-universal.jar) 
	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	torohealthmod{1.11.2-11} [ToroHealth Damage Indicators] (torohealth-1.11.2-11.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.86.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
NEICorePlugin (NotEnoughItems-1.11.2-2.2.0.216-universal.jar)
  codechicken.nei.asm.NEITransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.57' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	nei Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Launched Version: forge-13.20.0.2294
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.57, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Gerudoku Faithful.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs_Vibrant_Shaders_v1.163_High.zip
	OpenGlVersion: 4.5.0 NVIDIA 378.57
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/a0b622393948770f5ad1be4fb49cbcccb53726a9
