### ISSUE TITLE
White fences don't join to other fences, *and* don't have a gate.

### ISSUE THREAD

**Issue by MentalMouse** [MrCrayfish/MrCrayfishFurnitureMod#165]
Version 4.1.2, MC 1.11.2.

As per subject, White fences don't join to other fences, *and* don't have a gate.  This makes it rather hard to use them for a perimeter.

**Comment by Rac3rZer0** [comment]
In reply to MentalMouse > Version 4.1.2, MC 1.11.2.

As per subject, White fences don't join to other fences, and don't have a gate. This makes it rather hard to use them for a perimeter.

It was made like that on purpose.

**Comment by darthvader45** [comment]
Well a white fence gate would be nice to have.
