### ISSUE TITLE
1.11.2 Dishwasher not working 4.1.2

### ISSUE THREAD

**Issue by BearlyCompetent** [MrCrayfish/MrCrayfishFurnitureMod#167]
1.11.2 Dishwasher not working 4.1.2, 

Will take the tools, the soapy water, but will not start.

Running Forge - forge-1.11.2-13.20.0.2309

**Comment by piks** [comment]
According to the script atm, it will only run if every slot in the dishwasher is used and is a valid recipe item, I have a patched version on my github if you know how to compile mods

**Comment by MrCrayfish** [comment]
Will look into the issue
