### ISSUE TITLE
1.11.2 When placing directional objects, some rotate.

### ISSUE THREAD

**Issue by Jigokusaru** [MrCrayfish/MrCrayfishFurnitureMod#170]
1: Come on MrCrayfish, get your stuff together, are you reading these? this mod looks like it hasn't been feed for a week, mods need love.
2: The issue, when I place certain objects, like doorbell or sink they rotate a different direction.  then the doorbell looks like its floating

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed issue in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/714f4dc359b53d5fdc31eb47263a0f26b514dd85
