### ISSUE TITLE
Mods in Curse

### ISSUE THREAD

**Issue by vpontin** [MrCrayfish/MrCrayfishFurnitureMod#171]
Hey MrCrayfish, do you ever think to release your mods on CurseForge?
It would be very good to control modpacks and stuff.
Thanks in advance and sorry for any inconvenience.

**Comment by LiamtjuhhZ** [comment]
Please also release these mods in 1.7.10! I'm begging you :C

**Comment by kinggoesgaming** [comment]
I support this... Curse has become one 3 main modpack compilation platforms, alongside FTB and Technic, so having the mod on curse would provide a convenient way to add the mod to modpacks hosted on curse

**Comment by MrCrayfish** [comment]
They are already hosted on Curse. I will be converting downloads from my site to be downloaded from curse instead.
