### ISSUE TITLE
MrCrayfishFurnitureMod not compatible with JEI 

### ISSUE THREAD

**Issue by KrauzeBartek** [MrCrayfish/MrCrayfishFurnitureMod#172]
MrCrayfishFurnitureMod is not compatible with JEI please do samethink with that.

**Comment by KrauzeBartek** [comment]
![2017-06-11_11 25 58](https://user-images.githubusercontent.com/29304275/27009901-895828ac-4e99-11e7-8aa8-7081d9b270e1.png)

**Comment by Ocelot5836** [comment]
looks comptable to me? The pink items are simply cray's messups with having items for blocks such as the fridge top and the closed curtain.

**Comment by Kenneth-Brandon** [comment]
https://www.reddit.com/user/6Brandons/draft/0568d634-34a3-11ea-91f4-dea815c6998b

**Comment by Kenneth-Brandon** [comment]
https://www.reddit.com/user/6Brandons/draft/0568d634-34a3-11ea-91f4-dea815c6998b

**Comment by Kenneth-Brandon** [comment]
https://www.reddit.com/user/6Brandons/draft/0568d634-34a3-11ea-91f4-dea815c6998b
