### ISSUE TITLE
1.11.2 client crash crafting soap water

### ISSUE THREAD

**Issue by leagris** [MrCrayfish/MrCrayfishFurnitureMod#176]
Reproduce:
Place soap and water bucket in crafting grid.
Attempt to collect soap water from result slot.
Client crash while CFM attempts to return the water bucket.
Returning in-game, water bucket is gone and no soap water.

cfm-4.1.2-mc1.11.2
[crash-2017-07-09_20.58.31-client.txt](https://gist.github.com/leagris/4a50c37d6c96bddd29831c690a2a6125)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/a0b622393948770f5ad1be4fb49cbcccb53726a9
