### ISSUE TITLE
Model Orientation Bug

### ISSUE THREAD

**Issue by NovaTheLynx** [MrCrayfish/MrCrayfishFurnitureMod#178]
Mysteriously, the doorbell tile block, seems to be having weird orientation issues. It looks like something might have been mapped incorrectly, when placed on some sides it works with weird results, other sides like left and right of the block its placed on it won't change states.

Screenshots of this weird 'bug':
![2017-07-16_18 41 11](https://user-images.githubusercontent.com/21307676/28250009-3127a312-6a58-11e7-9d18-2b7cb2f4f974.png)
![2017-07-16_18 33 49](https://user-images.githubusercontent.com/21307676/28250010-3129ca5c-6a58-11e7-888c-62735af134a0.png)
![2017-07-16_18 35 07](https://user-images.githubusercontent.com/21307676/28250011-312c8436-6a58-11e7-8b78-976ca74d3a0f.png)

I don't know if this is a visual bug or possible model mapping error.
Please can anyone see if this may be happening to them? Thanks.
P.S. I have checked to see if any issues are similar, but none look the same. 
References if any look the same would help.

**Comment by fcpwiz** [comment]
Similar issues:
- https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/130 (1.10.2, v4.1)
- https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/143 (1.10.2, v4.1.2)
- https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/170 (1.11.2, v?)

**Comment by PixelGamerX32** [comment]
Huh, so this bug persists in later versions too as it describes what I've seen in 1.10.2.

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed issue in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/714f4dc359b53d5fdc31eb47263a0f26b514dd85
