### ISSUE TITLE
[1.10.2] Shower/Shower head

### ISSUE THREAD

**Issue by SCaydi** [MrCrayfish/MrCrayfishFurnitureMod#179]
Excuse me, each time my friends and I, interact with this 2 blocks, our server crashes, and I was wondering if you are still working on this Mod issues.

Edit: Seems to be happening each time we are under the shower water drops, not exactly when we right click the mentioned items.

Crash Log:
https://pastebin.com/vCLjFiCW

**Comment by Jacksharkben** [comment]
i +1 this to same with me

**Comment by MrCrayfish** [comment]
I will look into the issue, however I kind of want to start phasing out 1.10.2 as it wasn't an significant version for mods. I made some changes in 1.11.2 to the line it was mentioning in the report. Hopefully not a problem now. Check out this commit: https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/6adca00ba19047d23a229ceecfbb3fe1572fb2ab
