### ISSUE TITLE
Placing Mirror block down causes an instant client crash.

### ISSUE THREAD

**Issue by NovaTheLynx** [MrCrayfish/MrCrayfishFurnitureMod#180]
Hey guys, I just attempted to place down a mirror from 1.10.2 version of MrCrayfish furniture mod and it crashed me instantly.
I have found that issue #156 describes this as I had just experienced.
Here is the crash report I recently just got which was generated from the crash.
Hope this can be fixed.

**Comment by MrCrayfish** [comment]
Check the issue you mentioned for my reply

**Comment by MrCrayfish** [comment]
Seems to been have fixed in this PR https://github.com/Growlith1223/ArsMagica2/pull/305
