### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by majinisinpu** [MrCrayfish/MrCrayfishFurnitureMod#183]
I found two problems so I report them.
1. Since I installed this mod, NEI mod don't display left half of their GUI on the inventory(1).

2.  When I use Japanese language, Item name is not displayed correctly.
When I use UK English language, Items' names are displayed correctly(2). 
But When I use Japanese language, they are displayed as non-readable words(3).

Thank you for reading this issue.
[my computer and mods]
OS - windows 10
CPU -  i7-4770   3.40GHz
GPU - GTX 1060
RAM - 8GB
Forge - 1.11.2-13.20.1.2386
mods - Buildcraft - 7.99.6
            Furniture mod - 4.1.2
            CodechickenLib - 3.0.0.287-universal
            CustomNPCs - 21-jul-2017
            ForestryForMinecraft - 5.3.4.119
            General gun's 
            IndustrialCraft²_experimental - 2-2.7.78-ex111 
            Just Enough Items - 4.5.0.291
            NotEnoughItems - 1.11.2-2.3.0.227-universal

(1)
![2017-08-17_20 54 55](https://user-images.githubusercontent.com/18363105/29411100-6264d8b0-838e-11e7-8509-3ef178125452.png)
(2)
![2017-08-17_20 56 29](https://user-images.githubusercontent.com/18363105/29411161-951534e4-838e-11e7-87a6-960c28d067ac.png)
(3)
![2017-08-17_21 44 47](https://user-images.githubusercontent.com/18363105/29412847-4fb0e98c-8395-11e7-912d-d2c78da4c15d.png)

**Comment by MrCrayfish** [comment]
Some strange issues and not marking this as closed yet. Basically what I have done is updated the resource folder by correctly added an mcmeta file. From my testing, Japanese is working correctly for me. I would look into NEI potentially ruining rendering after I release this update with a potential fix.

I've also changed the buttons in the creative GUI to be added on Post, hopefully fixing the issue but I'll get back to you on that as I cant run NEI in a deobfuscated environment.

**Comment by MrCrayfish** [comment]
Commits are:
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/c867d31fb15896cd9a5a3db851c23335662e26e1
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/52f3af0340115998a078ea1e264fd0e22e7284bd
