### ISSUE TITLE
duplication bug

### ISSUE THREAD

**Issue by runescapejon** [MrCrayfish/MrCrayfishFurnitureMod#184]
I found, so it involves the package from Mr crayfish furniture mod, you open the package place an item inside, keep GUI open and press Q when hovering over package. You can now take the item out of the package, close the gui, pick up dropped package, open it and a duplicate item will be found inside.
or you can put the item in the package gui and then hover your mouse over the item then drop it and then drop the package at the same time while your in the gui
either works
this also works with envelopes
can you possibly make a fast fix?

**Comment by Tony103** [comment]
@MrCrayfish 
 i am using a ban item plugin but because of this mod is forcing open the package gui which means events are being cancelled
probably a bug with the mod 
so i cannot really ban the item on the server can you please make a fast fix thanks!

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/54af36c80e103a8a2dc908f1238dd74f1f00b26c
