### ISSUE TITLE
Private Server - 1.11.2 - CPM Missing Class ServerProxy

### ISSUE THREAD

**Issue by JonnyBrando** [MrCrayfish/MrCrayfishFurnitureMod#186]
MC 1.11.2
Forge 13.20.1.2454
CPM 1.0.2

Error:
java.lang.ClassNotFoundException: com.mrcrayfish.paintings.MrCrayfishPaintingsMod$ServerProxy

[crash-2017-08-24_19.11.46-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/1250453/crash-2017-08-24_19.11.46-server.txt)

[fml-server-latest.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/1250455/fml-server-latest.txt)

**Comment by MrCrayfish** [comment]
Not the place to report this! Although I will keep this in mind

**Comment by JonnyBrando** [comment]
Sorry MrCrayfish, I couldn't find where the source was for CPM. I checked your other repos.

**Comment by JonnyBrando** [comment]
Oh, I found that I posted this back in Mar 2017, under HobbyMod thinking that might be it.

https://github.com/MrCrayfish/MrCrayfishHobbyMod/issues/1
