### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by GameSlayar** [MrCrayfish/MrCrayfishFurnitureMod#187]
When breaking a Christmas tree, 2 items drop on the ground instead of one.

V 4.1.2, Minecraft V 1.10.2

**Comment by MrCrayfish** [comment]
I don't support 1.10.2 anymore however I have fixed this in 1.11.2 https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/2fca852bc89b17928b3d43db99d16df9f80eb645
