### ISSUE TITLE
1.12 issue with Microwave

### ISSUE THREAD

**Issue by runescapejon** [MrCrayfish/MrCrayfishFurnitureMod#191]
when you shift click while your in the microwave you will crash 
here is the crash report 
https://pastebin.com/e6nbWdjs

**Comment by BinaryVigilante** [comment]
I have the same problem.

I'm running:
Forge version: 1.12.2 - 14.23.1.2555
Minecraft version: 1.12.2
Mod version: 4.1.5
Java: openjdk version "1.8.0_151"
Operating system: Xubuntu 16.04

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/0553e05b5dac55e29c957e2a55c872dc06e84b49
