### ISSUE TITLE
[Question] Crafttweaker

### ISSUE THREAD

**Issue by vpontin** [MrCrayfish/MrCrayfishFurnitureMod#193]
Does this mod have some degree of compatibility (like a "binding" with recipeapi) with jared's crafttweaker?
I mean if is possible to add recipes for oven or freezer for example.

Thanks in advance!

**Comment by bodieb1** [comment]
Mr. Crayfish has a recipe API for the Furniture Mod [here](https://mrcrayfish.com/recipeapi.php).

**Comment by vpontin** [comment]
Yeah, but someone will need to make a mod which exposes this api to zenscript.

**Comment by QuantumStatement** [comment]
I think this issue can be closed because Crafttweaker support will be added in the next version
