### ISSUE TITLE
Christmas Tree Duplication Glitch

### ISSUE THREAD

**Issue by Sade66** [MrCrayfish/MrCrayfishFurnitureMod#195]
Hello, a member on my staff team realized that when you break a Christmas tree from this mod, it turns into two trees. As far as I can tell this does not work for things placed on the tree, but I figured it should be brought to attention either way. Thanks! :)

**Comment by MrCrayfish** [comment]
Cheers for the report. What version of the mod and Minecraft are you using?

**Comment by Sade66** [comment]
It looks like I'm using version 4.1.2 of the mod, and I'm on Minecraft 1.10.2.

**Comment by MrCrayfish** [comment]
Unfortunately I do update version of the mod less than 1.11.2. So you will need to update to fix the issue.
