### ISSUE TITLE
Item Tooltips

### ISSUE THREAD

**Issue by TimGoll** [MrCrayfish/MrCrayfishFurnitureMod#196]
There are also no item tooltips in your TEs.
Add this to your clientGui Class
```java
@Override
public void drawScreen(int mouseX, int mouseY, float partialTicks) {
    super.drawScreen(mouseX, mouseY, partialTicks);
    renderHoveredToolTip(mouseX, mouseY);
}
```

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/2ca9574c296e0fcf5c1ec35be586e83f7f0688f5
