### ISSUE TITLE
Crash when trying to sit on toilet

### ISSUE THREAD

**Issue by BinaryVigilante** [MrCrayfish/MrCrayfishFurnitureMod#197]
Hi,

The game crashes when I left-click on the toilet to sit on it. I have done a little bit of testing and I hope  it helps:

The toilet works fine if I have the "fart-key" set to a letter, for example "L". But if I use some thing like "<", "´" or "½", the game crashes. Tho the "-" key works just fine. I have not tried all the keys there is, but I hope this helps.

I have tested without any other mods installed.

Forge version: 1.12.2 - 14.23.1.2555
Minecraft version: 1.12.2
Mod version: 4.1.5
Java: openjdk version "1.8.0_151"
Operating system: Xubuntu 16.04

Crash report (Using the "<" as the "fart-key"):
https://pastebin.com/TzjhpJj0

By the way, I love your mods! They are really good and I hope you keep working on them! :D

Kind regards
BinaryVigilante

**Comment by MrCrayfish** [comment]
The keybindings "<", "´" and "½" are not valid OpenGL keybindings. There is no unique button on the keyboard to press these characters. "<" is simply Shift + Comma.
