### ISSUE TITLE
Toaster accepts unlimited bread, still outputs two toast

### ISSUE THREAD

**Issue by capSAR273** [MrCrayfish/MrCrayfishFurnitureMod#20]
In the latest version, the toaster will accept any number of toast pieces, but when activated it will still spit out two pieces. Maybe just limit it to accepting two bread?

**Comment by capSAR273** [comment]
Same with the bread slices that are created through the chopping board :)

**Comment by MrCrayfish** [comment]
Thanks for the report, will fix the problem.

**Comment by MrCrayfish** [comment]
Fxed :)
