### ISSUE TITLE
I get this when using the microwave

### ISSUE THREAD

**Issue by tsjsw** [MrCrayfish/MrCrayfishFurnitureMod#200]
https://pastebin.com/xi2ZbthB - If this helps, I put Shit+Clicked a potato

**Comment by Rac3rZer0** [comment]
It happened to me too. But on something else.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/0553e05b5dac55e29c957e2a55c872dc06e84b49
