### ISSUE TITLE
Mailbox Not Working

### ISSUE THREAD

**Issue by number65259** [MrCrayfish/MrCrayfishFurnitureMod#201]
Shift+Right Click with signed package opens package instead of placing mail inside box. Shift+Right Click with signed envelope returns mailbox full msg (mailbox is empty) and opens the envelope.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/960a54b141fad41e068430ac27c4a61ce53294a4
