### ISSUE TITLE
I put Logdotzip's head in a blender and it blended into fruit juice without child mods!

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishFurnitureMod#202]
it is horrible! [look at the picture here or at discord](https://cdn.discordapp.com/attachments/370943365170069504/410889026950660097/2018-01-07_09.58.53.png)
the glitch is is that you can put one extra item in a blender with a real recipe without child mods or other modifications.
![2018-01-07_09 58 53](https://user-images.githubusercontent.com/35274722/35939269-4065a2e2-0c11-11e8-9c84-af8139075cfb.png)

**Comment by Rac3rZer0** [comment]
> well, ain't that horrible! - Rac3rZer0

ewww! {:

**Comment by Ocelot5836** [comment]
why did you put his head in a blender is the first question
