### ISSUE TITLE
[1.12.2]Several bugs

### ISSUE THREAD

**Issue by EnderTurret** [MrCrayfish/MrCrayfishFurnitureMod#204]
First one is one where any disks played in the jukebox play their sound up to three times, and the stereo will play it twice.

Second one is that the bedside cabinet GUIs do not have lang entries and display container.bedside_cabinet.

Third one is where middle clicking either the blinds or curtain blocks will give you a missing texture,
same thing happens when middle clicking a ceiling light that is on, and the lamp while it is on.

Fourth one is that sometimes when turning off the shower head, the sound will not stop immediately.

Fifth one: You can walk through bath tubs, (Not sure if this is intentional.) and when placing a bath tub facing south, you can not walk through the middle of it when you can when it is facing any other direction.

All of these happen when the only mod installed is cfm.
I am currently running cfm version 4.1.5, and Forge 14.23.2.2611.
Any other info you need I can provide.

**Comment by MrCrayfish** [comment]
Please separate issues. It's too hard for me to track what issues are resolved or not.
