### ISSUE TITLE
Crash by Shower Head

### ISSUE THREAD

**Issue by sandtechnology** [MrCrayfish/MrCrayfishFurnitureMod#206]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. ([优化]FoamFix-1.11.2-0.7.3-Anarchy.jar)
  SpongeCoremod ([插件-API]spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 18-2-19 上午12:00
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at com.mrcrayfish.furniture.tileentity.TileEntityShowerHead.func_73660_a(TileEntityShowerHead.java:64)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:229)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2838)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zkc000(WorldServer.java:2825)
	at net.minecraft.world.World.func_72939_s(World.java:6063)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2197)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mrcrayfish.furniture.tileentity.TileEntityShowerHead.func_73660_a(TileEntityShowerHead.java:64)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:229)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2838)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zkc000(WorldServer.java:2825)

-- Block entity being ticked --
Details:
	Name: cfmShowerHead // com.mrcrayfish.furniture.tileentity.TileEntityShowerHead
	Block type: ID #293 (tile.shower_head_on // com.mrcrayfish.furniture.blocks.BlockShowerHeadOn)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-273,66,-298), Chunk: (at 15,4,6 in -18,-19; contains blocks -288,0,-304 to -273,255,-289), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #293 (tile.shower_head_on // com.mrcrayfish.furniture.blocks.BlockShowerHeadOn)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:6063)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2197)

-- Affected level --
Details:
	Level name: world
	All players: 10 total; [EntityPlayerMP['ZhiZu'/133582, l='world', x=-8870.70, y=54.00, z=8860.03], EntityPlayerMP['Fu__Xi'/100693, l='world', x=-241.02, y=54.00, z=-246.81], EntityPlayerMP['Seth_AZ'/151042, l='world', x=-386.49, y=68.00, z=-217.84], EntityPlayerMP['Pao_hui'/76579, l='world', x=-265.31, y=63.06, z=-232.79], EntityPlayerMP['Uncle_Red'/184855, l='world', x=-805.48, y=64.00, z=-1000.74], EntityPlayerMP['Lovely_Snowy'/186041, l='world', x=-810.20, y=53.00, z=-1846.83], EntityPlayerMP['HokkaidoS'/186419, l='world', x=-328.69, y=63.00, z=-317.70], EntityPlayerMP['Li_Linya'/87126, l='world', x=-272.37, y=64.00, z=-297.38], EntityPlayerMP['Dream_run'/73880, l='world', x=-280.76, y=50.06, z=-149.42], EntityPlayerMP['Dustyice'/168173, l='world', x=-438.39, y=72.00, z=-144.34]]
	Chunk stats: ServerChunkCache: 1063 Drop: 0
	Level seed: -471316018
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-346,66,-207), Chunk: (at 6,4,1 in -22,-13; contains blocks -352,0,-208 to -337,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 5194663 game time, 5198664 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 18281 (now: true), thunder time: 2767 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge CauseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zhp000(MinecraftServer.java:3953)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1826684256 bytes (1742 MB) / 5935464448 bytes (5660 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 3 total; -XX:+AggressiveOpts -XX:+UseCompressedOops -Xmx10G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2477 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2477-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2477} [Minecraft Forge] (forge-1.10.2-12.18.3.2477-universal.jar) 
	UCHIJAAAA	spongeapi{5.2.0-SNAPSHOT-c675e80} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2477-5.2.0-BETA-2793} [SpongeForge] ([插件-API]spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] ([JEI-核心]jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] ([优化]FoamFix-1.11.2-0.7.3-Anarchy.jar) 
	UCHIJAAAA	cyclicmagic{1.10.30} [Cyclic] ([传送书]Cyclic-1.10.2-1.10.30.jar) 
	UCHIJAAAA	recipehandler{0.6} [NoMoreRecipeConflict] ([修复物品合成冲突]NoMoreRecipeConflict-0.6(1.10.2).jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] ([修改合成]CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	MineTweaker3{3.0.26} [MineTweaker 3] ([修改合成]CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] ([家具]cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAA	adamantineshield{0.3.3} [AdamantineShield] ([插件-查询]AdamantineShield-0.3.3（sand汉化）.jar) 
	UCHIJAAAA	flexiblelogin{0.14.6} [FlexibleLogin] ([插件-登录]flexiblelogin-0.14.6.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] ([更多箱子]ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] ([潘马斯]Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	pixelmon{5.1.2} [Pixelmon] ([神奇宝贝]Pixelmon-1.10.2-5.1.2.jar) 
	UCHIJAAAA	u_whitelist{1.0} [UWhitelist] (UWhitelist.jar) 
	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. ([优化]FoamFix-1.11.2-0.7.3-Anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
SpongeCoremod ([插件-API]spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 10 / 20; [EntityPlayerMP['ZhiZu'/133582, l='world', x=-8870.70, y=54.00, z=8860.03], EntityPlayerMP['Fu__Xi'/100693, l='world', x=-241.02, y=54.00, z=-246.81], EntityPlayerMP['Seth_AZ'/151042, l='world', x=-386.49, y=68.00, z=-217.84], EntityPlayerMP['Pao_hui'/76579, l='world', x=-265.31, y=63.06, z=-232.79], EntityPlayerMP['Uncle_Red'/184855, l='world', x=-805.48, y=64.00, z=-1000.74], EntityPlayerMP['Lovely_Snowy'/186041, l='world', x=-810.20, y=53.00, z=-1846.83], EntityPlayerMP['HokkaidoS'/186419, l='world', x=-328.69, y=63.00, z=-317.70], EntityPlayerMP['Li_Linya'/87126, l='world', x=-272.37, y=64.00, z=-297.38], EntityPlayerMP['Dream_run'/73880, l='world', x=-280.76, y=50.06, z=-149.42], EntityPlayerMP['Dustyice'/168173, l='world', x=-438.39, y=72.00, z=-144.34]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by MrCrayfish** [comment]
Update to 1.12.2
