### ISSUE TITLE
Toaster only renders contents from opposite side

### ISSUE THREAD

**Issue by capSAR273** [MrCrayfish/MrCrayfishFurnitureMod#21]
Here's an example with bread slices: https://www.youtube.com/watch?v=n1gVoRbMh3E

**Comment by MrCrayfish** [comment]
This might be due to you having fast rendering on. I will look into the issue and see if there is a fix

**Comment by capSAR273** [comment]
Ahh, I might have had that enabled! I've been using Optifine to get smoother performance lately.
