### ISSUE TITLE
Most blocks that have a container/gui do not render tooltips.

### ISSUE THREAD

**Issue by Ocelot5836** [MrCrayfish/MrCrayfishFurnitureMod#210]
The guis don't render tooltips because in 1.12 it needs to be done manually.

![image](https://user-images.githubusercontent.com/19599406/37807906-175562f0-2e05-11e8-9062-7f714ffd5e4d.png)

**Comment by MrCrayfish** [comment]
Thanks for report. Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/2ca9574c296e0fcf5c1ec35be586e83f7f0688f5
