### ISSUE TITLE
[Furniture Mod 4.2.0-Forge-1.12.2] Invalid statistic errors

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishFurnitureMod#214]
I'm seeing these errors on the server console:

26.03 12:24:25 [Server] Server thread/WARN Invalid statistic in ./world2018/stats/ebbae4e3-4a3c-4c8b-9475-e9d07ee7f6ab.json: Don't know what stat.mineBlock.cfm.ceiling_light_on is
26.03 12:24:25 [Server] Server thread/WARN Invalid statistic in ./world2018/stats/ebbae4e3-4a3c-4c8b-9475-e9d07ee7f6ab.json: Don't know what stat.pickup.cfm.ceiling_light_on is
26.03 12:24:25 [Server] Server thread/WARN Invalid statistic in ./world2018/stats/ebbae4e3-4a3c-4c8b-9475-e9d07ee7f6ab.json: Don't know what stat.mineBlock.cfm.shower_top is
26.03 12:24:25 [Server] Server thread/WARN Invalid statistic in ./world2018/stats/ebbae4e3-4a3c-4c8b-9475-e9d07ee7f6ab.json: Don't know what stat.useItem.cfm.ceiling_light_on is
26.03 12:24:25 [Server] Server thread/WARN Invalid statistic in ./world2018/stats/ebbae4e3-4a3c-4c8b-9475-e9d07ee7f6ab.json: Don't know what stat.mineBlock.cfm.bath_top is

**Comment by MrCrayfish** [comment]
This is a side affect of removing the item version of blocks in the latest update. It's impossible to get these blocks as an item so I decided to remove the ability to have them as an item and only allow them to be a block in the world. Unfortunately there is not a lot I can do, I've already added them to an ignore list.
