### ISSUE TITLE
Fire alarm not beeping. 1.12.2

### ISSUE THREAD

**Issue by bodieb1** [MrCrayfish/MrCrayfishFurnitureMod#216]
**Hello Everyone**
----
I recently built a house in Minecraft and I put up fire alarms. My house ended up burning down. I was like hmm... So I tested the fire alarm and it lights up but it doesn't beep.

**Comment by MrCrayfish** [comment]
Have you updated to v4.2.0?

**Comment by bodieb1** [comment]
Probably not. Thank you!
