### ISSUE TITLE
Odd Black Gradient Texture on Objects - 1.11.2

### ISSUE THREAD

**Issue by WalkerNewton** [MrCrayfish/MrCrayfishFurnitureMod#217]
This is a screenshot of the issue. I don't fully understand what is causing it. We did update the server from 1.10.2 to 1.11.2, maybe we have to remove the mod fully, and then re-add it? - Any help on this subject would be appreciated!

![2018-04-01_23 50 34](https://user-images.githubusercontent.com/37993138/38182723-7128a024-3609-11e8-9c9f-df18643ecddd.png)
![2018-04-01_23 52 14](https://user-images.githubusercontent.com/37993138/38182724-713756b4-3609-11e8-8a55-4a31106b0420.png)
![2018-04-01_23 52 16](https://user-images.githubusercontent.com/37993138/38182725-7146fb78-3609-11e8-82c8-7b829095255c.png)

**Comment by MrCrayfish** [comment]
One word, optifine
