### ISSUE TITLE
Bucket dupe crafting super soapy water

### ISSUE THREAD

**Issue by Skalfred** [MrCrayfish/MrCrayfishFurnitureMod#221]
Craft a bucket of super soapy water and the water in the bucket is used up and leaves the bucket in the crafting table giving new bucket with super soapy water.

Version #: 4.2.0
Modpack: [Magiculture 2](https://minecraft.curseforge.com/projects/magiculture-2?gameCategorySlug=modpacks&projectID=282334)

**Comment by fandomaniac** [comment]
This bug still exist in version: 5.4.1.

**Comment by Sebqy** [comment]
this is in latest 1.12.2 version as well

**Comment by TheDarkDnKTv** [comment]
Closed, but wasn't fixed.
