### ISSUE TITLE
Door Mat Gui doesnt show when placing on a non-full block.

### ISSUE THREAD

**Issue by TeKGameR950** [MrCrayfish/MrCrayfishFurnitureMod#229]
Hi cray! as you can see on the GIF, door mat gui's is opening and instantly closing when we place it on a non-full block! :/ I'm using latest forge and latest version of the mod.

https://imgur.com/a/1GSinRu

Thanks, Have a good cheesy time!

**Comment by MrCrayfish** [comment]
I am unable to reproduce and marking this as fixed in the latest version
