### ISSUE TITLE
[CFM version: 4.3.0] Multiplayer Server Crash - Exception in server tick loop

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishFurnitureMod#235]
I updated the Furniture Mod to 4.3.0 from version 4.2.0 and it is causing a server crash.

Here's the Crash Report:

Time: 6/21/18 2:41 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.mrcrayfish.furniture.items.ItemEnvelopeSigned.func_77653_i(ItemEnvelopeSigned.java:63)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:1047)
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:201)
	at net.minecraft.stats.StatList.reinit(StatList.java:346)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:559)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.11.0-26-generic
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2563767552 bytes (2444 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 4 total; -Xmx4096M -Xms4096M -XX:+UseG1GC -Xss2M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2709 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version              | Source                                         | Signature                                |
	|:------ |:-------------------- |:-------------------- |:---------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft            | 1.12.2               | minecraft.jar                                  | None                                     |
	| UCHIJA | mcp                  | 9.42                 | minecraft.jar                                  | None                                     |
	| UCHIJA | FML                  | 8.0.99.99            | custom.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                | 14.23.4.2709         | custom.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | openmodscore         | 0.11.5               | minecraft.jar                                  | None                                     |
	| UCHIJA | foamfixcore          | 7.7.4                | minecraft.jar                                  | None                                     |
	| UCHIJA | obfuscate            | 0.2.4                | minecraft.jar                                  | None                                     |
	| UCHIJA | quark                | r1.4-125             | Quark-r1.4-125.jar                             | None                                     |
	| UCHIJA | autoreglib           | 1.3-18               | AutoRegLib-1.3-18.jar                          | None                                     |
	| UCHIJA | backpacks16840       | 3.5.2                | backpacks 1.12.2 - 3.5.2.jar                   | None                                     |
	| UCHIJA | bibliocraft          | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
	| UCHIJA | cfm                  | 4.3.0                | cfm-4.3.0-mc1.12.2.jar                         | None                                     |
	| UCHIJA | chameleon            | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| UCHIJA | chesttransporter     | 2.8.8                | ChestTransporter-1.12.2-2.8.8.jar              | None                                     |
	| UCHIJA | cjcm                 | 1.0                  | cjcm-1.0.jar                                   | None                                     |
	| UCHIJA | codechickenlib       | 3.1.9.344            | CodeChickenLib-1.12.2-3.1.9.344-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | cookingforblockheads | 6.4.40               | CookingForBlockheads_1.12.2-6.4.40.jar         | None                                     |
	| UCHIJA | craftablesaddles     | 1.3                  | Craftable+Saddles[1.12]-1.3.jar                | None                                     |
	| UCHIJA | customnpcs           | 1.12                 | CustomNPCs_1.12.2(20jan18).jar                 | None                                     |
	| UCHIJA | ptrmodellib          | 1.0.2                | PTRLib-1.0.2.jar                               | None                                     |
	| UCHIJA | props                | 2.6.0                | Decocraft-2.6.0_1.12.2.jar                     | None                                     |
	| UCHIJA | cdm                  | 0.4.1                | device-mod-0.4.1-1.12.2.jar                    | None                                     |
	| UCHIJA | gottschcore          | 1.3.5                | GottschCore-mc1.12-f14.21.1.2387-v1.3.5.jar    | None                                     |
	| UCHIJA | dungeons2            | 1.3.3                | Dungeons2-mc1.12-f14.21.1.2387-v1.3.3.jar      | None                                     |
	| UCHIJA | dungeontactics       | DT-0.14.2            | DungeonTactics-1.12.2-0.14.2.jar               | None                                     |
	| UCHIJA | ebwizardry           | 4.1.2                | Electroblob's Wizardry - 4.1.2 - MC 1.12.2.jar | None                                     |
	| UCHIJA | fastleafdecay        | v14                  | FastLeafDecay-v14.jar                          | None                                     |
	| UCHIJA | foamfix              | 0.9.9.1-1.12.2       | foamfix-0.9.9.1-1.12.2-anarchy.jar             | None                                     |
	| UCHIJA | foamflower           | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar            | None                                     |
	| UCHIJA | gravestone           | 1.10.1               | gravestone-1.10.1.jar                          | None                                     |
	| UCHIJA | infernalmobs         | 1.7.5                | InfernalMobs-1.12.2.jar                        | None                                     |
	| UCHIJA | ironchest            | 1.12.2-7.0.40.824    | ironchest-1.12.2-7.0.40.824.jar                | None                                     |
	| UCHIJA | jei                  | 4.9.2.196            | jei_1.12.2-4.9.2.196.jar                       | None                                     |
	| UCHIJA | jrftl                | 1.1                  | JRFTL[1.12.2]-1.1.jar                          | None                                     |
	| UCHIJA | lootbags             | 2.5.6                | LootBags-1.12.2-2.5.6.jar                      | None                                     |
	| UCHIJA | lunatriuscore        | 1.2.0.42             | LunatriusCore-1.12.2-1.2.0.42-universal.jar    | None                                     |
	| UCHIJA | lycanitesmobs        | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | arcticmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | demonmobs            | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | desertmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | elementalmobs        | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | forestmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | freshwatermobs       | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | infernomobs          | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | junglemobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | mountainmobs         | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | plainsmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | saltwatermobs        | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | shadowmobs           | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | swampmobs            | 1.20.3.1 - MC 1.12.2 | LycanitesMobsComplete 1.20.3.1 [1.12.2].jar    | None                                     |
	| UCHIJA | malisiscore          | 1.12.2-6.4.0         | malisiscore-1.12.2-6.4.0.jar                   | None                                     |
	| UCHIJA | malisisblocks        | 1.12.2-6.1.0         | malisisblocks-1.12.2-6.1.0.jar                 | None                                     |
	| UCHIJA | malisisdoors         | 1.12.2-7.3.0         | malisisdoors-1.12.2-7.3.0.jar                  | None                                     |
	| UCHIJA | mantle               | 1.12-1.3.2.24        | Mantle-1.12-1.3.2.24.jar                       | None                                     |
	| UCHIJA | natura               | 1.12.2-4.3.2.49      | natura-1.12.2-4.3.2.49.jar                     | None                                     |
	| UCHIJA | nex                  | 2.1.14.15            | NetherEx-1.12-2.1.14.15.jar                    | None                                     |
	| UCHIJA | recipehandler        | 0.10                 | NoMoreRecipeConflict-0.10(1.12.2).jar          | None                                     |
	| UCHIJA | nei                  | 2.4.1                | NotEnoughItems-1.12.2-2.4.1.233-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | openmods             | 0.11.5               | OpenModsLib-1.12.2-0.11.5.jar                  | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJA | openblocks           | 1.7.6                | OpenBlocks-1.12.2-1.7.6.jar                    | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJA | guilib               | $version             | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar  | None                                     |
	| UCHIJA | paintingselgui       | $version             | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar  | None                                     |
	| UCHIJA | harvestcraft         | 1.12.2u              | Pam's HarvestCraft 1.12.2u.jar                 | None                                     |
	| UCHIJA | roguelike            | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| UCHIJA | simplecore           | 1.6.0.6              | simplecore-1.12.2-1.6.0.6.jar                  | None                                     |
	| UCHIJA | simpleores           | 1.11.1.9             | simpleores-1.12.2-1.11.1.9.jar                 | None                                     |
	| UCHIJA | simplyenchanting     | 1.0.3                | SimplyEnchanting-1.12-1.0.3.jar                | None                                     |
	| UCHIJA | soccer               | 1.0                  | soccer-mod-1.0-1.12.2.jar                      | None                                     |
	| UCHIJA | storagedrawers       | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.6.jar                | None                                     |
	| UCHIJA | tconstruct           | 1.12.2-2.10.1.87     | TConstruct-1.12.2-2.10.1.87.jar                | None                                     |
	| UCHIJA | treechopper          | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                   | None                                     |
	| UCHIJA | variedcommodities    | 1.12.2               | VariedCommodities_1.12.2(15may18.jar           | None                                     |
	| UCHIJA | varodd               | 3.1                  | varodd-1.12.2-3.1.jar                          | None                                     |
	| UCHIJA | vehicle              | 0.14.0               | vehicle-0.14.0-mc1.12.2.jar                    | None                                     |
	| UCHIJA | vending              | 1.12.2-3.0.1.1       | vending-1.12.2-3.0.1.1.jar                     | None                                     |
	| UCHIJA | waystones            | 4.0.43               | Waystones_1.12.2-4.0.43.jar                    | None                                     |
	| UCHIJA | worldutils           | 0.4.2                | worldutils-1.12.2-0.4.2.jar                    | 2b03e1423915a189b8094816baa18f239d576dff |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
BCModPlugin (backpacks 1.12.2 - 3.5.2.jar)
  brad16840.core.ClassTransformer
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by BearlyCompetent** [comment]
I am also experiencing a crash when trying to run this mod (and only this mod) on a Forge 1.12.2-14.23.4.2705 server. I removed all other mods, and created a new world and it will not load. Works fine single player with same forge version.

> ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/24/18 9:14 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.mrcrayfish.furniture.items.ItemEnvelopeSigned.func_77653_i(ItemEnvelopeSigned.java:63)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:1047)
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:201)
	at net.minecraft.stats.StatList.reinit(StatList.java:346)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:559)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 29 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-93-generic
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3650692952 bytes (3481 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	JVM Flags: 3 total; -Xmx4096M -Xms4096M -Xss2M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                                  | Signature                                |
	|:------ |:--------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft | 1.12.2       | minecraft.jar                           | None                                     |
	| UCHIJA | mcp       | 9.42         | minecraft.jar                           | None                                     |
	| UCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.4.2705-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge     | 14.23.4.2705 | forge-1.12.2-14.23.4.2705-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | cfm       | 4.3.0        | cfm-4.3.0-mc1.12.2.jar                  | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by iBars** [comment]
The same bug on server

**Comment by BearlyCompetent** [comment]
Plugin seems to be working now with version 5.0.0 that was released. My server started with the plugin.

**Comment by BearlyCompetent** [comment]
I recommend anyone having the issue with 4.3.0 upgrade to the 5.0.0 furniture mod.

**Comment by iBars** [comment]
Yes, it helped!

**Comment by fandomaniac** [comment]
The newer updates have fixed the issue.
