### ISSUE TITLE
Modern Widows - Strange Graphical Glitch with Resource Pack

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishFurnitureMod#238]
We're running on a SMP server with a BDcraft Sphax Resource Pack and we are seeing strange graphical glitch/atifacting. See screen grab:
![2018-06-29_23 26 23](https://user-images.githubusercontent.com/37810246/42127092-96eb02e6-7c60-11e8-8efa-0d138e552bad.png)

**Comment by fandomaniac** [comment]
![2018-07-01_01 00 39](https://user-images.githubusercontent.com/37810246/42131496-11d29d00-7cd1-11e8-8b50-6e5626edde4a.png)

**Comment by JacksonPlayz** [comment]
Cray can't really do anything about it since the UVs were made using Minecraft textures. The Sphax pack doesn't have glass like Minecraft so it's gonna look weird.
