### ISSUE TITLE
[CFM version: 5.1.0] Non-Vanilla Armor Pieces Can No Longer be Placed in Washing Machines

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishFurnitureMod#239]
It seems that non-vanilla armor pieces can longer be placed in Washing Machines. I've tried SimpleOres 2 and Dungeon Tactics armor pieces.

**Comment by MrCrayfish** [comment]
You need to specify it in the config now. This was unintended that it allowed everything.

**Comment by fandomaniac** [comment]
How do I specify other armor types in the config file?

**Comment by MrCrayfish** [comment]
```
recipe-api {
    # Insert custom recipes here [default: ]
    S:custom-recipes <
         "type=washing_machine,input-item=modid:itemid",
         "type=washing_machine,input-item=modid:itemid",
         "type=washing_machine,input-item=modid:itemid"
     >
}
```

**Comment by fandomaniac** [comment]
Awesome, thanks!

**Comment by fandomaniac** [comment]
I've added these, but their not working:
recipe-api {
    # Insert custom recipes here [default: ]
    S:custom-recipes <
        "type=washing_machine,input-item=simpleores:onyx_helmet",
        "type=washing_machine,input-item=simpleores:onyx_chestplate",
        "type=washing_machine,input-item=simpleores:onyx_leggings",
        "type=washing_machine,input-item=simpleores:onyx_boots"
     >
Does that look correct? I did a triple-check of the modid and itemid and they are correct.

**Comment by MrCrayfish** [comment]
Try removing the quotes and comma. I forgot how arrays work in the config

**Comment by fandomaniac** [comment]
Ok. Thanks again!

**Comment by fandomaniac** [comment]
I changed it to this and it's still not working:
recipe-api {
    # Insert custom recipes here [default: ]
    S:custom-recipes <
        type=washing_machine,input-item=simpleores:onyx_helmet
        type=washing_machine,input-item=simpleores:onyx_chestplate
        type=washing_machine,input-item=simpleores:onyx_leggings
        type=washing_machine,input-item=simpleores:onyx_boots
     >
}

**Comment by MrCrayfish** [comment]
Can you go into the config an enable recipe api output then post the log of your game startup

**Comment by fandomaniac** [comment]
Here's what I got:
[com.mrcrayfish.furniture.api.RecipeRegistry:registerConfigRecipes:1089]: RecipeAPI (Configuration): Registering 4 recipes from the config.
15.07 00:40:28 [Server] Server thread/WARN [cfm]: ## RecipeAPI Error Report ##
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Recipe Number: 1
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Type: washing_machine (Error)
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Description: The recipe type 'washing_machine' does not exist
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Variables: 
15.07 00:40:28 [Server] Server thread/WARN [cfm]: - input-item: simpleores:onyx_helmet
15.07 00:40:28 [Server] Server thread/WARN [cfm]: ## RecipeAPI Error Report ##
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Recipe Number: 2
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Type: washing_machine (Error)
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Description: The recipe type 'washing_machine' does not exist
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Variables: 
15.07 00:40:28 [Server] Server thread/WARN [cfm]: - input-item: simpleores:onyx_chestplate
15.07 00:40:28 [Server] Server thread/WARN [cfm]: ## RecipeAPI Error Report ##
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Recipe Number: 3
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Type: washing_machine (Error)
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Description: The recipe type 'washing_machine' does not exist
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Variables: 
15.07 00:40:28 [Server] Server thread/WARN [cfm]: - input-item: simpleores:onyx_leggings
15.07 00:40:28 [Server] Server thread/WARN [cfm]: ## RecipeAPI Error Report ##
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Recipe Number: 4
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Type: washing_machine (Error)
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Description: The recipe type 'washing_machine' does not exist
15.07 00:40:28 [Server] Server thread/WARN [cfm]: Variables: 
15.07 00:40:28 [Server] Server thread/WARN [cfm]: - input-item: simpleores:onyx_boots

**Comment by MrCrayfish** [comment]
Sorry, it's actually `washingmachine`

**Comment by fandomaniac** [comment]
It's working now. Thanks.
