### ISSUE TITLE
Questions about upcoming PRs

### ISSUE THREAD

**Issue by Phylogeny** [MrCrayfish/MrCrayfishFurnitureMod#243]
@MrCrayfish I've implemented the ability of light switches to render text on their backing blocks or hovering above themselves. Light switches can be named upon placement (like the door mat), and when they break, the items they drop retain their names. They can be renamed with a right click while sneaking.

![Light Switch Names](https://s26.postimg.cc/ed18qw62x/Light_Switch_Names.png)

As a result of wanting to add configs via Forge's annotation system (which I have since done), I've also gone ahead and ported all the configs in this mod to that system. So, I have a few questions:
1. Should naming upon placement via the GUI only be done if sneaking, or should the GUI come up every time, like the door mat?
2. Should I give the door mat the same ability to place pre-named via a named stack, to drop a named stack, and to be renameable?
3. Should I submit all the refactoring to Forge's config annotation system in a separate PR first, before submitting the PR with the name rendering changes?
4. I noticed that the exact same 3 sync methods are in many TE classes. Should I bundle the refactor to a TE baseclass in one of the above mentioned PRs, or submit it separately as well?

**Comment by MrCrayfish** [comment]
1. Making it consistent like the door mat I think will fit best
2. I don't think pre-named should work, only give the ability to name in the GUI. When dropping, it should not include the name just in case the player makes a type and needs to fix it. Same should apply to the light switch.
3. Yes if you can, it will be easier for me to track changes.
4. Yes, that is fine as long as it doesn't break anything. Separately if possible, I like keeping track of changes

**Comment by Phylogeny** [comment]
1. I agree.
2. Right now, I have it sow that they can be renamed upon sneak-right-clicking them. Is that better, or not? After all, they remember their control lights when broken, and the name goes with the light set. Your call.
3. No problem.
4. It wont; it's actually very simple.

**Comment by MrCrayfish** [comment]
I like to think about it like a sign, just simply breaking it and replacing will allow you to change the text. It's something players are already familiar with.

**Comment by Phylogeny** [comment]
Ok. Yeah, you mentioned liking to preserve vanilla mechanics.

**Comment by MrCrayfish** [comment]
Wait, I do like the idea of shift and right clicking to bring up the GUI on placement. I want to start adding Block#addInformation() to most furniture to tell people how to use them and this could simply be mentioned in that.

**Comment by Phylogeny** [comment]
Ahh. Yeah, that would be good. Sure thing.
