### ISSUE TITLE
Better chopped log's recipe

### ISSUE THREAD

**Issue by mcBegins2Snow** [MrCrayfish/MrCrayfishFurnitureMod#258]
mod:5.3.1
mc:1.12.2
Single game
Crafting chopped logs will complete cost a new vanilla axe and an oak wood only.It's not convenient.
In my opinion,the axe is an any axe with any durability damage,then the axe will cost 1 durability after crafting,and the wood should be compatible with ore dictionary logWood.The logWood means that it is a kind of woods in Minecraft.

**Comment by QuantumStatement** [comment]
It's already working as you suggest
![2018-07-25_11 10 47](https://user-images.githubusercontent.com/35406698/43187966-a4889de2-8ffb-11e8-9454-8d9189b51ca8.png)

Furniture mod 5.3.1
Minecraft 1.12.2
Forge 14.23.4.2705
No other mods

**Comment by mcBegins2Snow** [comment]
I understand.
