### ISSUE TITLE
Toilet Fart crash [1.12.2]

### ISSUE THREAD

**Issue by ehmitchell3** [MrCrayfish/MrCrayfishFurnitureMod#267]
Hey MCF,

Running a rather large modpack (Tekxit 3), and I've noticed that even as an admin/poweruser, sitting on the toilet and pressing the fart key will fatal error out the client. 

Server still is fine, and it works in Single player, but the kicker is, there's no crash log or standard log.

I'm wondering if it has anything to do with advancement on the server, so I'm trying to force it through the achievement command, but I'm not sure what to put in the command.

They keybind is F, and there's no conflicts.

Any help, whether it's in the advancement area, or with known conflicting mods would be great.

Thanks!
-

**Comment by JacksonPlayz** [comment]
It's due to a bug with the advancements and has been fixed. Download the most recent version.
