### ISSUE TITLE
Envelope seeming to not save NBT data correctly

### ISSUE THREAD

**Issue by dsmall3303** [MrCrayfish/MrCrayfishFurnitureMod#268]
##Mods:
Mod version: 5.3.1-1.12.2
Forge version: 1.12.2-14.23.4.2739
Minecraft version: 1.12.2

Other involved mods:
Immersive Engineering, version 0.12-84
Vampirism: Become a Vampire, version 1.12.2-1.4.3
Thaumcraft 6, version 1.12.6-6.1.BETA19
##What happened:
Immersive Engineering crate lost its inventory after being put in an envelope

##What you expected to happen:
Immersive engineering crate should keep its inventory

##Steps to reproduce:
1) Place down mailbox
2) Place down vanilla chest
3) Place down Immersive Engineering Wooden Storage Crate and put a human heart from Vampirism, and two silverwood saplings from Thaumcraft in the crate
4) Break the crate with an axe so that you can pick up the crate with it keeping its inventory
5) Place the crate in the envelope, seal it, and place the envelope in the vanilla chest
6) open chest and remove the envelope, open the envelope, and place the crate

**Comment by MrCrayfish** [comment]
Not sure what to tell you. I don't know how "Immersive Engineering Wooden Storage Crate" stores it's data. Anything in the ItemStack's NBT should be saved in the Envelope. Do you happen to be in creative mode? There are bugs with how NBT is handed in the inventory which is out of my control.
