### ISSUE TITLE
[Suggestion] TV assets can be reduced in size.

### ISSUE THREAD

**Issue by Tokeli** [MrCrayfish/MrCrayfishFurnitureMod#270]
Half of the size of the .jar file is simply the animated PNGs for the TV. I know 9mb isn't much, but it does seem slightly large. 

PNGQuant ( https://pngquant.org/ ) is a PNG compressor, and I ran it on channel_heman.png and channel_cooking.png.

It took heman from 1.8mb to 350Kb with very little quality loss, and cooking from 331Kb to 164Kb with no visible quality loss at all.

Optimizing just the TV assets would make the mod half its current size and wouldn't cause any issues.

**Comment by QuantumStatement** [comment]
I think this problem is already [resolved](https://twitter.com/MrCraayfish/status/1027240738650615808)
