### ISSUE TITLE
TV glitch (Minecraft menu)

### ISSUE THREAD

**Issue by dogoverlord** [MrCrayfish/MrCrayfishFurnitureMod#273]
_**this glitch occurred on the modern tv update (5.5.0)**_
**Edit: This glitch only occurs when the render distance is lower than 4**

Hey Cray! Your Probably aware of this but there is a really weird bug in the furniture mod with the flat screen tv, it occurs when you play a gif on the tv and then open the pause menu. It does a weird color glitching thing, and when you change to a different world, the bug stays in effect. it changes to the colors of the gif that your playing on the tv like this one is mostly blue. It doesn't just happen with the pause menu, but also at any time the game is paused, such as changing the gif on the tv.

I hope this is helpful 
Thank you 

Instructions on getting the glitch (pretty obvious)

1. place down a tv (i use a modern tv but a normal one should work too)

2.put in a gif

3.once the gif has appeared on the tv, pause the game.

4.glitch should have happened

![glitch](https://user-images.githubusercontent.com/42335681/44017839-1490580c-9f1d-11e8-8772-96db7d296025.png)
![glitch 2](https://user-images.githubusercontent.com/42335681/44017837-142bbcbc-9f1d-11e8-93d5-b955b3694ef5.PNG)
![glitch 1](https://user-images.githubusercontent.com/42335681/44017838-145fa5b8-9f1d-11e8-97a6-3be96ad754e1.PNG)
![glitch 4](https://user-images.githubusercontent.com/42335681/44018883-893b85e8-9f20-11e8-8d22-ee27b22a69e4.PNG)
![glitch 5](https://user-images.githubusercontent.com/42335681/44018998-e245d530-9f20-11e8-83d0-958047c71309.PNG)

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
