### ISSUE TITLE
[1.12.2] Game STILL crashes when you touch the Electric Fence that is placed on a Chisel'd Block.

### ISSUE THREAD

**Issue by Z-Tunic** [MrCrayfish/MrCrayfishFurnitureMod#276]
Referenced Issue:
https://github.com/Chisel-Team/Chisel/issues/704

The last time I reported this issue was back in June 22, 2018... 

https://minecraft.curseforge.com/projects/mrcrayfish-furniture-mod/issues/70

...however it seems that it cannot be found anymore so I'm just going to open it here. I'm also linking the issue that I opened on chisel's issue forum here for reference and they've mentioned that it isn't a problem on their end.

This bug was present in "furniture-4.2.0-1.12.2" and at the time of this post... with what's being used right now... the bug is STILL present.

-----

Minecraft: 1.12.2
Forge: 14.23.4.2725

Mods:
Chisel-MC1.12-0.2.0.30
CTM-MC1.12.2-0.3.2.18
furniture-5.5.1-1.12.2

Crash Report:
https://pastebin.com/w4Rc4wfX

**Comment by MrCrayfish** [comment]
Fixed in the next update 5.6.0 which will be released tomorrow
