### ISSUE TITLE
Parsing error loading recipe SPONGE FORGE 1.12.2 (7.1.0-BETA-3332 / Forge 14.23.4.2705)

### ISSUE THREAD

**Issue by LeChevalierDOr** [MrCrayfish/MrCrayfishFurnitureMod#277]
**Describe the bug**
Parsing error loading recipe

**Crash report**
https://pastebin.com/G1Ta63Pw

**To Reproduce**
Launch the game with SPONGE FORGE 1.12.2 (7.1.0-BETA-3332 / Forge 14.23.4.2705) and look the consol 

**Screenshots**
No screenshots

Please complete the following information:
- Minecraft Version: SPONGE FORGE 1.12.2 (7.1.0-BETA-3332 / Forge 14.23.4.2705)
- Mod Version: I don't know sorry...

**Comment by MrCrayfish** [comment]
Update to the latest version
