### ISSUE TITLE
Duplicating Oak Hedges

### ISSUE THREAD

**Issue by Hypocrisy** [MrCrayfish/MrCrayfishFurnitureMod#28]
The issue appear when using a Shear on any type of hedge. It will drop itself as well as an item named tile.hedge.name that can then be placed again as an Oak Hedge wherein you can repeat the process of shearing and placing, effectively duplicating your hedges. 

Also, as a side note, your Spruce Hedge is named "Spurce Hedge".

**Comment by MrCrayfish** [comment]
Which version are you using? This is not present in the latest 1.8 build.

**Comment by Hypocrisy** [comment]
Ah, sorry. I am indeed using 3.4.8 on 1.7.10

**Comment by MrCrayfish** [comment]
Might get a fix out for it. Trying to focus on 1.8 and above now.
