### ISSUE TITLE
Duplication bug with presents

### ISSUE THREAD

**Issue by 777-Scorpion-777** [MrCrayfish/MrCrayfishFurnitureMod#280]
When you put item into stack of presents, this item appears in each present. This issue was posted on forum already, but it was in 2016 and still not fixed! I hope you do something with it. This is description of issue: https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/105.

**Comment by MrCrayfish** [comment]
Should be fixed in f9b667b8365e5b020ed65d9275a337fce097cc34
