### ISSUE TITLE
Run out of memory 5.5.1 1.12.2

### ISSUE THREAD

**Issue by Tarena397** [MrCrayfish/MrCrayfishFurnitureMod#281]
Hello, I have a problem with version 5.5.1 on 1.12.2
Last time I installed Furniture mod was on 1.7.10 and it worked perfectly!
Right now Minecraft says it runs out of memory, even tho I increased my memory from 1 to 2 (in case other mods worked with 1ram available)

I experimented with removing other mods (I left only better fps, optimize and liteloader, the furniture just crashes on the desktop while I trying to load the world in the game).
I tried to delete JAVA_OPTIONS, but I realized I did not even have that it in Windows Environmental Variables.

I included here a debug file.
Thank You For Your Help!

**Describe the bug**
Run out of Memory
Increased ram, still does nothing.

**Crash report**
[debug.log](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/2299145/debug.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/20219520/44295894-b238d380-a306-11e8-9e61-ba82228e9728.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 5.5.1

**Comment by Tarena397** [comment]
Update:
Increased up to 4gb - works.
//
That's weird, do I really need to increase the memory up to 4gb to make it work?

**Comment by MrCrayfish** [comment]
This is not an issue because of my mod. The more mods you add to your game, the more memory you may need.
