### ISSUE TITLE
Source for v3.4.8

### ISSUE THREAD

**Issue by Eonasdan** [MrCrayfish/MrCrayfishFurnitureMod#29]
Could you provide the source (or what commit it was) for version 3.4.8 (MC 1.7.10)? I'd like to make some minor adjustments to your mod but several of my favorite mods are still on 1.710.

If I get my changes to work, I might be willing to port them to 1.8 as a PR if you're interested.

Thanks

**Comment by NDruce** [comment]
I want too, MrCrayfish, please

**Comment by ShadowCoder69** [comment]
#49
