### ISSUE TITLE
Crafttweaker integration documentation

### ISSUE THREAD

**Issue by beanaboston** [MrCrayfish/MrCrayfishFurnitureMod#292]
No where does it say how to do the crafttweaker integration. Please write that somewhere so people can actually use it.

**Comment by BlueAgent** [comment]
Currently to busy to do this.
Would need to making a pull request to [CraftTweaker-Documentation](https://github.com/CraftTweaker/CraftTweaker-Documentation).

For now what you can do is use the `/crafttweaker dumpzs` command, it'll output the zenscript methods to an html file.

**Comment by beanaboston** [comment]
Thanks for the sample script. I'll be able to work backwards and use that to figure out the recipes.

**Comment by BlueAgent** [comment]
Documentation has been added, it's not perfect and could be cleaned up a bit, but should be sufficient.
[Link to Docs](https://crafttweaker.readthedocs.io/en/latest/#Mods/MrCrayfish_s_Furniture_Mod/MrCrayfish_s_Furniture_Mod/)
@MrCrayfish  This issue can be closed now.

**Comment by MrCrayfish** [comment]
Cheers! I appreciate you doing that.
