### ISSUE TITLE
Using the tv cache

### ISSUE THREAD

**Issue by Phixaen** [MrCrayfish/MrCrayfishFurnitureMod#293]
Not sure if this is an issue or not but I downloaded gifs and put them in the tv cache, when I try to access them on the tv they show up as "failed to download".  I tried using just the file name, the full address and just the folder with the file name.  Is there something I'm missing on how to use the cache folder?

**Comment by JacksonPlayz** [comment]
Cache folder isn't meant to be used that way. Instead, put a link to the image you want to put on the TV.

**Comment by Phixaen** [comment]
I've been putting links in to gif's, none have been working for me through links from imgur, giphy or just searching on google.  Was hoping this would work.

**Comment by JacksonPlayz** [comment]
They must be 2mb or lower. Any higher than 2mb won't work. The cache saves images from links so you don't have to download the image every time.

**Comment by Phixaen** [comment]
That explains so much, thank you I'll have to make them a little smaller.
