### ISSUE TITLE
cray my labtop turns black i wait for it to come but it doesnot coem plz ficx this crash report

### ISSUE THREAD

**Issue by juicyboxyoutubee** [MrCrayfish/MrCrayfishFurnitureMod#296]
**Describe the bug**

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version:
- Mod Version:

**Comment by juicyboxyoutubee** [comment]
and then the game crash

**Comment by MrCrayfish** [comment]
Fill in the information...
