### ISSUE TITLE
Some items don't have their own localization strings

### ISSUE THREAD

**Issue by mcBegins2Snow** [MrCrayfish/MrCrayfishFurnitureMod#299]
**Describe the bug**
Some items don't have their own localization strings on JEI:
`item.item_drink.name`
`item.item_crayfish.name`
`item.ceiling_fan_fans.name`

**Crash report**
No crash

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**
![2018-08-25_19 39 45](https://user-images.githubusercontent.com/37864486/44617927-aae16f00-a89e-11e8-8943-0c981c34994f.png)

Please complete the following information:
- Minecraft Version:1.12.2
- Mod Version:5.7.0

**Comment by JacksonPlayz** [comment]
It's because these items are unused. The crayfish face is for advancements and the fans are for the actual fan. The drink is normally renamed and colored once a drink is blended, so you'll never see that item.
