### ISSUE TITLE
Microwave oven ERRORs.

### ISSUE THREAD

**Issue by chezpaul** [MrCrayfish/MrCrayfishFurnitureMod#30]
I get these on my Forge 1517 server log
http://pastebin.com/xXyNqcEj

I also let Pam know
https://github.com/MatrexsVigil/harvestcraft/issues/34

**Comment by chezpaul** [comment]
Went back down to Forge 1492 and I get the same error.
I often use other servers (launching them from my remote mac and whatever mudpack I try, I always get this error.

**Comment by MrCrayfish** [comment]
Looking into issue. Will have new patch out soon
