### ISSUE TITLE
Tv

### ISSUE THREAD

**Issue by TheLostSoul2818** [MrCrayfish/MrCrayfishFurnitureMod#303]
The TV in this mod isn't working. It's telling me to input the channels'and when I do it doesn't work. Any reason why? 

![image](https://user-images.githubusercontent.com/42722897/44633108-47b21400-a954-11e8-8f5e-ccfd459eaa7f.png)

**Comment by MrCrayfish** [comment]
Try another GIF. Sometimes websites don't like what essentially is a non-human downloading files from their domain.
