### ISSUE TITLE
Previous enquiry

### ISSUE THREAD

**Issue by 1stFalloutBoy** [MrCrayfish/MrCrayfishFurnitureMod#305]
Hi,
Sorry to open a new ticket but I'm not that much up on Gut and don't know if once a ticket is closed if you see any amendments so I apologize in advance for being a pain in the @ss.

Regarding my previous inquiry could I possibly fork your instance and change it so that the entries that show "Potentially Dangerous alternative prefix `minecraft` for name `cfmxxxxxx`, expected `cfm`. This could be a intended override, but in most cases indicates a broken mod." are actually using the notation as required myself? It would be a good starter project for me for learning about mod architecture for a starter and give me the ability to have a world file that I wouldn't have to edit in the future.

Any problem with that, if required I could keep the fork private so it's exclusive for my use and not publicly available.

And again - sorry if this would have been dealt with on my now closed previous ticket.

**Comment by JacksonPlayz** [comment]
If it's on GitHub, you can fork the entire repository and change it as long as you abide by the licence.

**Comment by 1stFalloutBoy** [comment]
I've always deemed it polite to ask.
