### ISSUE TITLE
Bad packet handling

### ISSUE THREAD

**Issue by TheAndrey** [MrCrayfish/MrCrayfishFurnitureMod#310]
I found a lot of security issues in the mod's packet handlers that hackers can use to harm the server 👎

1. `MessageTakeWater` - this packet is not used. Can be used to destroy any block. Must be removed.
2. `MessageEnvelope`, `MessagePackage`, `MessagePresent`, `MessagePresentContents` - these packets use the item received from the client. A hacker can put any items in a letter/parcel/gift to get them on the server (e.g. command block). You must use the container to transfer items to the letter inventory. Packet should used to transfer only the name and other attributes.

**Comment by TheAndrey** [comment]
@MrCrayfish Are you going to fix it? This is important.

**Comment by MrCrayfish** [comment]
Fixed in daec054debc43af7668e972c3f8f27ffab3eac64 and f9b667b8365e5b020ed65d9275a337fce097cc34
