### ISSUE TITLE
Missing and Wrong recipes

### ISSUE THREAD

**Issue by Hexroid** [MrCrayfish/MrCrayfishFurnitureMod#311]
Some recipes por the variants of desks and bedside cabinets are missing or wrong:

- Missing recipe for andesite desk, the recipe instead is listed for the diorite desk

- Missing recipes for diorite and andesite bedside cabinets, the recipes are instead listed for the spruce bedside cabinet

Checked the recipes using JEI

**Comment by Zerotiger** [comment]
It would be nice to have recipes for the grill as well. Like recipes on how to make Cooked Kebab, it could just be some (seemingly) simple like this:
![image](https://user-images.githubusercontent.com/4203804/45264480-611b8b80-b43d-11e8-8d14-79b5dac2f094.png)

**Comment by fandomaniac** [comment]
Modern Chair recipe is also missing from JEI.
