### ISSUE TITLE
tree.json has "blocks/blocks/leaves_oak" in it's particle field

### ISSUE THREAD

**Issue by EnderTurret** [MrCrayfish/MrCrayfishFurnitureMod#314]
**Describe the bug**
In the tree.json inside models/block the particle field has "blocks/blocks/leaves_oak" rather than "blocks/leaves_oak".

**Crash report**
As this doesn't crash the game, there is no crash report.

**To Reproduce**
I believe simply launching the game with the mod will reproduce it.

**Screenshots**
I don't have any screenshots of it at the moment and I'm not sure they're needed.

- Minecraft Version: 1.12.2
- Mod Version: 5.10.0

**Comment by realTIMematrix** [comment]
Error Message in Minecraft Game Output:

Minecraft Version: 1.12.2
Forge: 14.23.5.2768
Furniture: 5.14.0

13:34:37 | FML.TEXTURE_ERRORS | main | error | +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
-- | -- | -- | -- | --
13:34:37 | FML.TEXTURE_ERRORS | main | error | The following texture errors were found.
13:34:37 | FML.TEXTURE_ERRORS | main | error | ==================================================
13:34:37 | FML.TEXTURE_ERRORS | main | error | DOMAIN minecraft
13:34:37 | FML.TEXTURE_ERRORS | main | error | --------------------------------------------------
13:34:37 | FML.TEXTURE_ERRORS | main | error | domain minecraft is missing 1 texture
13:34:37 | FML.TEXTURE_ERRORS | main | error | domain minecraft has 1 location:
13:34:37 | FML.TEXTURE_ERRORS | main | error | unknown resourcepack type net.minecraft.client.resources.DefaultResourcePack : Default
13:34:37 | FML.TEXTURE_ERRORS | main | error | -------------------------
13:34:37 | FML.TEXTURE_ERRORS | main | error | The missing resources for domain minecraft are:
13:34:37 | FML.TEXTURE_ERRORS | main | error | textures/blocks/blocks/leaves_oak.png
13:34:37 | FML.TEXTURE_ERRORS | main | error | -------------------------
13:34:37 | FML.TEXTURE_ERRORS | main | error | No other errors exist for domain minecraft
13:34:37 | FML.TEXTURE_ERRORS | main | error | ==================================================
13:34:37 | FML.TEXTURE_ERRORS | main | error | +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

`
