### ISSUE TITLE
Server crash (single player server)

### ISSUE THREAD

**Issue by IceCreeper74** [MrCrayfish/MrCrayfishFurnitureMod#320]
---
name: Crash report
about: integrated Server Crash

---

**Describe the bug**
Usage of the TV, trash bin, Photo frame, 

**Crash report**
https://pastebin.com/cL4Aetu9

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place down item like the TV, 
2. Open the GUI by right clicking the TV
3. Exit the GUI

**Screenshots**
![screenshot_2](https://user-images.githubusercontent.com/35157604/45929996-3c3c1380-bf27-11e8-8f80-1f759597588a.png)

Please complete the following information:
- Minecraft Version: 1.12.2 (Forge 1.12.2-14.23.4.2075)
- Mod Version: 5.11.0

**Additional Info**
I have tried using this mod by itself and it still does the same thing.

**Comment by MrCrayfish** [comment]
Hmm strange because it's saying the constructor from an networking library (out of my control) is missing. Have you tried updating Forge to recommended or even latest? Let me know if that will fix it.

**Comment by MrCrayfish** [comment]
You are using a highly outdated Forge version. Please update

**Comment by IceCreeper74** [comment]
Recently i got a new laptop and everything seems fine. thanks for response anyways.
