### ISSUE TITLE
Minebay Doesn't Support MetaData for Payment Items

### ISSUE THREAD

**Issue by dragonshardz** [MrCrayfish/MrCrayfishFurnitureMod#321]
There doesn't appear to be a way to specify metadata (eg: minecraft:wool:16) for payment items in Minebay using the config method of RecipeAPI. Specifying the metadata value as part of _payment-item_ returns an error saying the item doesn't exist, and specifying the metadata value on its own in _payment-item-metadata_ simply results in the non-metadata version of the item being requested.

**Comment by BlueAgent** [comment]
This is because Minebay doesn't check on metadata for the payment item.
It could possibly be changed to use the same system as the other one-to-one recipes like the oven or freezer.
Currently it's an implementation and API limitation.

**Comment by dragonshardz** [comment]
It would be nice if it did check metadata.

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
