### ISSUE TITLE
Bucket Duplication Bug when crafting Soapy Water and also when placing it in the Washing Machine or Dishwasher

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishFurnitureMod#326]
**Describe the bug**
When crafting Soapy Water using Soap and a Water Bucket, you get an empty Bucket back. When placing the Soapy Water into a Washing Machine or Dishwasher, you get a second empty Bucket back and you get a third Bucket back when the soap empties into the machine in the GUI.

**Crash report**
N/A

**To Reproduce**
Just repeat the steps written above in the bug description.

Please complete the following information:
- Minecraft Version: Forge-1.12.2-14.23.4.2759
- Mod Version: Furniture Mod 5.13.0

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
