### ISSUE TITLE
Modern Chair crafting is broken

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishFurnitureMod#328]
**Describe the bug**
Modern Chair crafting is broken. Please see JEI screen capture below.

**Screenshots**
![image 2](https://user-images.githubusercontent.com/37810246/46897715-5d22c500-ce52-11e8-87a3-8179b4fd9798.jpg)

Please complete the following information:
- Minecraft Version: Forge Forge 14.23.5.2769
- Mod Version: Furniture 5.14.0-1.12.2

**Comment by QuantumStatement** [comment]
This should be fixed in #318
