### ISSUE TITLE
Crash with OptiFine_1.12.2_HD_U_E2

### ISSUE THREAD

**Issue by SeanChengN** [MrCrayfish/MrCrayfishFurnitureMod#330]
**Describe the bug**
Crash when loading world with [OptiFine_1.12.2_HD_U_E2](https://optifine.net/downloads).
OptiFine_1.12.2_HD_U_E1 is Compatible.

**Crash report**
https://pastebin.com/1dmH5hF8

**To Reproduce**
1. Use [SEUS Renewed 1.0.0 Shader](http://www.sonicether.com/download/seus-renewed-v1-0-0/).
2. Just loading world.

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 5.14.0
- Obfuscate: 0.2.6
- Forge: 14.23.5.2768

**Comment by Ycarx** [comment]
Thank you for spotting that crash !

**Comment by SeanChengN** [comment]
Fix in OptiFine_1.12.2_HD_U_E3
