### ISSUE TITLE
Minecraft crashes when I join my server

### ISSUE THREAD

**Issue by JagleW** [MrCrayfish/MrCrayfishFurnitureMod#342]
**Describe the bug**
When I join my server, minecraft crashes instantly.

**Crash report**
https://pastebin.com/15jbw1JC

**To Reproduce**
Help me to fix that.

**Screenshots**
A film in the attach. (must be in zip, because github didnt accept mp4

[film.zip](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/2545032/film.zip)

Please complete the following information:
- Minecraft Version: 1.7.10
- Mod Version: MrCrayfishFurnitureModv3.4.7(1.7.10)

**Comment by JacksonPlayz** [comment]
You're playing on an extremely old version which is no longer supported. That's your problem.

**Comment by JagleW** [comment]
But mod can broke itself? Some months ago it works good

**Comment by MrCrayfish** [comment]
Well retrace your steps. Did you change anything recently? This is not a furniture mod problem.

**Comment by JagleW** [comment]
But peoples from forge forum says, thats furniture mod problem... Can you help me?

**Comment by MrCrayfish** [comment]
Who said that? Obviously the person who did doesn't know how to read crash logs. It's an error with Galactic Craft @ micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced

**Comment by MrCrayfish** [comment]
Anyway, even if it was an issue with my Furniture Mod, I no longer update 1.7.10 because it's a dead MC version. You should play on newer version of the game.

**Comment by JagleW** [comment]
So I will try to remove Galactic Craft, thank you so much.
