### ISSUE TITLE
Strange model for a Modern Chair corner

### ISSUE THREAD

**Issue by QuantumStatement** [MrCrayfish/MrCrayfishFurnitureMod#343]
**Describe the bug**
Modern Chair corner has (maybe) a wrong model

**Crash report**
N/A

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Create a corner from Modern Chairs
2. See error

**Screenshots**
![2018-10-21_16 47 06](https://user-images.githubusercontent.com/35406698/48223915-5f246900-e3a9-11e8-9f7f-d02d5bdd09d1.png)
![2018-10-21_16 47 15](https://user-images.githubusercontent.com/35406698/48223916-5fbcff80-e3a9-11e8-80dc-2108dc581eda.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 5.15.0

**Comment by MrCrayfish** [comment]
Woops, Modern Couch isn't actually suppose to have a corner version. Will fix soon

**Comment by MrCrayfish** [comment]
Fixed in de6577c7d78cd82946a26b8c5391032d994725b2
