### ISSUE TITLE
Modern light doesnt turn on

### ISSUE THREAD

**Issue by yeet55yeet** [MrCrayfish/MrCrayfishFurnitureMod#346]
Everytime i try to right click, it just places another one. I tried using a light switch but that didnt work either.

**Comment by fandomaniac** [comment]
It seems you can only turn them on with the light switch.

**Comment by fandomaniac** [comment]
I just tested on SMP and single-player. It does turn on with a Modern Light Switch. Make sure you right-click the Modern Light with the Modern Light switch before placing the Switch on a block.

Note: You currently can't craft a Modern Light in survival until the crafting recipe is fixed.

**Comment by MrCrayfish** [comment]
It can only be powered with a light switch
