### ISSUE TITLE
Player can sign an empty package, envelope and present

### ISSUE THREAD

**Issue by QuantumStatement** [MrCrayfish/MrCrayfishFurnitureMod#352]
**Describe the bug**
Player can sign a package, envelope, present and crates without any items in them

**Crash report**
N/A

**To Reproduce**
1. Open Envelope/Package/Present/Crate GUI
2. Click on "Sign"/"Wrap" button
3. Don't see chat error message

https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/0b27d76bcf531ea11e001267e67922570dcefa8e/src/main/resources/assets/cfm/lang/en_us.lang#L522
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/0b27d76bcf531ea11e001267e67922570dcefa8e/src/main/resources/assets/cfm/lang/en_us.lang#L526
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/0b27d76bcf531ea11e001267e67922570dcefa8e/src/main/resources/assets/cfm/lang/en_us.lang#L529
**Screenshots**
N/A

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 5.17.0, 6.2.0

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
