### ISSUE TITLE
computer Right-Click crash

### ISSUE THREAD

**Issue by Ktanaqui** [MrCrayfish/MrCrayfishFurnitureMod#353]
**Describe the bug**
Right-clicking placed computer results in total crash of game. Note that we are playing in a LAN world. Just two players - my SO and myself. SO placed the item down.

**Crash report**
https://pastebin.com/WmNBSAFX

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place Computer in world
2. Right-click on computer

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 5.15.0

**Comment by SalmonSays** [comment]
I came here to see if this was already reported and sure enough here it is- I've noticed this exact problem in a server environment.

**Comment by Ktanaqui** [comment]
It is worth noting that my SO (who is the one who placed the computer) does not have an issue with right-clicking the computer. It works as expected for him. I need to try placing a second one and see if it's unique to the player who placed it, or if it's because the LAN server is running off of his computer. (So I'm connecting to him.)

**Comment by gallowglass** [comment]
I am seeing this too in version cfm-6.2.0-mc1.12.2.jar

**Comment by chyper111** [comment]
me to

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
