### ISSUE TITLE
[Critical] Dupe anything bug

### ISSUE THREAD

**Issue by 0xEviqnn** [MrCrayfish/MrCrayfishFurnitureMod#354]
This issue was reported to me by QualityFps#7441 and forwarded by me (Eviqnn#5738)

This bug utilises the “presents” in CFM. Simply: get 2 or more presents. Open that stack of 2 or more. Place your item in and then press esc and separate them out. All presents from that stack will have that item.

To better describe the issue you can see a video here:
https://cdn.discordapp.com/attachments/503718131710296074/514238977973420047/2018-11-19_17-40-39.mp4

and here
https://cdn.discordapp.com/attachments/503718131710296074/514233805197017139/2018-11-19_17-17-55.mp4

Both the client and the server is running the latest versions of CFM. Running on top of 1.12.2 Forge.

**Comment by 0xEviqnn** [comment]
Update: Tested this on a SpongeForge Server and a Normal Server for 1.12.2- still happens even when in vanilla.

**Comment by fandomaniac** [comment]
One way to fix this would be to modify these items to not be stackable. This up to MrCrayfish.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/13faca1b86611a51b9b9fa65ae8236461e5fdc0a
