### ISSUE TITLE
tables replace nbt data of items

### ISSUE THREAD

**Issue by MasterSloth1** [MrCrayfish/MrCrayfishFurnitureMod#355]
**Describe the bug**
the spruce coffee table replaces nbt data of items

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. place down a spruce coffee table
2. place item on table eg item dislocator from draconic evolution
3. pick item up off table

**Screenshots**
![2018-11-26_01 33 29](https://user-images.githubusercontent.com/34207969/48979158-7ee2bd80-f11b-11e8-897a-39318f6ef2fc.png)
![2018-11-26_01 33 32](https://user-images.githubusercontent.com/34207969/48979160-886c2580-f11b-11e8-8f39-8f5ec67d5e1e.png)
![2018-11-26_01 33 51](https://user-images.githubusercontent.com/34207969/48979162-8bffac80-f11b-11e8-97f2-c2d442fb617b.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: furniture-5.17.0-1.12.2

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/b741bc44037c6545656a35cd4be5c9d6f6f2852f
