### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by ughhmeghan** [MrCrayfish/MrCrayfishFurnitureMod#356]
whenever i load into minecraft, ill click play to launch and it'll start loading the mods but always crashes before to finishes loading. i deleted every mod except for the furniture mod and it's still crashing. i dont know anything about scripting so the crash report is all a foreign language to me. please help, its been several months i just want to use your mod :(

**Crash report**
https://pastebin.com/ay44HEed

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 1.12.2

**Comment by fandomaniac** [comment]
You need to allocate more memory for Minecraft. I recommend allocating 4 GB or higher. I also recommend updated your Forge version to to 1.12.2-14.23.5.2768.
