### ISSUE TITLE
Fire Alarm Redstone Not Updating

### ISSUE THREAD

**Issue by LanceNickel** [MrCrayfish/MrCrayfishFurnitureMod#360]
When a fire alarm goes off, the redstone placed above it does not update, it stays non-powered. When I remove and then place a new piece of redstone it will then be powered. When I reset the fire alarm, the redstone stays powered until I remove it and put a new piece in.

It should be updating automatically so my redstone can work when there is a fire.

I am on MC 1.12.2, and here are the mods I have installed just in case you want them:

SecurityCraft, Advanced Solar Panels, Crayfish Devices, Crayfish Furniture, Colored Lights, IndustrialCraft, Just Enough Items, Malisis Blocks, Malisis Core, Malisis Doors, Malisis Switches, Multi Hotbar, Multi Hotbar Core, OptiFine, Restone Paste, Thut Core, Thut Tech, Torojima Build Helper, Tree Chopper

**Comment by PurifyHD** [comment]
I should also add that I have tested this on MC 1.12.2 without any other mods but CFM installed.

I am still having the redtone issue with the fire alarm. Thank you!

**Comment by IsDerpy** [comment]
For clarification, the redstone needs a title update before it produces a redstone output. That seems to be the issue that is occurring,

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
