### ISSUE TITLE
Stone Path Does Not Test for Non-Transparent Block Below It When Placed

### ISSUE THREAD

**Issue by IsDerpy** [MrCrayfish/MrCrayfishFurnitureMod#363]
**Describe the bug**
When first placed the Stone Path does not test if the block below it is Non-Transparent. It only does test for it when it has been updated by having a neighboring tile change. By Non-Transparent I mean blocks such as pistons, glass, air, leaves, etc.

**Crash report**
Not applicable.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place a Stone Path on a Non-Transparent Block
2. Place a block next to the Stone Path

**Screenshots**
Before
![2018-12-09_16 51 47](https://user-images.githubusercontent.com/45742276/49703417-e1839100-fbd2-11e8-8766-24285c509b9d.png)

After
![2018-12-09_16 52 02](https://user-images.githubusercontent.com/45742276/49703420-e9433580-fbd2-11e8-9268-1c206049bff0.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.1.0

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/96729801ebc10d21c5982bb10741b8d068c0d11c
