### ISSUE TITLE
Wrapped Presents Don't Keep Original Color

### ISSUE THREAD

**Issue by IsDerpy** [MrCrayfish/MrCrayfishFurnitureMod#364]
**Describe the bug**
No matter what color present you have after wrapping it the present will become a White Present

**Crash report**
N/A

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Grab any present (Except white)
2. Wrap it with any item.

**Screenshots**
N/A

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.1.0

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/82e9c5a6a3f3856d624450005efe7d5c25f4d0f1
