### ISSUE TITLE
Game Crashes on World Startup

### ISSUE THREAD

**Issue by TheMaskofOsiris** [MrCrayfish/MrCrayfishFurnitureMod#365]
**Describe the bug**
When I start my world the game crashes before finishing loading.

**Crash report**
https://pastebin.com/hgbLVrhU

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.0

**Comment by fandomaniac** [comment]
Try allocating more memory for Minecraft. I recommend allocating 4 GB or higher.
