### ISSUE TITLE
Curtains do not retain their colour

### ISSUE THREAD

**Issue by GSValore** [MrCrayfish/MrCrayfishFurnitureMod#366]
**Describe the bug**
Coloured curtains revert to white when placed and remain white when broken by the user. EDIT: This applies to a server -- omitted initially and fixed thanks to RyanCR03's comment.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Craft coloured curtains, in our case we were using purple.
2. Place the curtains
3. The curtains become white instead of retaining their crafted colour.
4. Break the curtains, they remain white.

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.1.0

**Comment by RyanCR03** [comment]
for me this only works on servers

**Comment by GSValore** [comment]
Updated to reflect that the bug report refers to servers in this context.

**Comment by n217062** [comment]
Something similar also happens in single player. When I place a colored curtain and then save and exit, it will always revert back to a white curtain when I load the game back up.

**Comment by soulgem** [comment]
This still happens on the 6.2.1 version of cfm.
Any idea what could be causing this?

**Comment by Pairaka** [comment]
This is happening to me in 6.2.1 in the FTB Builder's Paradise (single player) pack. I placed (oddly enough) purple curtains, then logged out. When I logged back in, they were white. Clicking on them to change their state from open to closed (and vice versa), they reverted back to purple. Breaking them while white, they did not revert and instead were white in my inventory.

**Comment by AechtRob** [comment]
Pleeeease fix this! You craft coloured curtains but when you place them, they place as white and revert to white!

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
