### ISSUE TITLE
TVs on SMP not accepting input in Survival

### ISSUE THREAD

**Issue by GSValore** [MrCrayfish/MrCrayfishFurnitureMod#370]
**Describe the bug**
When in survival mode and interacting with either type of TV on a server, I can input or change buttons but pressing Escape or clicking on the X causes no change to the TV.  This is verifiable by opening the interface again and it's all set to the default values (empty for channels, for example).

**Crash report**
Not Applicable

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Be in survival mode on a multiplayer server.
2. Right click a TV and try to change it settings.
3. Escape or press "X" to exit the interface.
4. Reopen the interface, all changes were not committed.

**Screenshots**
Not applicable (as it'd show the same screen)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.1.0
- Forge Version: 2795

**Comment by Darkfiend009** [comment]
I'm having the same exact issue. Here is my current information:

Minecraft Version: 1.12.2
Mod Version: 6.1.1
Forge Version: 2796

**Comment by kreezxil** [comment]
confirmed also with forge 14.23.5.2838 and Furniture 6.2.1

being in creative the tv will accept the settings.

please fix this.
