### ISSUE TITLE
Crash with Futurepack

### ISSUE THREAD

**Issue by danikk14g** [MrCrayfish/MrCrayfishFurnitureMod#371]
**Describe the bug**
I get a crash only when i run MC with both MrCrayFish's Furniture Mod and Futurepack, without the last, i never get this type of error.

**Crash report**
https://pastebin.com/hn2cgX0C

**To Reproduce**
1. Run MC with both  

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: furniture-6.1.1-1.12.2
 Futurepack: https://minecraft.curseforge.com/projects/futurepack/files/2638870

This same error also happened to me 2-3 months ago with different versions of both mods.
I am now using latest forge version, but like i said this crash is not new, now tried with forge 1.12.2-14.23.5.2796 and 1.12.2-14.23.5.2772

Thanks.

#315

**Comment by danikk14g** [comment]
i have tried using only a few mods and the crash does not happen anymore, sorry for making this issue.

**Comment by Yzelast** [comment]
Having the same issue, removing crafttweaker seens to fix the problem...

**Comment by jelaw21** [comment]
I can confirm that a crash happens with Futurepack, Crayfish and Craftweaker, but works fine when Crafttweaker is removed.
