### ISSUE TITLE
Gray and Green Door Mat Recipes are broken

### ISSUE THREAD

**Issue by fandomaniac** [MrCrayfish/MrCrayfishFurnitureMod#372]
You can't craft a Grey Door Mat.
Six Grey Rugs craft a Green Door Mat (see screen capture below).
Six Green Rugs doesn't craft anything.

Forge Version: 1.12.2-14.23.5.2796 SMP
Mod Version: Furniture Mod 6.2.0

![carpet](https://user-images.githubusercontent.com/37810246/50370710-ab062880-0579-11e9-8041-a7a5f9451ac7.jpg)

**Comment by Graywaren** [comment]
I confirm that the gray and green doormat's share a recipe; six Gray carpets. The green carpet's recipe is incorrect. 

Before this is fixed, if you want, you can craft both by installing the No More Recipe Conflicts mod and clicking the small arrow that scrolls between available recipes.
