### ISSUE TITLE
Tub will not show fullness

### ISSUE THREAD

**Issue by darthvader45** [MrCrayfish/MrCrayfishFurnitureMod#375]
**Describe the bug**
The bath tub simply will not show how full it is if shift-clicked.  I have to right-click it with a bucket to fill it.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place an unlimited source 2 blocks under where the bathtub head will be.
2. Place blocks to cover up the source and place tub.
3. Shift + right-click the tub.
4. Tub does not visibly show how full it is.

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.2.0

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
