### ISSUE TITLE
Cannot craft blue modern couch

### ISSUE THREAD

**Issue by AliciaJewel** [MrCrayfish/MrCrayfishFurnitureMod#376]
**Describe the bug**
The blue modern couch cannot be crafted. In JEI, its crafting recipe simply doesn't exist.

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.2.0

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
