### ISSUE TITLE
Crash when viewing Mirror, only on client. Server runs fine

### ISSUE THREAD

**Issue by LuftRaptor** [MrCrayfish/MrCrayfishFurnitureMod#379]
**Describe the bug**
Placing the Magic mirror causes an immediate crash to the client, however the server operates normally and does not crash. client will continue to crash on re-join.
**Crash report**
ps://pastebin.com/tBtSUbQh
**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place Mirror
2. Look at Mirror

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: cfm-6.2.0-mc1.12.2

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
