### ISSUE TITLE
Dying and having mirrors causes the client to crash

### ISSUE THREAD

**Issue by ParlocameonTheDev** [MrCrayfish/MrCrayfishFurnitureMod#380]
**Describe the bug**
Whenever a player dies on the server(which is a lot), the player that died immediately has their client crashed. The only mod listed in the exceptions for the crash is CFM, so I assume that this is the best place to post the issue. Note, the crash seems related to a mirror, and I have a single mirror inside my house, but when I die I'm no where near the mirror. NOTE: Possibly related to #379, with the main difference being that on #379 viewing the mirror crashes it, while on this just dying and having a mirror crashes the client. EDIT: I broke the mirror, and no longer crash after dying, so I can confirm it has something to do with the mirror.

**Crash report**
https://pastebin.com/qHA34avv

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Go on the server
2. Die  
3. Click Respawn
4. Client crashes

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: cfm-6.20

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
