### ISSUE TITLE
 tv automatically deletes the url

### ISSUE THREAD

**Issue by andrunetito** [MrCrayfish/MrCrayfishFurnitureMod#383]
version 1.12.2 , 
the modern TV disappears when you break it with your hand, (it breaks fast) and when you paste the link after leaving the TV interface, the link disappears

**Comment by Jon1128** [comment]
The TV might have to be off first but links do work if you add them while in creative.

**Comment by Kaegos** [comment]
I'm having the same issue. Any interactions with the TV are not saved, unless you're in creative mode. Which is fine for admin stuff, but not helpful for others in a SMP environment :(

**Comment by Leonature26** [comment]
this happens to me too. Is there no fix to this? I can't find a config file for this mod.

**Comment by DWX12** [comment]
The config for this mod is named "cfm.cfg", which really should be renamed to something more straightforward like CrayfishFurniture or something similar.

**Comment by SanjivanM** [comment]
cfm = CrayfishFurnitureMod, it's short and sweet, imo
Also, the TV breaking and not breaking is fixed in 6.3.0

**Comment by StaticHex** [comment]
So, I might have found an additional bit of info for this issue. I'm running this mod on a 1.12.2 server and I've noticed that I cannot add to the TV unless in creative mode. If I try to add in survival I cannot edit any of the TV's settings but if I switch to creative everything works fine. Hopefully this helps.

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
