### ISSUE TITLE
Kitchen Items Change Color with Other Mod Errors

### ISSUE THREAD

**Issue by Graywaren** [MrCrayfish/MrCrayfishFurnitureMod#384]
**Describe the bug**
I am having some, but not all of, my placed green kitchen cabinets and counter drawers change to white ones. This appears to be due to a mod error interaction between Landlust Furniture Mod and Chisel. Chisel is having an error with Landlust's Stove and burn times I think. This happens when any fuel is left in the LL stove on logout and then logging in. It will throw an error. The report (link below) doesn't mention Mr. Crayfish mod at all though. (It also happens to delete the image from Online Pic Frame as well). Removing the fuel from the stove and logging out and back in returns the cabinets to their proper color. Without that you have to break them, which gives the correct color to inventory, and then place them back into the world.

Not sure if there's anything you can do about this since it doesn't seem to quite be an error with your mod, but if you have any information on why it's happening that'd be great. LL appears to be a dead mod, but I adore the stove furnace! So perhaps... suggestion: add a cute stove fully functional furnace to your mod <3

**Crash report**
https://paste.dimdev.org/cafibuyewe.mccrash

(this also contains full mod list, though it will show an older version of Mr. Crayfish. I updated Mr. Crayfish after getting this link and confirmed it still happens with the latest version)

Link to LL mod:
https://minecraft.curseforge.com/projects/landlust-furniture

Link to Chisel mod:
https://minecraft.curseforge.com/projects/chisel

**To Reproduce**
1. Place burnable fuel into Landlust stove
2. Log out of game (does not require quitting and re-launching)
3. Log back into game
4. Mr. Crayfish items are wrong color
5. Remove fuel from LL stove
6. Log out
7. Log back in
8. Mr. Crayfish items return to proper color

- Minecraft Version:
1.12.2

- Mod Version:
6.2.0

**Comment by MrCrayfish** [comment]
I'll look into the Kitchen Counter issue but not a lot I can do about LL. You will have to ping the author of that mod in hopes they update it.

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
