### ISSUE TITLE
Photo Frame Doesn't Work

### ISSUE THREAD

**Issue by Graywaren** [MrCrayfish/MrCrayfishFurnitureMod#385]
**Describe the bug**
I assume this is related to the other open bug about the TV, but the Photo Frame will not retain a URL and display a photo. When you hit esc or the X to close the gui the frame remains blank and the URL is gone once you open the gui again.

**Crash report**
n/a

**To Reproduce**
1. Create and hang photo frame
2. Right click on frame to open gui
3. Input url. Stretch border on or off makes no difference
4. Hit esc or X 
5. Photo frame remains blank and URL is deleted

- Minecraft Version:
1.12.2

- Mod Version:
6.0.2

**Comment by sklll** [comment]
Same behavior on 6.2.0-1.12.2
but only for regular players, for OP-s it works ok

**Comment by MrCrayfish** [comment]
Closing since I won't be maintaining 1.12.2 anymore.
