### ISSUE TITLE
Texture bug with lights

### ISSUE THREAD

**Issue by MJRamon** [MrCrayfish/MrCrayfishFurnitureMod#386]
**Describe the bug**
When turning lights on, they have weird texture around.

**Crash report**
None

**To Reproduce**
If it's about resource pack, how do I fix this?

**Screenshot**
![2019-01-11_09 41 00](https://user-images.githubusercontent.com/2642227/51019905-67ee1280-1585-11e9-8ae8-5490726caf3e.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: Furniture Mod 6.2.0

**Comment by MrCrayfish** [comment]
It's a resource pack issue. All my models grab the texture from the current resource pack. It uses the yellow glass block.
