### ISSUE TITLE
MrCrayfishFurnitureMod is modifying the world off the main thread

### ISSUE THREAD

**Issue by Aaron1011** [MrCrayfish/MrCrayfishFurnitureMod#394]
In [MessageMineBayBuy](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/cde9227ed22af339ffa65359d30365d8ee6476b4/src/main/java/com/mrcrayfish/furniture/network/message/MessageMineBayBuy.java#L71), `World#spawnEntity` is called to spawn in a new item. However, the `onMessage` callback is invoked from a Netty handler thread - not the main server thread.

While this may appear to work, it can easily lead to corrupted data or other difficult-to-reproduce issues. The Minecraft server expects all modifications to the game to be done from the main thread, and has essentially no thread-safe methods.

To fix this, the body of `onMessage` should be wrapped in a scheduled task (using `MinecraftServer#addScheduledTask`

**Comment by MrCrayfish** [comment]
I hate my old code 😒 I will get a fix for this soon. For the 1.13 update, I plan to write the mod from scratch.

**Comment by 0xEviqnn** [comment]
@MrCrayfish will you still update the mod for 1.12.2?

**Comment by MrCrayfish** [comment]
"I will get a fix for this soon"

**Comment by 0xEviqnn** [comment]
> I will get a fix for this soon For the 1.13 update,

**Comment by DoomRater** [comment]
I can just about guarantee this is related to Issue #208.
