### ISSUE TITLE
[Suggestion] Additional features for the digital clock..

### ISSUE THREAD

**Issue by Karmacopper** [MrCrayfish/MrCrayfishFurnitureMod#395]
Some additional features I would love to see in the digital clock:

Optional hourly chime
Set an alarm

with optional redstone pulse (length option).

I am aware this probably isn't the place for suggestions, however I couldn't find anywhere else to post.

**Comment by MrCrayfish** [comment]
I will look into this. Definitely maybe modes to pulse every minute, hour, or day. Maybe some special chimes for when it becomes day or night.

**Comment by Graywaren** [comment]
Would also love the ability to place them on a wall

**Comment by SanjivanM** [comment]
Try putting it in an Item Frame, like w/ a vanilla clock?
