### ISSUE TITLE
6.0 to present versions crash w/ crash log

### ISSUE THREAD

**Issue by Mizvis** [MrCrayfish/MrCrayfishFurnitureMod#396]
I did a handful of testing with this mod and the FTB Direwolf20 pack. MCF 6.0 to 6.2 crashes with all somewhat new versions of forge. MCF 5.17 and previous seem to work just fine with new versions of forge. Also might not be forge thats the issue, might be something that all 6.0 and forward versions just don't cooperate with. (attached crash file)
[crash-2019-03-11_19.39.08-client.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/2954604/crash-2019-03-11_19.39.08-client.txt)

**Comment by MrCrayfish** [comment]
You've run out of block ids, not a bug.

**Comment by Mizvis** [comment]
oh...thats unfortunate. theres no fix for that is there..
