### ISSUE TITLE
Curtains are Not Middle-Clickable (selectable) in Creative Mode

### ISSUE THREAD

**Issue by BeksOmega** [MrCrayfish/MrCrayfishFurnitureMod#398]
**Describe the bug**
If you middle-click a block in creativemode, you expect that block to be added to your hotbar. This does not occure with curtains.

**Crash report**
N/A

**To Reproduce**
1. Go into Creative Mode.
2. Place a curtain.
3. Remove the curtain item from your inventory.
4. Middle click the curtain (to attempt to add it to your hotbar).
5. Observe that the curtain was not added to your hotbar.

**Screenshots**
N/A

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.2.0

**Comment by soulgem** [comment]
I can confirm that this is also the case in mod version 6.2.1
