### ISSUE TITLE
SecretRoomsMod One Way Glass + Furniture Conflict

### ISSUE THREAD

**Issue by aprilfooldude** [MrCrayfish/MrCrayfishFurnitureMod#403]
**Describe the bug**
I was playing on a personal server that I've been hosting for my friends and I, when we came across an issue between SecretRoomsMod and Furniture Mod's couch. Looking at the one way glass after I placed it on a couch crashed our games, and didn't crash us when we weren't (thankfully we got rid of it, so we didn't have to avoid that area entirely) I have already gone to the SRM repo and reported it, (https://github.com/AbrarSyed/SecretRoomsMod-forge/issues/272) and he came back telling me I should ask you next, so here I am.

**Crash report**
https://pastebin.com/2fKtHqKz
**To Reproduce**
1. Grab any colored Couch
2. Take a One Way Glass block from SRM mod
3. Place One Way Block On Couch
4. _Enjoy crashing the game_

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.2.0

**Comment by MishaPlayer** [comment]
I mean... why would you place it on a couch?

**Comment by aprilfooldude** [comment]
I was extremely curious and was trying to hide something

**Comment by MrCrayfish** [comment]
This is not a conflict but just a bug in general. WIll be fixed soon
