### ISSUE TITLE
[Help/Suggestion] - To change the mirror size (1 bloc -> 2/more ?

### ISSUE THREAD

**Issue by Finelarme9** [MrCrayfish/MrCrayfishFurnitureMod#407]
Hello
Thank you for your stuffs. I would like to know if it is possible to change the **mirror size** of the mod please . Currently the size is 1 bloc but can we change it to 2 blocs/more please ? I would really appreciate some help/all advices.
Thank you in advance.
Ben

**Comment by MrCrayfish** [comment]
It's staying as one block unfortunately. If it was easy, I would have done it already
