### ISSUE TITLE
Left Clicking Modern TV in survival breaks it instantly and does not return item

### ISSUE THREAD

**Issue by katubug** [MrCrayfish/MrCrayfishFurnitureMod#409]
**Describe the bug**
A player reported to me, and I can replicate, that the Modern TV is instantly deleted when left clicking with empty hand in survival mode. It's identical to breaking a block in creative, except it happens in survival.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Craft Modern TV and place it in world.
2. Left click on it.

Please complete the following information:
- Minecraft Version: 1.12.2, using forge-1.12.2-14.23.5.2825-universal
- Mod Version: furniture-6.2.1-1.12.2

**Comment by kreezxil** [comment]
I confirm this.
