### ISSUE TITLE
mirror seems to make the vignette very small

### ISSUE THREAD

**Issue by pabthelamb** [MrCrayfish/MrCrayfishFurnitureMod#410]
when the mirror is in the view the vignette goes very small.

**To Reproduce**
Not sure?

**Screenshots**
https://youtu.be/dHzq2XXw56U?t=314 (my friends video)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: ?(will ask)

**Comment by MrCrayfish** [comment]
This is most likely a conflict with another mod. I have plans to redo mirrors completely to be more efficently. I will keep this issue open until I do that.
