### ISSUE TITLE
Absurd load times in Forge Server

### ISSUE THREAD

**Issue by delta9690** [MrCrayfish/MrCrayfishFurnitureMod#412]
On an Aternos Server, running Forge 1.12.2 (14.23.5.2768), load times for this mod are exceeding 300 seconds, which causes the server to exceed the load time limits given by Aternos, preventing it from starting.

![image](https://user-images.githubusercontent.com/51144864/58525588-8dbd3200-8189-11e9-84d6-7502ebd2d370.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.0

**Comment by MrCrayfish** [comment]
5 minutes to load, yikes. That definitely doesn't sound normal. This is the first time anyone has experienced this, so it sounds like an issue on your side. What is the specs of your server? Have you allocated enough ram? My furniture mod adds over 250 blocks. Without enough ram, it's going to freeze until the garbage collector frees memory.

Heres the break down for Pre Initialization in my mod:
- Register config events
- Initialize Blocks, Item, Sounds, Crafting
- Initialize Packet Handler
- Initialize config
- Register advancement triggers

Then depending on the side
CLIENT:
- Register keybinds
- Register creative gui category tab events
- Register sprites

SERVER:
- Register crafting fix
- Register sync event for config
- Register missing mappings events

There are no URL requests in that (something that other mods do sometimes and significantly slow down load times). I stick to my original statement and you should check your server configurations.

**Comment by JacksonPlayz** [comment]
RAM on Aternos depends on player slots. Every server starts with 500mb of ram and gains 100mb more for every player slot added.

**Comment by MrCrayfish** [comment]
Ahh, well that's a clear indicator of the slow load. So to solve your problem, you need better server. 500mb is simply not enough for a modded server.
