### ISSUE TITLE
breaking blinds returns oak blinds

### ISSUE THREAD

**Issue by SanjivanM** [MrCrayfish/MrCrayfishFurnitureMod#419]
When breaking blinds of other wood, they drop oak blinds.  Possibly metadata stuff when returning the item dropped?

**Comment by xJon** [comment]
Can confirm, on all blinds in 1.12.2.
https://github.com/xJon/The-1.12.2-Pack/issues/199

**Comment by ThoBekMic** [comment]
Can confirm the bug is still there in 6.3 version for 1.12.2.

**Comment by SanjivanM** [comment]
The "glitch" starts here, and goes for the next 10 lines of code
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/2a6c88ed63a0255ce9f18ca76b960a2fcbd436bd/src/main/java/com/mrcrayfish/furniture/blocks/BlockBlinds.java#L86

Basically, getItemDropped and getPickBlock don't take the variant into account.  I'd make a PR, but I don't have time to give it a detailed look

**Comment by Ruukas97** [comment]
I came to report this as well.

**Comment by SanjivanM** [comment]
~So I downloaded the 1.12.2 version and loaded it onto my workspace, did the usual gradle setup things, but I see no eclipse folder (after doing gradlew setup and eclipse and all that), can anyone confirm, or am I just missing something?~

Just had to give the commands some "cooldown" before the next one, I guess...

**Comment by SanjivanM** [comment]
Alright, someone PM @MrCrayfish to accept this PR (as well as others, I have the built JAR that fixes this issue only)

**Comment by Ruukas97** [comment]
Great! :) Did you also fix the pick block method right under?

**Comment by SanjivanM** [comment]
Yep.  The code for that was nearly identical, so that *really* helped.  I might take what I've learnt and apply it to a few of my own mods :P
