### ISSUE TITLE
Blender And Cookie Jar Texture Problem

### ISSUE THREAD

**Issue by AR-JAXX** [MrCrayfish/MrCrayfishFurnitureMod#420]
I Have A Server Where I And My Friends Join On With A Bunch Of Mods And All Of A Sudden The Textures For The Cookie Jar And Blender Have Gone Weird. They Turn To Either Water, Red Water Or Ice. I Tried Deleting The Serene Seasons Mod Thinking That That Mod Was Trying To Change To Texture Of The Water (What The Blender And Cookie Jar Are Made Of) But That Didn't Work.

I Did Recently Get A Bunch Of Mods And Maybe That's What Happened.

Could Somone Read Through This Mod List And Tell Me If Maybe Any Of Them Are Clashing?
https://imgur.com/a/rFJ20Kp

**Comment by RubenVerg** [comment]
And Why Are You Writing In All Capitalized?

**Comment by AR-JAXX** [comment]
@RubenVerg Why Are You Writing In All Capitalized?

And Because I Like To See How Many People Get Bothered By It, Your One Of Em

**Comment by MrCrayfish** [comment]
ŮŚË ȚȞË BŮĠ ŖËPÖŖȚ ȚËMPĻÄȚË ÄŅĐ ŴŖÏȚË PŖÖPËŖĻŸ PĻËÄŚË
