### ISSUE TITLE
Crafting Chopped Log duplicates Axe

### ISSUE THREAD

**Issue by DoomRater** [MrCrayfish/MrCrayfishFurnitureMod#425]
**Describe the bug**
I crafted a pile of Chopped Logs and found that when I closed the crafting recipe, my axe had been duplicated.  This became even more apparent when shift-click crafting the recipe as the duped axe was returned to my inventory.

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.0

**Comment by DoomRater** [comment]
I've attempted to fix the issue by removing the recipe and place an identical recipe with CraftTweaker, but when this is done on a server the issue still persists, even when doing so fixes the issue on a single player world.

**Comment by clienthax** [comment]
This only occurs on servers, and not in single player.

**Comment by Pulz-TCP** [comment]
This is still an issue.

**Comment by DoomRater** [comment]
I used a dirty hack to fix it on my end- I removed the recipe and readded it myself using CraftTweaker, but differently on the server than on the client which you're not supposed to do.  The server has a recipe where the axe is consumed, but the axe duplication still happens and you do get it back, just with a desynced inventory.  Meanwhile the client (and thus singleplayer) has a CT recipe where the axe just takes some damage and that seems to do the trick.  Again, CraftTweaker is not supposed to run different recipes on client and server, but this seems to be the only fix I can implement that gets around the issue.

**Comment by Pulz-TCP** [comment]
@DoomRater I don't suppose you'd spare me the trouble and be willing to share the scripts? Or was this in the past.
Either way, thanks for the information.

**Comment by DoomRater** [comment]
I almost forgot about this, but- if you do fix it, Twilight Forest's Uncrafting Table will assume the axe is consumed and attempt to return it if you ever UNcraft logs, meaning that you MUST restrict it to an item that nobody will care to duplicate.  I chose a stone axe.

https://pastebin.com/fDpGJ6Qb

**Comment by DoomRater** [comment]
I've found the file responsible for the server duplication, but I don't know why this causes such a desync. Namely, I don't know how to specify that it should be used both on the client and server.  What I'm tempted to do instead is simply make a build with this file gone and see what happens.

https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/1.12.2/src/main/java/com/mrcrayfish/furniture/handler/CraftingHandler.java

**Comment by pinkwitchx** [comment]
Has this ever been fixed? It's an issue on my build that I downloaded maybe a month or so ago. 6.3.0
Crafted chopped logs and got back 17 diamond axes... 

@DoomRater did you find a fix?

**Comment by DoomRater** [comment]
https://github.com/DoomRater/MrCrayfishFurnitureMod/releases/tag/v6.3.1 Here's a build I made and released on my own fork.

**Comment by pinkwitchx** [comment]
@DoomRater Thanks a lot! I'll try it out!

**Comment by pinkwitchx** [comment]
@DoomRater Hey I still get the axe dupe bug. Is there somewhere we can DM? Don't want to clutter this up.

**Comment by DoomRater** [comment]
Enabled issues on my fork.  Why didn't I do that earlier? I have no idea.
