### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by JoshMayberry** [MrCrayfish/MrCrayfishFurnitureMod#426]
**Describe the bug**
When included, the game crashes while loading. 
When disabled, the game loads just fine.

**Crash report**
https://paste.dimdev.org/wejiqapeno.mccrash

**To Reproduce**
Launch the game, crashes on load screen

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: furniture-6.3.0-1.12.2.jar

**Comment by LemADEC** [comment]
You've too many mods, exceeding the game limit.
This is not due to a specific mod.
