### ISSUE TITLE
I can't see myself in mirror

### ISSUE THREAD

**Issue by JohnMackYouTube05** [MrCrayfish/MrCrayfishFurnitureMod#430]
**Describe the bug**
This occurs both in singleplayer worlds with the mod, and on my Forge server. My friend that plays on my server can see himself in the mirror from your mod, and I think I recall him saying he could see me in the mirror. But when I look in the mirror, if I'm on my server I can see my friend in the mirror, but I can't see myself. My skin doesn't load into the mirror. If I'm in singleplayer, all I can see is the room around me in the mirror. It gives me the illusion that I'm basically a ghost! Can someone please tell me how to fix this?

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Craft a mirror or get one from the creative menu
2. Place your mirror on a wall
3. Now look at the mirror. If you see yourself, then you can't reproduce this bug. If you can't see yourself, you have the same problem I do.

**Screenshots**
Here's what it looks like on my singleplayer world:
![2019-07-25_10 08 06](https://user-images.githubusercontent.com/16242045/61885814-1fb09500-aec4-11e9-9a21-a67f888210f3.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.0

**Comment by ColaLiao** [comment]
Can't see any thing...
![image](https://user-images.githubusercontent.com/16384174/63325564-fec14f80-c35c-11e9-8f84-2c5e28301087.png)
