### ISSUE TITLE
On a server, the blocks are black and purple, yet have textures on the handheld models.

### ISSUE THREAD

**Issue by Enframed** [MrCrayfish/MrCrayfishFurnitureMod#431]
**Describe the bug**
When using your Furniture Mod 7.0.0 for 1.14.3 Forge, it has an error when on a server. The models show in singleplayer, but in multiplayer they don't.
It's not a server-side issue, as the server has multiple other mods that also use custom models and textures, and they are fine. I removed all other mods and it still has this issue.
It's not just for me, for my friends on the same server all have the issue. The mod is installed correctly and even shows the hitbox and texture/model in-hand, but when placed as a block it is bugged.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Go to a server with the mods installed
2. Get a block from your mod
3. Place

**Screenshots**
![2019-07-26_14 37 55](https://user-images.githubusercontent.com/42250900/61955478-05091980-afb3-11e9-80bf-037e40d6b22e.png)
![2019-07-26_14 37 57](https://user-images.githubusercontent.com/42250900/61955482-06d2dd00-afb3-11e9-8318-3734b30542d9.png)
![2019-07-26_14 37 37](https://user-images.githubusercontent.com/42250900/61955485-09353700-afb3-11e9-9a78-e409e9335676.png)
![2019-07-26_14 37 52](https://user-images.githubusercontent.com/42250900/61955491-0afefa80-afb3-11e9-8c6d-c3392fdb21ab.png)

Please complete the following information:
- Minecraft Version: 1.14.3, Forge 27.0.14
- Mod Version: 7.0.0 pre2

**Comment by LorenzoPapi** [comment]
Try to update to latest version.
Close if fixed.
