### ISSUE TITLE
curtains color

### ISSUE THREAD

**Issue by noy98** [MrCrayfish/MrCrayfishFurnitureMod#432]
**Describe the bug**
I just placed any color curtains, it turns to white color.

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.0

**Comment by Kexerval** [comment]
Duplicate of #449 and #453
