### ISSUE TITLE
Missing Mod Items

### ISSUE THREAD

**Issue by JoshuaSellina** [MrCrayfish/MrCrayfishFurnitureMod#433]
Hello,

I recently installed this mod for minecraft 1.14.3.
For a seconde I though I had it working but then I found out that I am missing a lot of block.
When I look in the creatieve tabb and then page 2 at the MrCrayfish Furniture Mod tab, I see a selection of items.
The problem is, the only items I see are:
-Tables
-Chairs 
-Coffee tables 
-Cabinets
Those are the only items I see, I cant find the kitchen items like the fridge of the garden items like the fences etcetera.
I also tried crafting items like the fridge but no succes.
I have forge installed and the mod, I can place the given items without problems but Im missing so much blocks.

Am I missing something or..?

If there is anything you need to know, please tell me.
Thanks tot the help in advanced!

Yours Sincerely,
JoshuaSellina

**Comment by MrCrayfish** [comment]
#436

**Comment by Natetdw-labs** [comment]
Has 1.15.2 development stopped? I'm making a city and managed to realize there are no fans, light switches, ceiling lights, TVs, Computers, Printers, and a lot of other stuff
