### ISSUE TITLE
cant craft anything 

### ISSUE THREAD

**Issue by Raz12312** [MrCrayfish/MrCrayfishFurnitureMod#436]
i installed the mod just like you showen but i cant craft anything in game other then wood table

**Comment by Raz12312** [comment]
im on 1.14.4 and also the mod

**Comment by JoshuaSellina** [comment]
I have the same problem, only tables and chairs, look at my post (Missing Mod Items)

**Comment by MrCrayfish** [comment]
1.14 is in development, it's purposely missing everything because I am rewritting it all from scratch.

**Comment by biggnou** [comment]
> 
> 
> 1.14 is in development, it's purposely missing everything because I am rewritting it all from scratch.

Hello there MrCrayfish,

First of all, thank you for your hard work, I just discovered your mods on Youtube and it looks amazing, nothing less. I wanted to give a try to the furniture, and came up with the same issue as described above (I donwloaded the jar from your website, not from github).

This might be a communication issue, or me not doing things correctly, but I thought (based on youtube videos you recently released) that the mod was working for Minecraft 1.14.4.

Are you still in the process of refactoring all your code? Is "It's work in progress"  still the correct answer? And if so, do you provide any ETA, or is this a "you're banned, burn in hell" kind of question?

Thank you sir!

Alex.

**Comment by MrCrayfish** [comment]
@biggnou Yes the mod is still being updated to 1.14.4. I suggest following my Twitter and YouTube as that is where I will annouce when it has been complete. For now, I will be releasing development version.
