### ISSUE TITLE
Redstone not operating doors??

### ISSUE THREAD

**Issue by jsc255** [MrCrayfish/MrCrayfishFurnitureMod#437]
On version 1.12.2 the redstone levers, redstone torches, pressure plates, etc will not open the modded doors. They will open the regular minecraft doors but not the mrcrayfish doors. 

Thanks

**Comment by UltiMaxCZ** [comment]
I fixed it by replacing sliding door files in 6.3.0 with files from 5.12.0 version.

[CFM 6.3.0 - MC 1.12.2 - Sliding Doors Fix.zip](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3436829/CFM.6.3.0.-.MC.1.12.2.-.Sliding.Doors.Fix.zip)

**Comment by jsc255** [comment]
Thanks will try out now!

**Comment by ExDomino** [comment]
Which files have you replaced ? I tryed and it doesn't work for me.
