### ISSUE TITLE
Missing texture for Coffee Table

### ISSUE THREAD

**Issue by RepoDraghon** [MrCrayfish/MrCrayfishFurnitureMod#439]
**Describe the bug**
Missing Coffee Table texture

1.14.3
7.0.0.pre2

![2019-07-29_22 25 12](https://user-images.githubusercontent.com/8423696/62103095-3eaa8080-b250-11e9-91df-69c2c192ef26.png)

**Comment by MrCrayfish** [comment]
Are you using latest Forge?
