### ISSUE TITLE
[Suggestion] Mod for Spigot/Bukkit and Fabric 

### ISSUE THREAD

**Issue by lastsamurai26** [MrCrayfish/MrCrayfishFurnitureMod#440]
Hey, MsCrayfish,
have you ever thought about making your mod available for Spigot/Bukkit or if you want to build your mod based on Fabric because Forge is very slow at the moment?

**Comment by MrCrayfish** [comment]
You can't make mods for Spigot/Bukkit. I don't have time to create a version for Fabric. Use Forge 1.14.4
