### ISSUE TITLE
Content not loading on 1.14.4

### ISSUE THREAD

**Issue by ThatTonybo** [MrCrayfish/MrCrayfishFurnitureMod#446]
## **Describe the bug**
On recent versions of the Furniture mod, 1.14.4 pre4 specifically, the mod tab doesn't show an icon and no mod content is loaded in.

## **Crash report**
N/A as the game doesn't crash.

## **To Reproduce**
1. Install the 1.14.4 pre4 version of the mod into Minecraft Forge 1.14.4 version 28.0.41 or 28.0.45 (both tested)
2. Load the game and look in the creative tab

## **Screenshots**
Here's what it looks like for me; some other mods like ComputerCraft and MetalBarrels are doing it as well.
![image](https://user-images.githubusercontent.com/28176227/62681438-05ff6980-b9fd-11e9-8398-146854f2e71f.png)

Please complete the following information:
- Minecraft Version: 1.14.4, Forge 28.0.45
- Mod Version: cfm-7.0.0-pre4-mc1.14.4

**Comment by MrCrayfish** [comment]
Looks like a Forge bug
