### ISSUE TITLE
Breaking a microwave causes nearby players to crash

### ISSUE THREAD

**Issue by bloodmc** [MrCrayfish/MrCrayfishFurnitureMod#45]
http://pastebin.com/Eyx2kgVx

**Comment by Hyrules** [comment]
I'm also having this bug. Here is the crash log.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  MalisisCorePlugin (malisiscore-1.8.9-2.1.3.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/9/16 4:53 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at com.mrcrayfish.furniture.blocks.BlockFurniture.func_176201_c(BlockFurniture.java:63)
	at com.mrcrayfish.furniture.render.tileentity.MicrowaveRenderer.func_180535_a(MicrowaveRenderer.java:43)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:900)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:343)
	at shadersmod.client.Shaders.beginRender(Shaders.java:3637)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1522)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1328)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at com.mrcrayfish.furniture.blocks.BlockFurniture.func_176201_c(BlockFurniture.java:63)
	at com.mrcrayfish.furniture.render.tileentity.MicrowaveRenderer.func_180535_a(MicrowaveRenderer.java:43)

-- Block Entity Details --
Details:
	Name: cfmMicrowave // com.mrcrayfish.furniture.tileentity.TileEntityMicrowave
	Block type: ID #253 (tile.microwave // com.mrcrayfish.furniture.blocks.BlockMicrowave)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (664,87,17), Chunk: (at 8,5,1 in 41,1; contains blocks 656,0,16 to 671,255,31), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:900)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:343)
	at shadersmod.client.Shaders.beginRender(Shaders.java:3637)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1522)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Hyrules82'/161, l='MpServer', x=664.28, y=86.00, z=15.75]]
	Chunk stats: MultiplayerChunkCache: 2500, 2500
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 212.00,64.00,208.00 - World: (212,64,208), Chunk: (at 4,4,0 in 13,13; contains blocks 208,0,208 to 223,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 521994 game time, 7050 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 66 total; [EntitySquid['Squid'/263, l='MpServer', x=720.81, y=52.47, z=-48.28], EntityLift['Elevator'/162, l='MpServer', x=659.50, y=85.00, z=10.50], EntitySheep['Sheep'/163, l='MpServer', x=650.34, y=63.00, z=15.78], EntitySheep['Sheep'/164, l='MpServer', x=684.91, y=63.00, z=5.63], EntitySheep['Sheep'/165, l='MpServer', x=673.53, y=63.00, z=14.53], EntitySheep['Sheep'/166, l='MpServer', x=673.13, y=62.00, z=13.28], EntitySheep['Sheep'/167, l='MpServer', x=656.81, y=62.39, z=30.69], EntitySheep['Sheep'/168, l='MpServer', x=660.97, y=65.00, z=31.25], EntitySheep['Sheep'/169, l='MpServer', x=661.44, y=64.00, z=20.31], EntitySheep['Sheep'/170, l='MpServer', x=652.31, y=69.00, z=-12.94], EntitySquid['Squid'/171, l='MpServer', x=670.97, y=46.81, z=-30.50], EntitySquid['Squid'/172, l='MpServer', x=672.38, y=46.00, z=-30.50], EntityBat['Bat'/300, l='MpServer', x=592.34, y=48.03, z=89.19], EntitySquid['Squid'/173, l='MpServer', x=663.47, y=49.25, z=-31.69], EntityBat['Bat'/174, l='MpServer', x=701.69, y=17.10, z=6.22], EntitySquid['Squid'/177, l='MpServer', x=676.72, y=45.63, z=-35.34], EntitySquid['Squid'/178, l='MpServer', x=676.13, y=48.47, z=-28.56], EntityBat['Bat'/179, l='MpServer', x=691.91, y=46.88, z=-29.54], EntitySquid['Squid'/180, l='MpServer', x=665.50, y=45.00, z=-40.16], EntitySquid['Squid'/181, l='MpServer', x=669.03, y=47.16, z=-30.84], EntitySquid['Squid'/182, l='MpServer', x=670.56, y=48.03, z=-29.50], EntitySquid['Squid'/183, l='MpServer', x=709.03, y=41.13, z=7.09], EntitySquid['Squid'/184, l='MpServer', x=724.69, y=50.13, z=12.81], EntitySquid['Squid'/185, l='MpServer', x=674.44, y=45.03, z=-36.41], EntitySquid['Squid'/186, l='MpServer', x=669.47, y=51.03, z=-47.69], EntityBat['Bat'/187, l='MpServer', x=718.88, y=21.00, z=-14.09], EntitySquid['Squid'/188, l='MpServer', x=716.34, y=40.09, z=-10.06], EntitySquid['Squid'/189, l='MpServer', x=717.78, y=45.38, z=-7.38], EntitySquid['Squid'/190, l='MpServer', x=716.75, y=42.88, z=-7.44], EntityBat['Bat'/191, l='MpServer', x=714.25, y=23.10, z=26.25], EntitySquid['Squid'/192, l='MpServer', x=720.78, y=52.13, z=29.44], EntitySquid['Squid'/193, l='MpServer', x=676.34, y=59.44, z=52.06], EntitySquid['Squid'/194, l='MpServer', x=630.50, y=51.09, z=52.88], EntitySquid['Squid'/195, l='MpServer', x=619.00, y=57.19, z=60.91], EntityBat['Bat'/196, l='MpServer', x=612.75, y=22.19, z=-22.59], EntitySquid['Squid'/197, l='MpServer', x=700.19, y=46.00, z=-32.50], EntitySquid['Squid'/198, l='MpServer', x=704.00, y=49.19, z=-28.25], EntitySquid['Squid'/199, l='MpServer', x=714.81, y=53.75, z=-32.59], EntitySquid['Squid'/200, l='MpServer', x=720.13, y=53.88, z=-28.78], EntitySquid['Squid'/201, l='MpServer', x=722.34, y=50.81, z=-26.50], EntitySquid['Squid'/204, l='MpServer', x=722.84, y=47.41, z=1.75], EntitySquid['Squid'/205, l='MpServer', x=722.75, y=48.91, z=5.94], EntityBat['Bat'/206, l='MpServer', x=682.69, y=34.63, z=-62.59], EntityPlayerSP['Hyrules82'/161, l='MpServer', x=664.28, y=86.00, z=15.75], EntitySquid['Squid'/210, l='MpServer', x=691.47, y=48.44, z=-44.34], EntityBat['Bat'/216, l='MpServer', x=725.78, y=18.47, z=-5.28], EntityBat['Bat'/217, l='MpServer', x=720.84, y=22.63, z=-6.84], EntitySquid['Squid'/218, l='MpServer', x=721.63, y=46.16, z=-3.94], EntitySquid['Squid'/219, l='MpServer', x=725.50, y=57.34, z=-9.31], EntitySquid['Squid'/220, l='MpServer', x=729.84, y=62.28, z=-11.59], EntitySquid['Squid'/225, l='MpServer', x=716.34, y=46.81, z=-3.88], EntitySquid['Squid'/227, l='MpServer', x=706.25, y=47.03, z=-43.63], EntitySquid['Squid'/228, l='MpServer', x=706.50, y=49.69, z=-41.06], EntitySquid['Squid'/229, l='MpServer', x=711.66, y=51.53, z=-43.88], EntitySquid['Squid'/230, l='MpServer', x=712.84, y=50.22, z=-38.78], EntitySquid['Squid'/231, l='MpServer', x=717.91, y=54.59, z=-30.78], EntitySquid['Squid'/232, l='MpServer', x=712.31, y=58.97, z=61.03], EntityBat['Bat'/233, l='MpServer', x=646.54, y=14.00, z=58.13], EntityBat['Bat'/234, l='MpServer', x=629.44, y=12.00, z=77.69], EntityBat['Bat'/1258, l='MpServer', x=721.25, y=24.09, z=17.63], EntitySquid['Squid'/236, l='MpServer', x=685.44, y=48.03, z=-46.72], EntitySquid['Squid'/242, l='MpServer', x=697.25, y=49.50, z=76.16], EntitySquid['Squid'/245, l='MpServer', x=723.72, y=52.28, z=-31.03], EntitySquid['Squid'/246, l='MpServer', x=717.03, y=56.19, z=-35.03], EntitySquid['Squid'/247, l='MpServer', x=718.69, y=51.22, z=-44.16], EntityBat['Bat'/248, l='MpServer', x=743.81, y=22.22, z=2.88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 16x Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4818231144 bytes (4595 MB) / 6429081600 bytes (6131 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx6144M -Xms6144M
	IntCache: cache: 0, tcache: 4, allocated: 17, tallocated: 89
	FML: MCP 9.19 Powered by Forge 11.15.1.1847 Optifine OptiFine_1.8.9_HD_U_H5 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1847.jar) 
	UCHIJAAAA	Forge{11.15.1.1847} [Minecraft Forge] (forge-1.8.9-11.15.1.1847.jar) 
	UCHIJAAAA	ArchitectureCraft{1.4.1} [ArchitectureCraft] (ArchitectureCraft-1.4.1-mc1.8.9.jar) 
	UCHIJAAAA	cfm{3.6} [MrCrayfish's Furniture Mod] (cfm-3.6.1-mc1.8.9.jar) 
	UCHIJAAAA	cfmce{1.0.1} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0.1-mc1.8.9.jar) 
	UCHIJAAAA	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHIJAAAA	malisiscore{1.8.9-2.1.3} [MalisisCore] (malisiscore-1.8.9-2.1.3.jar) 
	UCHIJAAAA	malisisdoors{1.8.9-3.1.3} [MalisisDoors] (malisisdoors-1.8.9-3.1.3.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJAAAA	thutcore{2.4.6} [ThutCore] (thutcore-1.8.9-2.4.6.jar) 
	UCHIJAAAA	thuttech{2.3.5} [Thut's Tech] (thuttech-2.3.5.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
MalisisCorePlugin (malisiscore-1.8.9-2.1.3.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX TITAN X/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX TITAN X/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.51, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: LIFE 128x (Vers. 81).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_H5
	Render Distance Chunks: 25
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Continuum Preview - 1.8.9 - Preview2.zip
	OpenGlVersion: 4.5.0 NVIDIA 364.51
	OpenGlRenderer: GeForce GTX TITAN X/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by MrCrayfish** [comment]
It's fixed now :smile:
