### ISSUE TITLE
Printer automation issues

### ISSUE THREAD

**Issue by DoomRater** [MrCrayfish/MrCrayfishFurnitureMod#451]
**Describe the bug**
A hopper placed underneath the printer will pull everything out of it.

**Expected Behavior**
A hopper should only pull completed items from the final slot.

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version:  6.3.0

**Comment by ScythiaThe1st** [comment]
Crayfish did not "complete" this and just closed it

**Comment by MrCrayfish** [comment]
1.12.2 version is no longer maintained, hence the issue is closed.
