### ISSUE TITLE
Rendering Iusse

### ISSUE THREAD

**Issue by noy98** [MrCrayfish/MrCrayfishFurnitureMod#454]
**Describe the bug**
When I died next to mirror.
My launcher had a crash.

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

https://pastebin.com/wUWpUqGn

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by ProsperCraft** [comment]
Same 
furniture-6.3.1-1.12.2

https://gist.github.com/Geigren/c6f9321cbfd7780722f433cea4809442
