### ISSUE TITLE
When upgrading to furniture-7.0.0-pre5-1.14.4 furniture are waterlogged

### ISSUE THREAD

**Issue by Naetheline** [MrCrayfish/MrCrayfishFurnitureMod#456]
After an upgrade from furniture-7.0.0-pre4-1.14.4 to furniture-7.0.0-pre5-1.14.4 
(with an upgrade to forge 28.0.101) furniture previously placed lost their orientation and are waterlogged.

**Comment by MrCrayfish** [comment]
What version of Forge were you using previously?

**Comment by Neldardhen** [comment]
Guess it was the huge jump in version I did. New furniture are not waterloggd so it is ok.
