### ISSUE TITLE
v7.0.0-pre8 - 1.14.4 - Forge 28.1.10 - Some items don't load

### ISSUE THREAD

**Issue by fuzzyweapon** [MrCrayfish/MrCrayfishFurnitureMod#461]
**Describe the bug**
The items are not found in creative, through crafting, or JEI.  The only error I saw (though I could have missed one, is where it is trying to check the update.json and can't).

**Crash report**
No crash report, but log - https://pastebin.com/fdsC7mGw

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1.  Install MC 1.14.4 on server and client.
2.  Install Forge 28.1.10 on server and client.
3.  Install Furniture v7.0.0-pre8 on server and client.
4.  Launch server.
5.  Launch client.
6.  Connect to server once it is loaded.
7.  Observe that the *Mail Box* item does not appear in creative nor survival
(JEI, nor straight up crafting - used Mail Box for this test)

**Screenshots**
N/A

Please complete the following information:
- Minecraft Version: 1.14.4 - Forge 28.1.10
- Mod Version: v7.0.0-pre8

**Comment by MrCrayfish** [comment]
Mail Box is not released yet. It is coming in pre9
