### ISSUE TITLE
[1.14.4] Server Crash on Rename Postbox/Mailbox

### ISSUE THREAD

**Issue by kaffeekirsche** [MrCrayfish/MrCrayfishFurnitureMod#463]
**Describe the bug**
When i rename my Postbox and Push Save, the Server Crashed. See Crash Report

**Crash report**
[crash-2019-09-22_21.27.25-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3642247/crash-2019-09-22_21.27.25-server.txt)

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Go to Mailbox
2. Click on Edit Name Button
3. Change the Mailbox Name
4. Push Save

Please complete the following information:
- Minecraft Version: 1.14.4 forge-28.1.10
- Mod Version: furniture-7.0.0-pre9-1.14.4

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/4407992fea4134582e4e6c58a3a10a3a48c2a6a9
