### ISSUE TITLE
[cfm-7.0.0-pre10-mc1.14.4] Furniture Inventory is empty

### ISSUE THREAD

**Issue by BadHarry00** [MrCrayfish/MrCrayfishFurnitureMod#464]
**Describe the bug**
I open the inventory (Creative Mode) and click on the tab for the addon, but it is empty. Im tried to diesable an enable the filters, no result. 

**Crash report**
no entry in the Server Logs
no crashreport
no entry in debug.log
latest.log client  attached

[latest.log](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3653279/latest.log)
![2019-09-25_17 13 55](https://user-images.githubusercontent.com/30983485/65614455-f9889d80-dfb7-11e9-8011-a80a768a3b5b.png)

**Screenshots**
attached

Please complete the following information:
- Minecraft Version: 1.14.4
- Mod Version:
- cfm-7.0.0-pre10-mc1.14.4
- u_team_core-1.14.4-2.7.0.129
- forge 1.14.4-forge-28.1.19

**Comment by MrCrayfish** [comment]
Are you playing on a server or just single player?

**Comment by BadHarry00** [comment]
I’m playing on a Server. Is a Docker image on a Synology NAS System
The same version of Forge and other Mods.
 
Edit:
I'm tried in a single player game, thats works. 
I had no problems until version 8 with the server. I change only the furniture mod since version 8.
