### ISSUE TITLE
This is probably not a bug but you can break other player's mailboxes.

### ISSUE THREAD

**Issue by lizterr** [MrCrayfish/MrCrayfishFurnitureMod#466]
**Describe the bug**
This is not an issue. It's more like a suggestion. Can you make mailboxes indestructible and locked to other players to prevent them from stealing your stuff.

Please complete the following information:
- Minecraft Version: 1.14.4
- Mod Version: 7.0.0-pre10

**Comment by MrCrayfish** [comment]
I decided against proection and just wanted to keep it simple.
