### ISSUE TITLE
Missing Registry Entries After CFM Update

### ISSUE THREAD

**Issue by guodskrap** [MrCrayfish/MrCrayfishFurnitureMod#467]
**Describe the bug**
Forge issues a 'missing registry entries' warning when opening a world saved with a previous version of CFM.

**Additional notes**
When attempting to open with either cfm-7.0.0-pre9-mc1.14.4 or cfm-7.0.0-pre10-mc1.14.4, Forge issues the attached error, _Forge Mod Loader detected missing registry entries. There are 449 missing entries in this save._

To compare results, I created a new world with cfm-7.0.0-pre10-mc1.14.4. The world opens, but the furniture inventory is empty as in bug #464.

<img width="854" alt="CFM_error" src="https://user-images.githubusercontent.com/6117706/65682338-c8948100-e028-11e9-93d2-a77bdc763a5c.png">

**Crash report**
No crash report. 
[latest.log](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3657361/latest.log)

Please complete the following information:
- Minecraft Version: vanilla 1.14.4, single player
- Mod Version: cfm-7.0.0-pre10-mc1.14.4 - no other mods
- Forge Version: forge-1.14.4-28.1.0

**Comment by MrCrayfish** [comment]
Looks like Forge failed to load the mod. I'll look into the issue,

**Comment by guodskrap** [comment]
I did a fresh install of Forge in a new folder and copied the world over and pre10 now works. Still not sure why it did not before, but it is good now. 8^)

**Comment by MrCrayfish** [comment]
I will point out that the version of Forge you provided in the OP was inccorect. You were running 28.0.17
