### ISSUE TITLE
Mirror effect?

### ISSUE THREAD

**Issue by icedmoca** [MrCrayfish/MrCrayfishFurnitureMod#468]
**Describe the bug**
When a mirror is placed, I get a very circular effect and can only look around every 8 seconds but then does the same thing in like 2 seconds if I look at the mirror. The mirror looks black but I have to destroy it to be able to actually play Minecraft because it keeps freezing with this circular oval like thing. 

**Logs**
No logs, doesn't show anything.

**To Reproduce**
1. Place mirror
2. Look at it. Boom.

**Screenshots**
Cant. Unless I take a picture with my phone. If I pause the game, it goes away but then unpause and it comes back.

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: v6.3.0

**Comment by Josh65-2201** [comment]
Press F2 to take a screenshot in game then you can post it here.
