### ISSUE TITLE
A comment storage capacity and balance.

### ISSUE THREAD

**Issue by chrisbecke** [MrCrayfish/MrCrayfishFurnitureMod#47]
MrCrayfishFurnitureMod adds a number of decorative storage options - chests, wall cabinets etc. These are all attractive alternatives to placing vanilla chests.

However, for reasons I do not understand, these items all hold less than a chest would. This puts players like myself, who value utility highly, in a quandary - I do not believe that it should be necessary to trade utility for aesthetics.

**Comment by RackieW** [comment]
this mod is (almost) just for decoration!

**Comment by RackieW** [comment]
BTW this is not an issue/bug! Doesn't belong here!
