### ISSUE TITLE
resource packs which modifies models dosen't work on some elements

### ISSUE THREAD

**Issue by AnotherDevlop** [MrCrayfish/MrCrayfishFurnitureMod#470]
**Describe the bug**
Resource packs which modifies models, when applied, doesn't seem to override some blocks: 
Cabinet - models/block/cabinet_*.json [item not overrided, block not overrided],
Kitchen cabinet - models/block/kitchen_cabinet_*.json [item overrided, block not overrided]
Desk - models/block/desk_*.json [item not overrided, block not overrided],
            models/block/desk_cabinet_*.json [item not overrided, block not overrided]
Cooler - models/{block | items}/esky_*.json [item overrided, block overrided only handle]
Photo Frame - models/{block | items}/photo_frame*.json [item overrided, block overrided only glass element]
Modern Couch - models/{block | items}/modern_couch*.json [item overrided, block overrided only arm elements] 

**To Reproduce**
1. Apply a compatible resource pack that modifies the mentioned elements

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.2.0

**Comment by MrCrayfish** [comment]
This is more likely a lack of undertstanding overriding models, especially ones that use Forge Blockstates. Some of the blocks in my mod don't even have a item model json because Forge does it automatically.

**Comment by AnotherDevlop** [comment]
Thanks for pointing out. Now I managed to change it.
