### ISSUE TITLE
Where did the mirror code go?

### ISSUE THREAD

**Issue by KevOrr** [MrCrayfish/MrCrayfishFurnitureMod#474]
Hi, I'm trying to find the logic for mirrors. As far as I can tell, it disappeared in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/0f67e192deb1cc85ef6d30e976d9e77d2406fbf0. Is there somewhere it's moved to? Thanks.

**Comment by MrCrayfish** [comment]
Look at 1.12.2 branch
