### ISSUE TITLE
Yellow Office Chair's recipe incorrect

### ISSUE THREAD

**Issue by DoomRater** [MrCrayfish/MrCrayfishFurnitureMod#475]
**Describe the bug**
Yellow office chairs are crafted with light blue wool instead of yellow wool, making them uncraftable due to recipe conflict.  Discovered while auditing the recipe book using CraftTweaker to look for conflicting recipes.
I will use CraftTweaker to fix the recipe on my end, but that's a temporary fix...

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.0

**Comment by LorenzoPapi** [comment]
This is the wrong place to post the bug; the office chair is in the Device Mod
Report the issue here: [https://github.com/MrCrayfish/MrCrayfishDeviceMod](https://github.com/MrCrayfish/MrCrayfishDeviceMod)

**Comment by DoomRater** [comment]
Also it's been reported over there- my bad.
