### ISSUE TITLE
Glitched sofa model when near a carpet

### ISSUE THREAD

**Issue by BenHeavyson** [MrCrayfish/MrCrayfishFurnitureMod#479]
When placed adjacent to a carpet, a piece of the sofa's model disappears.

![2019-10-18_18 00 52](https://user-images.githubusercontent.com/56724593/67091334-91a02e00-f1d6-11e9-8921-6020f1888802.png)
![2019-10-18_18 00 55](https://user-images.githubusercontent.com/56724593/67091336-92d15b00-f1d6-11e9-9eff-e955e77ea585.png)

- Minecraft Version: 1.14.4
- Mod Version: 7.0.0-pre10

**Comment by Alethalen** [comment]
update to pre13 and close if fixed

**Comment by Alethalen** [comment]
still not fixed by the way
