### ISSUE TITLE
Request: Ender bedside cabinet.

### ISSUE THREAD

**Issue by chrisbecke** [MrCrayfish/MrCrayfishFurnitureMod#48]
A bedside cabinet seems a logical place to hold personal / private items.

I humbly request a version of the bedside cabinet - utilizing either an Ender Chest or simply Ender Eye in its construction - that allows access to the players (existing) Ender Chest storage.

**Comment by vampirebordello** [comment]
Hi - I have attempted to do this thing and have submitted a pull request with my implementation of the Ender Cabinet. :)
