### ISSUE TITLE
furniture-7.0.0-pre11-1.14.4.jar is for an older version and could not be loaded

### ISSUE THREAD

**Issue by MattRoxx** [MrCrayfish/MrCrayfishFurnitureMod#480]
Hello, with the 7.0.0 pre 11 Version i get the "is for an older version and could not be loaded" message.
With 7.0.0 pre 10 i dont get the message, and every thing is fine.

Forge is 1.14.4-28.1.61

Thank you

**Comment by MrCrayfish** [comment]
Send full client logs

**Comment by MattRoxx** [comment]
Hello, her is the log https://gist.github.com/MattRoxx/dee6479ed5b01b0a1346d74825443016

Interestingly, have only for the log removed all other mods, it worked. After that all mods pushed back it still worked. Have taken a backup from this morning to reproduce this log.

Also my work around was first to install furniture-7.0.0-pre11 alone, than copy the other mods back to the mods folder.

**Comment by MrCrayfish** [comment]
I don't know where you downloaded the mod from but it's saying it's missing the mods.toml file. In the log it says this. I've checked CurseForge and my websites and the mods.toml file is definitely in the jar archive.

```
furniture-7.0.0-pre11-1.14.4.jar is missing mods.toml file
furniture-7.0.0-pre11-1.14.4.jar has been ignored - it is invalid
```

**Comment by MattRoxx** [comment]
I downloaded it from CurseForge. Maybe an other of my mods affect the installation of your furniture mod? thanks for your time, i think we can close this issue.
