### ISSUE TITLE
Incompatible Optifine y MrCraayfish 1.14.4 ?

### ISSUE THREAD

**Issue by Annubis80** [MrCrayfish/MrCrayfishFurnitureMod#481]
Es posible que este mod en su ultima versión sea incompatible con Optifine?

**Comment by Annubis80** [comment]
porque lo cerráis si nadie me a respondido ni me han solucionado nada?

**Comment by LorenzoPapi** [comment]
Por favor escribe en inglés. Gracias (Google Translate)
