### ISSUE TITLE
[1.12.2] Modden beds exploding when they shouldn't

### ISSUE THREAD

**Issue by Josh65-2201** [MrCrayfish/MrCrayfishFurnitureMod#483]
When using modern bed anywhere other then the overworld (I know they don't work in the nether or end) it will exploded even when normal beds work.

- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by MrCrayfish** [comment]
Hmm try a normal bed in the nether mate

**Comment by Josh65-2201** [comment]
What i never said it was in the nether and it seems to be only the new tardis mod (https://www.curseforge.com/minecraft/mc-mods/new-tardis-mod) dimension it blows up in.

**Comment by MrCrayfish** [comment]
Probably because that mod doesn't test for beds dynamically, it only recognises Vanilla beds. You're better off reporting the issue to that mod.
