### ISSUE TITLE
[1.14.4] Sided Setup Event Phase Null Error

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishFurnitureMod#484]
**Describe the bug**
- I'm not sure what causes the error, but most of the time when I try to load my game with the Furniture mod, I get the error as seen in the image below.
- Optifine is not installed
- If you check out the timestamp `[18:56:10]` in the log, it indicates some type of error.

**Crash report**
No crash report, but [here ](https://gist.github.com/WenXin20/7fe60ffa4ed631ddc40c8c75139185e5)is a log

**To Reproduce**
1. Load game 
2. Error?

**Screenshots**
![2019-11-17_19 03 48](https://user-images.githubusercontent.com/12000593/69017639-f7b2d900-096d-11ea-9cfd-5fd24c19a123.png)

Versions:
- Minecraft Version: 1.14.4
- Mod Version: 7.0.0-pre11

**Comment by Alethalen** [comment]
load the game WithOUT mods to clear entries. then reload the game with the mod, 
DO NOT attempt to play the world without mods
BE SURE TO BACK IT UP
Your registry entries need to be refreshed

**Comment by WenXin20** [comment]
Interesting, I'll try that out. Thanks

**Comment by Alethalen** [comment]
any luck?

**Comment by MrCrayfish** [comment]
Have you tried the latest version of the mod?

**Comment by WenXin20** [comment]
Not yet, but I'll try it again soon

**Comment by WenXin20** [comment]
Latest version works :)
