### ISSUE TITLE
[1.12.2] Presence of light switch causes crash

### ISSUE THREAD

**Issue by PeterBlake77** [MrCrayfish/MrCrayfishFurnitureMod#485]
**Describe the bug**
Adding a light switch to the world (while Effortless Building's mirror feature is on?) causes a crash with error "java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to up on block cfm:light_switch_off, it is not an allowed value".
Re-entering the same world produces the same crash within 10 seconds.
Removing the mod, clearing the mod's blocks from the world, and re-installing the mod clears the crash (until the next placement).

**Crash report**
[https://pastebin.com/bdSGQkKw]

**To Reproduce**
(Possible trigger step: Turn on Effortless Building's "mirror" feature near the current co-ordinates.)
Place a light switch (within the area affected by mirror?).
Wait.

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.0

Thanks in advance for your help.

**Comment by LorenzoPapi** [comment]
What is Effortless Building? And have you reported the issue to them too?
