### ISSUE TITLE
[Minecraft 1.12.2] Player Is Always Glitched Sleeping Behind Modern Bed (Seen In Multiplayer)

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishFurnitureMod#489]
**Describe the bug**
Player attempts to sleep on the modern bed and they are shown sleeping but clipped through the headboard (can even go through walls)

**To Reproduce**
The steps to reproduce the behavior:
1. Right Click on Modern Bed at night
2. See Error (only able to be seen and shown from another player)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: v6.3.0

**Comment by LorenzoPapi** [comment]
Please post screenshots

**Comment by ghost** [comment]
This is the only photo a friend took from yesterday
https://imgur.com/a/LcEBiFK
