### ISSUE TITLE
Where is 1.7.10's Source?

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishFurnitureMod#49]
I want to read and learning 1.7.10 (3.4.8)'s code but I can't find it...
What should i do? Thanks!

**Comment by NDruce** [comment]
I joining request for 1.7.10 sources

**Comment by TheCodedOne** [comment]
I don't think anyone has the 1.7.10 code anymore, _I Could be wrong though_

**Comment by MrCrayfish** [comment]
I still have it obviously, I might put it up soon!

**Comment by Metatricity** [comment]
@TheCodedOne Of course you are wrong, reason being is that people have the jar file. The jar contains all of the code you'd need for 1.7.10, just compiled with a manifest :+1:

**Comment by SourcePowered** [comment]
@Metatricity NO, you are wrong, there is no any source files in jar file.

**Comment by SourcePowered** [comment]
@MrCrayfish Please upload the 1.7.10 code, which is very important for us, because if the lack of this part, on behalf of our server is not complete, thank you!

**Comment by KillerMapper** [comment]
Hello, I would like to get the 1.7.10 code as well so I can try fixing that achievement glitch for once on my server. Any news? Thanks.

**Comment by Metatricity** [comment]
@SourcePowered Wow, I'm really stupid. I posted this when I was like trying to be a cool kid. I realize I was wrong. Sorry for the late reply aswell.

Bump.

**Comment by NDruce** [comment]
No news(

**Comment by iBars** [comment]
No news(

**Comment by Metatricity** [comment]
Could use a class decompiler from the 1.7.10 jar.

**Comment by robin840211** [comment]
Though already solved in newer mc versions and much newer uses "state" instead, could see here for 1.7.10's v3.4.8 solution with simply class replacement.
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/99#issuecomment-388273769

**Comment by RagexPrince683** [comment]
any updates?
