### ISSUE TITLE
[1.14.4] Dedicate Server: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by kaffeekirsche** [MrCrayfish/MrCrayfishFurnitureMod#491]
**Describe the bug**
Dedicate Server cant Starting. 
Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER

**Crash report**
[crash-2019-12-09_16.26.37-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3940382/crash-2019-12-09_16.26.37-server.txt)

**server.log**
[2019-12-09-1.log](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3940385/2019-12-09-1.log)

**debug.log**
[debug-1.log](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3940386/debug-1.log)

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Install the Furniture Mod 7.0.0-pre14 on Dedicate Server
2. Start the Server
3. See Log files

Please complete the following information:
- Minecraft Version: 1.14.4-forge-28.1.104
- Mod Version: Furniture Mod 7.0.0-pre14

**Comment by Omnimetatron** [comment]
https://pastebin.com/yBR8F7Mx

Dedicated server crashed on load.

**Comment by Spiderach** [comment]
This only seems to be an issue with release 7.0.0-pre14 , pre13 works fine 

[crash-2019-12-09_20.24.30-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3942716/crash-2019-12-09_20.24.30-server.txt)

**Comment by Rakambda** [comment]
Maybe related to https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/bb4486b2054cf382304785b875d77867e5878c8e

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/670cceb22c1cd7988b230bd6f79b9535d1e3901a
Download 7.0.0-pre15 to fix
