### ISSUE TITLE
[1.14.4] LoadingFailedException

### ISSUE THREAD

**Issue by kreezxil** [MrCrayfish/MrCrayfishFurnitureMod#492]
Issue:  furniture-7.0.0-pre14-1.14.4 crashes dedicated server Forge 1.14.4 build 28.1.104

Notes:
     LoadingFailedException

crash report:
http://paste.ubuntu.com/p/YGfgdVT94F/

fml server latest:
http://paste.ubuntu.com/p/y6VQ4NR4P3/

**Comment by Wissi** [comment]
Same issue using newest Forge versions to date.

Using:
Forge 28.1.104   &   28.1.106
furniture-7.0.0-pre14-1.14.4.jar

Full Server crash log [here](https://gist.github.com/Wissi/2523e6e0ac2c9b0af2aa48c3283f6245).

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/670cceb22c1cd7988b230bd6f79b9535d1e3901a
Download 7.0.0-pre15 to fix
