### ISSUE TITLE
[1.14.4] Small Issues with Desk Drawers & Waterlogging

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishFurnitureMod#493]
**Describe the bug**
1. Desk drawers cannot be selected, the mouse will instead select the block below it.
   a) To open or break it, you have to look at the top of the desk.
2. Diving Boards can't be placed underwater, even though it can be waterlogged.
3. Crates, Sinks, Counters, & Counters with Drawers can't be waterlogged.

**To Reproduce**
Bug 1:
1. Place a desk drawer.
2. Try to select the drawers without selecting the back of it. (Image Below)

Bug 2 & 3:
1. Try to place Diving Boards, Crates, Sinks, or Counters underwater

**Screenshots**
As seen in the image, instead of the desk being selected, the sand is selected instead:
![2019-12-10_14 40 09](https://user-images.githubusercontent.com/12000593/70568365-562e3a00-1b5d-11ea-8ae2-64372ca014f6.png)

Please complete the following information:
- `Furniture: [7.0.0-pre14]`
- `Forge: [28.1.104]`
- `Minecraft: [1.14.4]`

**Comment by MrCrayfish** [comment]
Fixed in 1.16 version of the mod. Won't be updating 1.14 anymore.
