### ISSUE TITLE
1.12.2 Modern stairs require axe to break

### ISSUE THREAD

**Issue by DoomRater** [MrCrayfish/MrCrayfishFurnitureMod#495]
The materials used to craft modern stairs are iron and concrete, both of which are typically harvested with a pickaxe.  Yet the stairs require an axe to break.

**Comment by LorenzoPapi** [comment]
The problem is here:
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/1.12.2/src/main/java/com/mrcrayfish/furniture/blocks/BlockModernStair.java/#L37
The Block Material is wood.
