### ISSUE TITLE
[1.14] All furniture does not have a specific tool to break it.

### ISSUE THREAD

**Issue by lance-374** [MrCrayfish/MrCrayfishFurnitureMod#499]
No matter what tool you use, if you use a tool, it is still slow to break the furniture blocks.  And the couch cannot be harvested, as if you are mining stone without a pickaxe.
This is in version 7.0.0 pre15.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/dec1c873354eaa8e13b48b046f58c14043c070e1
