### ISSUE TITLE
Side load crash with Forge 1.15.1 - 30.0.17

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [MrCrayfish/MrCrayfishFurnitureMod#500]
Minecraft 1.15.1

furniture-7.0.0-pre15-1.15.1

Latest Forge rendering changes/fixes break your mod.

**Comment by chicovirus** [comment]
crash for forge 1.15.1 - 30.0.0.18 too

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/420f7ed16a21fb7c87dbfc230090449d737cc938
Download pre16
