### ISSUE TITLE
[1.15] Furniture mod crash

### ISSUE THREAD

**Issue by Lakxar** [MrCrayfish/MrCrayfishFurnitureMod#501]
**Crash report**
I´m using minecraft forge version 1.15.1-30.0.18 and when forge is finishing loading I get an error / crash

"MrCrayfish´s Furniture Mod (cfm) encountered an error during the sided_setup event phase".

**Screenshots**
![aya](https://user-images.githubusercontent.com/59364305/71582943-f11d9280-2ad1-11ea-925e-d6374b9f9e21.png)

**ERROR LOG**
https://pastebin.com/yr2663q7

- Minecraft Version: 1.15.1
- Mod Version: furniture-7.0.0-pre15-1.15.1

**Comment by LorenzoPapi** [comment]
I think that the rendering of TileEntites changed in 1.15, so MrCray must adjust the rendering part before releasing officially 1.15 version of the mod.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/420f7ed16a21fb7c87dbfc230090449d737cc938
Download pre16
