### ISSUE TITLE
[1.14.4] Wrong collision box

### ISSUE THREAD

**Issue by magiczocker10** [MrCrayfish/MrCrayfishFurnitureMod#503]
**Description**
The desk cabinet uses the same collision box as the desk.

**Screenshots**
![2019-12-31_10 30 09](https://user-images.githubusercontent.com/59317952/71616834-8abf6f80-2bb8-11ea-8c82-42ed4542d1e3.png)

**Game info**
- Minecraft Version: 1.14.4
- Mod Version: 7.0.0-pre15
- Forge Version: 1.14.4-forge-28.1.109

**Comment by magiczocker10** [comment]
The collision box from the kitchen sink and the kitchen drawer isn't correct aswell.

**Comment by MrCrayfish** [comment]
Fixed in recent versions
