### ISSUE TITLE
[1.14.4] Missing particles

### ISSUE THREAD

**Issue by magiczocker10** [MrCrayfish/MrCrayfishFurnitureMod#504]
**Description**
The kitchen sink has a missing particle texture when broken.

**Screenshots**
![2019-12-31_10 45 53](https://user-images.githubusercontent.com/59317952/71617300-c2c7b200-2bba-11ea-82d1-bd5477574a2d.png)

**Game info**
- Minecraft Version: 1.14.4
- Mod Version: 7.0.0-pre15
- Forge Version: 1.14.4-forge-28.1.109

**Comment by MrCrayfish** [comment]
I don't know when but this has been fixed since. I won't be maintaining 1.14.4 anymore though
