### ISSUE TITLE
[1.12.2] Client hard lock due to image downloading Photo Frame - proof.

### ISSUE THREAD

**Issue by ProsperCraft** [MrCrayfish/MrCrayfishFurnitureMod#511]
**Describe the bug**
In our town on the official TownCraft modpack server players all locked when they got close to a house, a Thread dump of a client that was fully locked up showed this- 
"Image Download Thread" #224 prio=5 os_prio=0 tid=0x000000005bd58000 nid=0x2e34 waiting for monitor entry [0x000000011a3ef000]
   java.lang.Thread.State: BLOCKED (on object monitor)

**Crash report**
Tread dump-
https://gist.github.com/BlackAce21/0c10f8c54ee34277fcd195a0da38f14f

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place a bunch of Image frames
2. Put images on them

Please complete the following information:
- Minecraft Version: 1.12.2 - https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/
- Mod Version: furniture-6.3.1-1.12.2

**Comment by Inari-Whitebear** [comment]
Also experiencing that randomly.
Pretty much the same cache dump too, anything new on this?
