### ISSUE TITLE
[1.14.4] Mod causes game to choppily freeze

### ISSUE THREAD

**Issue by ziviabea** [MrCrayfish/MrCrayfishFurnitureMod#512]
I have been using forge 28.1.0 for a little while now and tried to install this mod for 1.14. After adding it I tried to open the game, but forge said I needed 28.1.4 or above. I tried installing 28.1.11 and then replaced it with 28.1.5 but issues came up each time. MC loaded incredibly slowly and once I got into a world, the game froze every few seconds. Without this mod, the game worked fine. 
I came back to MC the next day and tried to run it with an old furniture mod (I think a bare basics version of this one?) that I was using before. Now that mod no longer works either.

I'm using a Macbook w/ Mojave. 
1.14.4 Minecraft. Optifine is installed.

Any help would be greatly appreciated, thanks!

**Comment by MrCrayfish** [comment]
It's Optifine, it's not optimised to handle lots of blocks. I suggest running the game without it or look for other performance mods. There are many on CurseForge. There is nothing I can do because it's Optifine's problem. All my mod does is add more blocks, nothing special.
