### ISSUE TITLE
crash when opening computer gui from client computer

### ISSUE THREAD

**Issue by chyper111** [MrCrayfish/MrCrayfishFurnitureMod#514]
**Describe the bug**
A clear and concise description of what the bug is. it crashed when i opened the computer from my LAN connected computer player.

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.https://pastebin.com/u7gTHTcR

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version:1.12
- Mod Version:6.3.0

**Comment by chyper111** [comment]
So you closed this because you think it's fixed your a worthless modder. Ill never play your shit again you loser.

**Comment by MrCrayfish** [comment]
bye!

**Comment by aemogie** [comment]
> So you closed this because you think it's fixed your a worthless modder. Ill never play your shit again you loser.
1) *you're
2) 1.12 is not supported anymore. Forge stopped supporting it so MrCrayfish **had** to stop supporting it.
3) Just because you have nothing else to do doesn't mean the same applies to others as well.
