### ISSUE TITLE
Letters and Packages increase inventory.

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [MrCrayfish/MrCrayfishFurnitureMod#52]
I noticed that players are using packages to carry a lot more items than intended and I think this is a big balancing issue, as this allows carrying around up to 6 times more stuff.
To prevent this, unsealed packages should not be allowed to hold items when put pack in the inventory.

**Comment by MrCrayfish** [comment]
Will looking into changing this.

**Comment by RackieW** [comment]
Same with Present & Envelope

**Comment by MrCrayfish** [comment]
Closing due to Shulker boxes

**Comment by MrCrayfish** [comment]
Opening again. Will disable shulker boxes being added into said items

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/06acacefc8de4676d26a5250398ed2cc215c7c93
