### ISSUE TITLE
[1.12.2] TV Blacks creen

### ISSUE THREAD

**Issue by DCCross** [MrCrayfish/MrCrayfishFurnitureMod#525]
**Describe the bug**
-Tv gif black screen-

Hi, I've tried to see gifs or images with their mod and it doesn't seem to work in any way, I tried removing all the mods and leaving only their mod and even so the black screen appeared on the TV. please help :(

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. copy any gif
2. Click on tv and paste turn on, press "x"
3.and shows a black screen 

**Screenshots**
![2020-02-10_01 39 45](https://user-images.githubusercontent.com/60871026/74129885-4c00da00-4ba6-11ea-9330-2900c56d2087.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by MrCrayfish** [comment]
Didn't turn it on lol

**Comment by DCCross** [comment]
When turning it on it shows the screen and when turning it off a dark blue .-.

OFF
![2020-02-10_22 22 57](https://user-images.githubusercontent.com/60871026/74211079-f3881600-4c53-11ea-9ec9-8f13207ddf11.png)

ON
![2020-02-10_22 23 32](https://user-images.githubusercontent.com/60871026/74211105-0864a980-4c54-11ea-8d1a-a980ed623377.png)
