### ISSUE TITLE
Photo Frame show black square when using transparent background PNG

### ISSUE THREAD

**Issue by Tommy0607** [MrCrayfish/MrCrayfishFurnitureMod#528]
**Describe the bug**
the Photo Frame has black square on the right-bottom when using transparent background PNG
![image](https://user-images.githubusercontent.com/13654195/74411734-f4e55880-4e76-11ea-805b-c3c05249d957.png)

**To Reproduce**
Here is the test URL I use: https://upload-images.jianshu.io/upload_images/11423226-8845a4ad2a60b7d1.png

**Screenshots**
![image](https://user-images.githubusercontent.com/13654195/74411734-f4e55880-4e76-11ea-805b-c3c05249d957.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by ghost** [comment]
This can be fixed by deleting these lines and recompiling the mod: https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/java/com/mrcrayfish/furniture/render/tileentity/PhotoFrameRenderer.java#L157-L165

It seems to be a leftover from the TV rendering code.
