### ISSUE TITLE
tv in furniture mod doesn´t work (black screen)

### ISSUE THREAD

**Issue by DenisTheTechGuy** [MrCrayfish/MrCrayfishFurnitureMod#530]
I inserted a link that was in the mod description (https://giphy.com/gifs/minecraft-enderman-j5ThXdq3wTKdW)
![2020-02-18_12 25 12](https://user-images.githubusercontent.com/61188426/74732162-ea95d680-5249-11ea-88be-5c2a092ae2b2.png)
![2020-02-18_12 25 18](https://user-images.githubusercontent.com/61188426/74732165-ebc70380-5249-11ea-85ff-2376bc4897e3.png)

 turned it on and nothing happened not even failed to download error

**Comment by Yitzhakbuff** [comment]
did you solve it?
