### ISSUE TITLE
1.12.2 Mod Crash

### ISSUE THREAD

**Issue by NekoOne** [MrCrayfish/MrCrayfishFurnitureMod#532]
Mod Crashed my game
here is link that it told me to send https://paste.dimdev.org/apoponaquy.mccrash

**Comment by ThoBekMic** [comment]
That's crashing because your graphics card doesn't support the mirror rendering method. Time to upgrade that 10+ years old PC :-)

**Comment by NekoOne** [comment]
haha, 2 days later i broke the CPU and i now have a quad core gaming PC
