### ISSUE TITLE
[MINECRAFT VERSION 1.12.2] TV AND PHOTO FRAME ISSUE

### ISSUE THREAD

**Issue by KillerQueenW** [MrCrayfish/MrCrayfishFurnitureMod#535]
BUG:
When I put an URL in the "Modern TV" and also in the "Photo Frame" it´s turn in a black image, the gifs don´t play, and in the Photo Frame the images who are "PNG" are completely in black. 

Example of how the Photo Frame doesn´t work:
![unknown](https://user-images.githubusercontent.com/61392927/75120714-28806980-5653-11ea-8606-22cd14ae0252.png)
the image shows how the photo frame doesn´t work correctly, the url is a PNG photo, and it only shows the silhouette

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1-1.12.2

**Comment by Will-Scrolls** [comment]
Yeah I get this issue as well, my friends can see the pictures fine but it looks like this for me
