### ISSUE TITLE
[1.14.4]  Incompatibility with 3D resoursepack

### ISSUE THREAD

**Issue by RomanKaberlad** [MrCrayfish/MrCrayfishFurnitureMod#536]
(Sorry for my english learning plz)

Hello! Thank you for mod, its awesom. But... If i enable 3d texturepack(https://www.curseforge.com/minecraft/texture-packs/default-3d-16x) with them? minecraft impossible to play. Forge has very long load, and minecraft and
freeze every five seconds. If i disable mod and enable resoursepack, all is normal. If i disable resoursepack and enable you mod, too. I dont have idea why. I'd like your mod, and Pack, but i forced to choose between them. 

I played with shaders, but if i off them, doesnt changed

Optifine HD U F5
Minecraft 1.14.4
Mod Version V7.0.0-Pre15

**Comment by MrCrayfish** [comment]
You're loading mods and texture packs on a single thread when using optifine. Uninstall optifine and try it.

**Comment by RomanKaberlad** [comment]
> You're loading mods and texture packs on a single thread when using optifine. Uninstall optifine and try it.

Hello, thanks for answer! I take off optifine, and all normal, but.. Optifine is whery important for me. Is there any way to fix problem?

Optifine with mod-all normal
Resoursepack with optifine-minecraft dont freeze

But if it's all toogether, minecraft starting lag. With other mod all normal to. But if i move from mods folder all mods besides Optfine and Furniture mod and ResPack, minecraft starting lags

My modlist
![2020-02-24_22-45-28](https://user-images.githubusercontent.com/61405029/75167090-71214b00-5757-11ea-8756-2377d19b50b2.jpg)

**Comment by MrCrayfish** [comment]
There is nothing you or I can do. Optifine simply doesn't multithread the loading process unlike Forge.

**Comment by RomanKaberlad** [comment]
> There is nothing you or I can do. Optifine simply doesn't multithread the loading process unlike Forge.

Very sad, thanks for the answer, good luck
