### ISSUE TITLE
[1.12.2] Open Modular Turrets Crash

### ISSUE THREAD

**Issue by SnaveSutit** [MrCrayfish/MrCrayfishFurnitureMod#542]
**Describe the bug**
The game crashes when attempting to tick an open modular turret's turret head.

**Crash report**
https://paste.dimdev.org/dajasuwamu.mccrash

**To Reproduce**
1. Install [Open Modular Turrets](https://www.curseforge.com/minecraft/mc-mods/openmodularturrets/files/2897119) 
2. Open a world and place down a few turrets
3. Install obfuscate and furniture mod.
4. Try and load the world again

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by Jimmy805** [comment]
Hello! May I ask which version of Open Modular Turret you installed? Is it the latest version?

**Comment by SnaveSutit** [comment]
I'd wager it was the latest version available on march 10th. I no longer have the personal modpack I was making so I don't know exactly what version it was. But I usually use latest available

**Comment by Jimmy805** [comment]
Ok! But as far as I know, Open Modular Turrets has been updated for a few times after March 10th. And the latest version is released on June 8th. Maybe the new version can solve this problem.
