### ISSUE TITLE
[1.14.4] freeze when using with optifine

### ISSUE THREAD

**Issue by OrdinaryBear** [MrCrayfish/MrCrayfishFurnitureMod#543]
So when I try to start Minecraft with Optifine and this mod, the game freezes when showing the Mojang logo. It does work with earlier versions of the mod (pre10) but causes the game to run at like 0.01 fps.

Here is the log file : https://pastebin.com/uSFRdKQU

Screenshot :

![Capture](https://user-images.githubusercontent.com/62072002/76444831-d5354780-63c4-11ea-861e-786d7df08889.PNG)

Minecraft Version: 1.14.4
Mod Version: 1.14.4 pre15

**Comment by MrCrayfish** [comment]
It's Optifine not multithreading the loading process. Forge does this but when Optifine is installed, it overrides their loading process. There is nothing I can do, all you have to do is wait.
