### ISSUE TITLE
[1.14] using the wood seats stops me frm placing paintings :(

### ISSUE THREAD

**Issue by budder165** [MrCrayfish/MrCrayfishFurnitureMod#548]
**Describe the bug**

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version:
- Mod Version:

**Comment by MrCrayfish** [comment]
Didn't even fill in the details...
