### ISSUE TITLE
[1.12.2] Compatibility issue with Cacti

### ISSUE THREAD

**Issue by yezhiyi9670** [MrCrayfish/MrCrayfishFurnitureMod#549]
**Describe the bug**

Cacti is a mod which enables more immediate access to mods' creative tabs, but it's discontinued. I [ported it to 1.12.2](https://github.com/yezhiyi9670/cacti-renewed) and am now maintaining it.

Cacti's category menu is displayed on the left side of the screen, this conflicts with Furniture Mod's item filter. Also, selecting a tab which has the same position (tabIndex) as the furniture tab will display Furniture Mod's item filter and items even though the tab isn't the Furniture tab.

**Crash report**

The bug does not cause a crash.

**To Reproduce**

1. Install just [Cacti](https://www.curseforge.com/minecraft/mc-mods/cacti-categorical-creative-inventory-1-12-2) and MrCrayfish's Furniture Mod on a new 1.12.2 game profile.
2. Create a world. Open creative inventory.
3. Select "MrCrayfish's Furniture Mod" category. The item filter will render on top of the category menu (bug 1).
4. Click back to "Minecraft" category. Select "Decoration" tab, and re-select "Building blocks". The item filter will still be shown, and the inventory will display furniture items instead of building blocks (bug 2).

![image](https://user-images.githubusercontent.com/39194383/77382658-dcdcef00-6dbb-11ea-8a2c-3fd020f4fc78.png)

![image](https://user-images.githubusercontent.com/39194383/77382705-fc741780-6dbb-11ea-819d-364a329da551.png)

![image](https://user-images.githubusercontent.com/39194383/77382891-7c9a7d00-6dbc-11ea-890b-6fd836851270.png)

Please complete the following information:
- Minecraft Version: 1.12.2-14.23.5.2847
- Mod Version: 6.3.1

**Suggestion**

Add a config option to seperate furniture items into several creative tabs and disable the item filter.

**Comment by MrCrayfish** [comment]
I'll add a config option
