### ISSUE TITLE
Mr Crayfish Vehicle Mod and Obfuscate Plugin crashing my game. Game version 1.12.2

### ISSUE THREAD

**Issue by tedkaj231** [MrCrayfish/MrCrayfishFurnitureMod#551]
Mr Crayfish Vehicle Mod and Obfuscate Plugin crashing my game. Game version 1.12.2

**Comment by MrCrayfish** [comment]
Send a crash report or I'm closing this issue

**Comment by MrCrayfish** [comment]
Closing anyway because you reported this opn the Furniture Mod repo
