### ISSUE TITLE
[1.15.2] Stripped Kitchen Drawers Have No Recipe

### ISSUE THREAD

**Issue by demonJ5** [MrCrayfish/MrCrayfishFurnitureMod#552]
**Describe the bug**
There are no valid recipes to craft the stripped kitchen drawer blocks of any type of wood.

This is because the recipe does not give a "Stripped" version as the output.

Excerpt from `stripped_spruce_kitchen_drawer.json`
```
"result": {
        "item": "cfm:spruce_kitchen_drawer",
        "count": 4
```
while it should presumably be
```
"result": {
        "item": "cfm:stripped_spruce_kitchen_drawer",
        "count": 4
```
Here is a .zip with the files modified as appropriate
https://www.dropbox.com/s/mu2rean92onqz7t/fixed%20recipes.zip?dl=0

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Go to JEI
2. Search for kitchen drawer
3. Click any stripped kitchen drawer
4. No recipe is available
5. Attempting a similar recipe to the non-stripped versions is equally fruitless.

Please complete the following information:
- Minecraft Version: 1.15.2
- Mod Version: 7.0.0-pre16

**Comment by MrCrayfish** [comment]
Fixed in recent versions
