### ISSUE TITLE
[1.15.2] Items are missing

### ISSUE THREAD

**Issue by DasFantatier** [MrCrayfish/MrCrayfishFurnitureMod#553]
**Items are missing**
There aren´t all items. There are fences, kitchen wood furniture, chairs, but no bathroom furniture, modern kitchen and more. I tried the mod downloading from the curseforge site and also from your own website. The two .jar files are named differently, but the issue is the same. I haven´t found any information about missing items in 1.15.2 yet.

**Crash report**
There is no crash.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**
Adding 2 screenshots of the creative menu with all items from this mod

Please complete the following information:
- Minecraft Version: 1.15.2
- Mod Version: I tried "MrCrayfishs-Furniture-Mod-1.15.2.jar" from your homepage and "furniture-7.0.0-pre16-1.15.1.jar" from the curseforge site. Both are the latest 1.15.2 files.
![Screen Shot 03-29-20 at 07 35 PM 001](https://user-images.githubusercontent.com/62701156/77856029-bc19fc80-71f4-11ea-99c1-40e04f69f98e.JPG)
![Screen Shot 03-29-20 at 07 35 PM](https://user-images.githubusercontent.com/62701156/77856031-be7c5680-71f4-11ea-868d-0a4a0531ed86.JPG)

**Comment by DasFantatier** [comment]
This issue got closed without information about the issue - please write back - thank you

**Comment by MrCrayfish** [comment]
1.15.2 version is in development

**Comment by DasFantatier** [comment]
@MrCrayfish thanks for the reply!

It would be nice if such informations would be mentioned in the version description, it saves time for you too :)

Thank you!

**Comment by Natetdw-labs** [comment]
Has 1.15.2 development stopped? I'm making a city and managed to realize there are no fans, light switches, ceiling lights, TVs, Computers, Printers, and a lot of other stuff.

**Comment by Tiff256** [comment]
I have the same problem, when is development going to be finished on the items?

**Comment by TerranceAfton** [comment]
it's still missing with this 1.19.3 version as well. I'm building the Afton house and theres no tvs or any bathroom stuff except for sinks. when is that stuff being added back?
