### ISSUE TITLE
[1.14.4] (Random?) Recipe incompatibilities with Quark

### ISSUE THREAD

**Issue by shimmer-n-shine** [MrCrayfish/MrCrayfishFurnitureMod#554]
**Describe the bug**
When using [Quark](https://www.curseforge.com/minecraft/mc-mods/quark), the recipe for Stripped Bedside Cabinets is uncraftable for the stripped oak and birch bedside cabinets.  Quark adds a recipe to craft 4 chests using logs, which conflicts with (strangely, only) the oak and birch varieties. The issue does not extend to non-stripped logs. I do not know if the issue extends to the acacia or jungle varieties as I did not have any in my survival world.

**Screenshots**
![GIF 01](https://user-images.githubusercontent.com/22829358/78486595-4b289680-7758-11ea-8bda-cb46d385a8f3.gif)
![GIF 02](https://user-images.githubusercontent.com/22829358/78488178-bc684980-7758-11ea-84b4-48b673a2e4ed.gif)
![Screenshot 01](https://i.imgur.com/GPC1fLR.png)
![Screenshot 02](https://i.imgur.com/Pz5kgAg.png)
![Screenshot 03](https://i.imgur.com/yCiyOD5.png)
![Screenshot 04](https://i.imgur.com/AloWfon.png)

Please complete the following information:
- Minecraft Version: 1.14.4
- Mod Version: 7.0.0

**Comment by MrCrayfish** [comment]
Nothing I can do! You'll have to write yourself a datapack that changes the recipes.

**Comment by moll** [comment]
Hey,

I stumbled upon the same issue in v1.15.2 and the latest Furniture Mod version. Looking at some other mods, they seem to accept "forge:chests/wooden" instead of the core "Chest". Could this be a way to make the furniture recipes compatible with Quark et alii, @MrCrayfish?
