### ISSUE TITLE
[1.15.2] Texture changes when placing carpet on kitchen blocks

### ISSUE THREAD

**Issue by DasFantatier** [MrCrayfish/MrCrayfishFurnitureMod#555]
**Describe the bug**
I like to place carpets on the kitchen drawers, so it looks like a surface to work on it. 
When i put a carpet on it, the texture is changing, the knobs are not good to see any more.
On the screenshots you can see a placed vanilla carpet and a wood carpet from the mod "carpet stairs mod", - no matter which carpet i choose and which drawer, the issue stays the same.

**Crash report**
There is no crash

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place any kitchen drawer
2. place carpet on it
3. watch the front

**Screenshots**
![2020-04-05_18 07 59](https://user-images.githubusercontent.com/62701156/78503760-ecb7e400-7768-11ea-85bb-e31962f795ee.png)
![2020-04-05_18 08 34](https://user-images.githubusercontent.com/62701156/78503766-f04b6b00-7768-11ea-9535-c49ec198c666.png)

Please complete the following information:
- Minecraft Version: 1.15.2
- Mod Version: furniture-7.0.0-pre16-1.15.1.jar
- Forge 31.1.0

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/c4c7030e2de63386df5ddcb7a477e27c7f0cdafc
