### ISSUE TITLE
[1.15.2 Suggestion] Allow sink to fill water bottles

### ISSUE THREAD

**Issue by ocram9** [MrCrayfish/MrCrayfishFurnitureMod#562]
I think it would be useful to allow a sink to fill water bottles. We would basically have a nicer looking cauldron which you could easer fit into a build.

**Comment by MrCrayfish** [comment]
Added in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/72d83d3cb1ee818b28a051e28f261db57ef9c896
