### ISSUE TITLE
[1.15.2] A lot of items are missing

### ISSUE THREAD

**Issue by rogeriodec** [MrCrayfish/MrCrayfishFurnitureMod#565]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11199752/80260654-be8a3d80-865e-11ea-8e89-6d35ea8fec25.png)

That's the current mod version for Minecraft 1.15.2, however, I can't find a lot of items that should be there.

What's wrong?

**Comment by MrCrayfish** [comment]
Mod is still in development hence "pre"
