### ISSUE TITLE
[1.14.4] Mod Version Problem

### ISSUE THREAD

**Issue by gigiovanna** [MrCrayfish/MrCrayfishFurnitureMod#571]
**Absence of items**
I played the game with this mod in 1.12.2 version, and i had frigde, oven, modern door, lamps and the light switch. 
But now that I had updated to the 1.14.4 version and downloaded the mod for this version, it doesn't have nothing of this, just the basic furniture. I want the modern itens :( 
The modern itens are just for the 1.12.2 version? 

- Minecraft Version: 1.14.4 
- Mod Version: I tested all the 1.14.4 mod versions and none of them have the items.

**Comment by alex-vance** [comment]
+1 for 1.15.x
