### ISSUE TITLE
[1.15.2] Graphics bug with Crates

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishFurnitureMod#575]
**Describe the bug**
Xray glitch with crates opened when they are flush with other blocks in height

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1.Place crate in floor
2. open crate
3. See error

**Screenshots**
![2020-05-23_18 39 06](https://user-images.githubusercontent.com/62222154/82742543-411d2000-9d25-11ea-81c1-a4455764ac2f.png)

Please complete the following information:
- Minecraft Version: 1.15.2
- Mod Version:7.0.0pre-16

**Comment by shinyyraichu** [comment]
I have this as well. Occurs while crate lid is open.
Minecraft 1.16.1
Forge 32.0.108
Version 7.0.0-pre18-1.16.1
![crate glitch](https://user-images.githubusercontent.com/44959919/90061754-94639680-dcb4-11ea-9493-19c20826491f.png)
