### ISSUE TITLE
[1.12.2] Conflict with Futurepack mod

### ISSUE THREAD

**Issue by Nidero** [MrCrayfish/MrCrayfishFurnitureMod#577]
**Describe the bug**
MrCrayfishFurnitureMod installed with Futurepack will cause minecraft to fail to start

**Crash report**
This is crash report：https://paste.ubuntu.com/p/hN927PXdbM/

Please complete the following information:
- Minecraft Version:1.12.2
- Mod Version: FurnitureMod 6.3.1 Futurepack 26.4.89

**Comment by Art1xs** [comment]
I have this too
