### ISSUE TITLE
[1.12.2] Game crashes when I look at mirror

### ISSUE THREAD

**Issue by dangoi5** [MrCrayfish/MrCrayfishFurnitureMod#584]
**Describe the bug**
Whenever I look at the mirror it straight up crashes my game. I think its something to do with obfuscate.

**Crash report**
https://pastebin.com/5e8iW6d5
**To Reproduce**
If applicable, the steps to reproduce the behavior:

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: Furniture Mod version 6.3.1
                        Obfuscate version 0.4.2
![Badlion Client Screenshot 2020 06 24 - 16 45 34 50](https://user-images.githubusercontent.com/67239411/85626250-bf2d5900-b63a-11ea-8c7f-10f45540ca97.png)

**Comment by UnclassifiedX** [comment]
Update your forge version, that'll fix it.

**Comment by dangoi5** [comment]
> Update your forge version, that'll fix it.

I updated it to the latest version and its still happening, it doesn't crash my game but if I look at it, it freezes my screen with like some black bars
![Badlion Client Screenshot 2020 06 24 - 16 45 34 50](https://user-images.githubusercontent.com/67239411/85626230-b63c8780-b63a-11ea-8fa4-b5eb84635ce6.png)
