### ISSUE TITLE
[1.15.1] Only certain items show up. No bathroom furniture at all.

### ISSUE THREAD

**Issue by those21phandoms** [MrCrayfish/MrCrayfishFurnitureMod#587]
**Describe the bug**
When I'm in creative and looking at the furniture menu, the only furniture that shows up is tables, coffee tables, cabinets, bedside cabinets, chairs, counters, sofa, blinds, fences, desks, gates, crates, bench, mailbox, trampoline, cooler, grill, doormat, diving board, postbox, rock path, bushes, and sinks. The bathroom section doesn't even show up in the menu and when I go to the item category, only the spatula shows up.

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. I downloaded and installed mc forge 1.15.2 (I also deleted it and downloaded 1.15.1 to see if the mod would work better, it didn't)
2.  I then downloaded your furniture mod version 1.15.1
3.  Started up Minecraft and created a new world to try the mod out. I went to inventory and went to the second page of it to view your mod's objects. I then noticed that a lot of the items in the mod screenshots were missing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67725794/86318876-b8818180-bbf8-11ea-940f-ffb7ee2084dc.png)
![image](https://user-images.githubusercontent.com/67725794/86318905-c8996100-bbf8-11ea-8974-513b8e08c8e8.png)
![image](https://user-images.githubusercontent.com/67725794/86318920-d5b65000-bbf8-11ea-94e9-89cb7f88dfec.png)
![image](https://user-images.githubusercontent.com/67725794/86318948-e1097b80-bbf8-11ea-8fa8-a21171722786.png)
![image](https://user-images.githubusercontent.com/67725794/86318966-ec5ca700-bbf8-11ea-97bf-985d02558d31.png)
![image](https://user-images.githubusercontent.com/67725794/86318979-f4b4e200-bbf8-11ea-8745-03f0915cc269.png)
![image](https://user-images.githubusercontent.com/67725794/86318990-fb435980-bbf8-11ea-899e-ce05b310fd87.png)
![image](https://user-images.githubusercontent.com/67725794/86318996-01d1d100-bbf9-11ea-97f0-441e0f2aad50.png)
![image](https://user-images.githubusercontent.com/67725794/86319009-09917580-bbf9-11ea-98d6-74ccb491c481.png)

Please complete the following information:
- Minecraft Version: 1.15.1 and 1.15.2
- Mod Version: 1.15.1

**Comment by Orkidea16** [comment]
I have the exact same problem, no dishwasher, refrigerator, oven, microwave, bathroom furniture, etc
My forge version is 31.2.0
Minecraft 1.15.2
And the mod version is 7.0.0 pre 16 1.15.1

**Comment by Ocelot5836** [comment]
Most furniture has not yet been added to 1.15

**Comment by TheFireSkorpion** [comment]
Same in 1.16.5 When I'm in creative and looking at the furniture menu, the only furniture that shows up is tables, coffee tables, cabinets, bedside cabinets, chairs, counters, sofa, blinds, fences, desks, gates, crates, bench, mailbox, trampoline, cooler, grill, doormat, diving board, postbox, rock path, bushes, and sinks. The bathroom section doesn't even show up in the menu and when I go to the item category, only the spatula shows up.
There is also a good part of the kitchen elements missing, the dryer, the TV and many other things like that.
