### ISSUE TITLE
Minecraft v 1.14.4 crashes after it says it's freezing data? So before launch. 

### ISSUE THREAD

**Issue by cravingmay** [MrCrayfish/MrCrayfishFurnitureMod#591]
**Describe the bug**
Every time I put mod in mods folder, open the launcher and try to launch minecraft with forge It loads up until the "freezing data" then it freezes for a while and then eventually just crashes. If there's a crash report I don't see it because it just takes me back to the launcher. I was so excited to see this mod and use it! I hope someone can help me.

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here. 

no crash report :(

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Go to '...' Minecraft launcher 
2. Click on '....' play with forge 1.14.4 
3. screen freezes. 
4.  taken back to launcher

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.14.4
- Mod Version: cfm-7.0.0-pre15-mc1.14.4.jar

**Comment by MrCrayfish** [comment]
Uninstall Optifine

**Comment by cravingmay** [comment]
Does this mean it’s not at all compatible with optifine? Or just my version
of it

**Comment by Ocelot5836** [comment]
Can you send the latest.log? It should be in .minecraft/logs/latest.log?
