### ISSUE TITLE
{Minecraft 1.15 A Furniture Mod 7.0.0-pre16]  this 1.15 version says pre 1.16 so i thought it would work with 1.16 it didn't  so can you make a version that works with 1.16 please i love your mod but i want to play with 1.16

### ISSUE THREAD

**Issue by chloegoesboom** [MrCrayfish/MrCrayfishFurnitureMod#595]
**Describe the bug**

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version:
- Mod Version:

**Comment by Ocelot5836** [comment]
1.16 is not compatible with 1.15

**Comment by MrCrayfish** [comment]
pre16 is a development versioning, not mc version. If it was for 1.16.1 it would explicitly say it from where you download it.
