### ISSUE TITLE
Actions do not work for one player account only (not PC dependent)

### ISSUE THREAD

**Issue by ejayjock** [MrCrayfish/MrCrayfishFurnitureMod#599]
I have installed the MrCrayFish furniture Mods on a private multiplayer server, and 6 user PCs. The mod functions as expected for all users except one. For this one user the "shift-Right Click" action does not work with the object generated in the world - for example the blender will not blend, or the toaster will not toast.

The strange thing about the situation is the non-functioning "shift-Right Click" is specific only to one player account and not specific to a single PC. It does not matter which PC she is logged into, the action does not work. Likewise, other users can log onto her PC and the mod works as expected.

Any suggestions would be very much appreciated.

**Comment by Tsoccerguy3** [comment]
This player may have custom key assignments in Minecraft or a foreign keyboard , try to set to default

**Comment by MrCrayfish** [comment]
I highly doubt this is an account issue. To describe the action required, you need to sneak and right click. Sneak could be a key binding they have changed.

**Comment by ejayjock** [comment]
Thanks you for the fast responses!

Update: The issue resolved on its own for the user today. For the record I will replay to the to comments above.

>  This player may have custom key assignments in Minecraft or a foreign keyboard , try to set to default
The issue followed the same user across different three different PCs - all with completely different hardware, all with US keyboards. So I don't believe it was a Keyboard issue. I did look through the key mapping to make sure there was nothing strange there, they were all defaults.

> I highly doubt this is an account issue. To describe the action required, you need to sneak and right click. Sneak could be a key binding they have changed.
I share you skepticism and if I didn't recreate the issue myself I would not have believed it. After producing the behavior on multiple PCs for just the one user yesterday, it started working this morning.

Very strange.

Thanks for all of the hard work on the mod.  The people who play on my server love it.
