### ISSUE TITLE
New blocks

### ISSUE THREAD

**Issue by RackieW** [MrCrayfish/MrCrayfishFurnitureMod#60]
Not a bug but the new blocks(like cooler, grill and diving board) destroyes instantly in survival.

And if you use an inventory editor (tmi,nei,jei...) you will find a lot of stuff :)
Like item.item_crayfish.name and item.item_money.name, a very small chrismas tree and (probably some sort of easter egg) the Rave Couch(Rainbow Couch)

**Comment by sudo-apt-get-install** [comment]
Those are secret items

**Comment by MrCrayfish** [comment]
Fixed blocks breaking instantly in ce5dd1c63c783e32f10b57f06e3a1652c0c329e9
