### ISSUE TITLE
[1.16.1] newest forge not combitable

### ISSUE THREAD

**Issue by ZEROX7** [MrCrayfish/MrCrayfishFurnitureMod#600]
**Describe the bug**
cant load on nesest forge method public static void

**Crash report**
https://1drv.ms/u/s!AoGi5ELkm7SZoVK4KmkYYYWFBDQg?e=fJhNOR

- Minecraft Version: 1.16.1
- Mod Version: 7.0.0-ptr17

**Comment by Ocelot5836** [comment]
Remove Immersive Engineering

**Comment by ZEROX7** [comment]
wrong log https://pastebin.com/yzTZCVeg

**Comment by Ocelot5836** [comment]
Use forge 1.16.1-32.0.93

**Comment by ZEROX7** [comment]
well other mods need newer one would be nice if you could fix the error, i know how frustraded modding atm is for 1.16.1 because how frequently forge changes things

**Comment by Ocelot5836** [comment]
Forge made a breaking change and the mod has yet to update.
