### ISSUE TITLE
[1.12.2] 

### ISSUE THREAD

**Issue by jotkauser** [MrCrayfish/MrCrayfishFurnitureMod#601]
About This bug
Im Playing on pixelmon with cfm

**Screenshots**
![image](https://user-images.githubusercontent.com/56410520/89125679-6de97280-d4e0-11ea-80f1-66cfd4805bd0.png)

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by MrCrayfish** [comment]
Just switch to a different creative tab. I can't add a patch for every mod that renders in the creative GUI
