### ISSUE TITLE
Stone variations of Furniture don't drop even when using a pickaxe

### ISSUE THREAD

**Issue by lizterr** [MrCrayfish/MrCrayfishFurnitureMod#602]
Stone variants don't drop. Whenever you try to break it, it will not drop, even when you're using a pickaxe. Pickaxes also don't increase the mining speed on stone furniture making it a hassle to break.

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/499
