### ISSUE TITLE
[1.16.1 Version] Missing Mod Items

### ISSUE THREAD

**Issue by SimpNotSimping** [MrCrayfish/MrCrayfishFurnitureMod#604]
Newer mod items and some of the older ones don't appear in the 1.16.1 version. 
Items including but not limited to every Kitchen appliance (not including the fridge), electronics, and bathroom equipment (excluding the sink).

Essentially if you download mod posted and look up names such as 'blender' or 'computer' in 1.16.1 you'll find such items missing.

- Minecraft Version: 1.16.1
- Mod Version: 1.16.1

**Comment by Ocelot5836** [comment]
Most furniture has not been implemented yet.
