### ISSUE TITLE
[1.12.2] HashMap crash related to CFM mod

### ISSUE THREAD

**Issue by RisingInIris2017** [MrCrayfish/MrCrayfishFurnitureMod#606]
**Describe the bug**
Game had been successfully started, and been played for a while.
But it crashed suddenly.

**Crash report**
https://pastebin.com/UmcfnP8r

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by ghost** [comment]
This can be fixed by using a concurrent hash map and simply taking out all the explicit synchronization. It's part of the PR I've created: #608
