### ISSUE TITLE
Missing Furniture (1.15.1)

### ISSUE THREAD

**Issue by CM357** [MrCrayfish/MrCrayfishFurnitureMod#609]
I Have Downloaded Your Furniture Mod And It Seems To Be Working But, It's Missing A lot Of Furniture Items. Do You Know Of Any Way To Fix This Or Why This Is Happening? Can You Please Get Back To Me On This? Thanks.

**Comment by scratchysmiles03** [comment]
the same thing is happening to me, just 1.16.1 version. i don't know if it's something i did wrong or if it's a bug

**Comment by MrCrayfish** [comment]
The mod is not fully ported...
