### ISSUE TITLE
Error loading mod: "needs language provider javafml:32 or above to load"

### ISSUE THREAD

**Issue by bpeabody** [MrCrayfish/MrCrayfishFurnitureMod#610]
I'm trying to get this installed for my daughter. Using forge 1.15.2 (have tried a few other versions too). Any ideas?

Thanks in advance!
Brock

**Comment by MrCrayfish** [comment]
You've downloaded the 1.16 version, not the 1.15. version.

**Comment by bpeabody** [comment]
Thanks so much!
