### ISSUE TITLE
Data pack with custom grill recipes don't appear to work

### ISSUE THREAD

**Issue by djmattyg007** [MrCrayfish/MrCrayfishFurnitureMod#615]
Using this file for inspiration:

https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/1.15.X/src/main/resources/data/cfm/recipes/cooked_potato_from_grill_cooking.json

I created a datapack with the following recipe for the Aquaculture fish fillet:

```
{
    "type": "cfm:grill_cooking",
    "ingredient": {
        "item": "aquaculture:fish_fillet_raw"
    },
    "result": {
        "item": "aquaculture:fish_fillet_cooked"
    },
    "experience": 4.0,
    "cookingtime": 600
}
```

But it doesn't appear to have done anything. Am I missing something?

**Comment by MrCrayfish** [comment]
After testing, it's seems it's working as normal.
Test Pack: [Test.zip](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/6630137/Test.zip)

![image](https://user-images.githubusercontent.com/4958241/121502078-fac55c80-ca1e-11eb-891a-f9bb7e079abb.png)
![image](https://user-images.githubusercontent.com/4958241/121502229-20526600-ca1f-11eb-958e-f33a7d3ef51a.png)
