### ISSUE TITLE
1.16.2 Forge crashes when loading the mod due to need for license

### ISSUE THREAD

**Issue by joerawr** [MrCrayfish/MrCrayfishFurnitureMod#616]
**Minecraft Forge crashes when loading the mod due to need for license**

1.16.2+ crashed when trying to load mod.

Since 1.16.1-32.0.90 a license is required in mods.toml
`	cpw:
		Update coremods and spi, include mandatory license field in metadata. Added at top level of mods.toml file.`

http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.1-32.0.90/forge-1.16.1-32.0.90-changelog.txt

**Crash report**
`Exception in thread "main" [23:16:27] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing License, please supply a license. (cfm-7.0.0-pre18-mc1.16.1.jar)`

**To Reproduce**
1. Install latest forge, eg: forge-1.16.2-33.0.22
2. Run installer, accept eula, copy mod to mods folder
3. java -jar forge-1.16.2-33.0.22.jar nogui
4. Crashes with the above error.

Please complete the following information:
- Minecraft Version:   forge-1.16.2-33.0.22
- Mod Version: cfm-7.0.0-pre18-mc1.16.1.jar  (Downloaded from https://mrcrayfish.com/mods?id=cfm, today's date)

Two more issues discussing it:
https://github.com/MinecraftForge/MinecraftForge/issues/7247
https://github.com/MinecraftForge/MinecraftForge/issues/7184

https://twitter.com/voxcpw/status/1287856575084994561

Rolling back to 1.16.1-32.0.88 didn't work either, with this error:
```

[[main/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §ecfm§r requires §6forge§r §o32.0.97 or above§r
§7Currently, §6forge§r§7 is §o32.0.88]
```

**Comment by MrCrayfish** [comment]
This is simply a side effect because the mod isn't built for 1.16.2 yet, only 1.16.1. Thanks for the report though, it will be fixed soon.

**Comment by joerawr** [comment]
Thanks.  I did get it working on current 1.16.1.  However the kids couldn't find the beds, so they went back to 1.12.  They're happy.

**Comment by simonjonnemeth** [comment]
How soon is soon? I know there has been some major headaches with worldgen mods but other mods like this that simply add items were updated pretty quickly.

**Comment by MokahTGS** [comment]
Can this be updated for 1.16.3 as well?

**Comment by vsvetoslavov** [comment]
Anyone willing to play this mod on 1.16.2 can just open the .jar file with any zip tool that allows editing and add the license field manually to the top part of the mods.toml file (located in the META-INF folder). It's a quoted plain text field, so the following will do:
license="All rights reserved"
But you can type in there whatever you want - mine says "power overwhelming" :)
