### ISSUE TITLE
missing a lot of items 

### ISSUE THREAD

**Issue by TheWeepingDalek** [MrCrayfish/MrCrayfishFurnitureMod#617]
ive checked everything i could i cant seem to find a lot of items in 1.16 including the fridge, toaster, blender and lamps and many more. im not the only one having this problem my gf is experiencing the same thing.

**Comment by 1bananana1** [comment]
im getting the same issue, where i only have access to half the items that are meant to be there

**Comment by MrCrayfish** [comment]
This is not an issue, the mod is getting reworked.
