### ISSUE TITLE
Issue with server and custom receipe for Minebay

### ISSUE THREAD

**Issue by Frogger60** [MrCrayfish/MrCrayfishFurnitureMod#618]
Hey all, not sure if this is the right place to add this, but my buddies and I are running a server that we have added a number of mods. I have been fiddling with adding custom items to MrCrayfish's Minebay on the crafted computer. I run all of my testing in SP and then send it over to my friend to add to the server. We have run into an issue where a reference is not being read by the server correctly in cfm.cfg. Under custom recipes I have the following lines:

`type=microwave,input-item=openblocks:sponge,output-item=minecraft:sponge
type=minebay,input-item=minecraft:emerald,payment-item=ic2:crafting,payment-metadata=38,payment-price=8
type=minebay,input-item=ic2:crafting,input-metadata=38,input-amount=8,payment-item=minecraft:emerald,payment-price=1
type=minebay,input-item=minecraft:sponge,payment-item=minecraft:emerald,payment-price=2
type=minebay,input-item=minecraft:blaze_rod,payment-item=minecraft:emerald,payment-price=2
type=minebay,input-item=minecraft:mob_spawner,payment-item=minecraft:emerald_block,payment-price=3
type=minebay,input-item=ic2:misc_resource,input-metadata=2,payment-item=minecraft:emerald,payment-price=4
type=minebay,input-item=tconstruct:edible,input-metadata=2,input-amount=4,payment-item=minecraft:emerald,payment-price=1
type=minebay,input-item=minecraft:emerald,input-amount=2,payment-item=minecraft:carrot,payment-price=16`

In SP everything works as intended, however once added to the server, the second line bugs out

`type=minebay,input-item=minecraft:emerald,payment-item=ic2:crafting,payment-metadata=38,payment-price=8`

It ignores the "payment-metadata=38" part of the code, causing it to select rubber from IC2, instead of credit from IC2. I do not understand what could be causing it to ignore the metadata on the server, but work in SP

**Comment by MrCrayfish** [comment]
Unfortunately I won't be making any improvements to the API on 1.12.2. It was horribly designed and I was unexperienced when I created it. It's a giant mess I don't want to touch. Sorry about that.
