### ISSUE TITLE
Bucket be gone! (1.16.1)

### ISSUE THREAD

**Issue by P4ZLE** [MrCrayfish/MrCrayfishFurnitureMod#620]
The bucket disappears in the fridge. I get 2 ice, but no bucket is returned. I do not remember this happening in the 1.12 version. Is this a bug?

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/8ecbf1390c29886d327d71c2da2a2b0b195662d9
