### ISSUE TITLE
[1.12.2] Multi-Block Furniture not rotating as a single piece

### ISSUE THREAD

**Issue by tomodachi94** [MrCrayfish/MrCrayfishFurnitureMod#626]
**Describe the bug**
Using Thermal Expansion’s Crescent Hammer (a tool that can ‘dismantle’ and rotate blocks), when I rotate the upper or lower “block” parts, it rotates half of the door but not the other half!

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

- Minecraft Version: 1.12.2

**Comment by MrCrayfish** [comment]
Not all mods are compatible like that... I can't fix this "bug" because it's only introduced because of the tool from that mod.
