### ISSUE TITLE
[1.16.3] some items that are supposed to be in the mod dont show up in creative

### ISSUE THREAD

**Issue by jessboop** [MrCrayfish/MrCrayfishFurnitureMod#631]
when i downloaded the mod i was kinda confused because i thought there was supposed to be a lot more items in it. the only things that show up are tables, chairs, sofas, fences, cabinets, counters, diving board, outdoor mat, mailboxes, rock path, and a spatula. how do i get the bathroom and all the other stuff to show up?

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.16.3
- Mod Version: 1.16.3

**Comment by LorenzoPapi** [comment]
The mod is being rewritten, lots of items and blocks aren't in new versions. Please close this issue
