### ISSUE TITLE
Sofa bug

### ISSUE THREAD

**Issue by scottycool64** [MrCrayfish/MrCrayfishFurnitureMod#634]
my game crashes when i try to use a sticky piston on a sofa
edit: my safe is now bricked help
p.s. i was trying to make a secret hatch, so i put a sofa on an extended sticky piston which is then flush on the wall. i retracted and now my save is bricked help please

**Comment by MrCrayfish** [comment]
I'll need a crash report. Not much I can do to help

**Comment by scottycool64** [comment]
> I'll need a crash report. Not much I can do to help

Thankfully it was a test world, though it will be helpful to have the bug fixed. No rush on it. I think the reason it got bricked is because the sofa was constantly trying to load in the middle of an 3x3 square

**Comment by MrCrayfish** [comment]
I can't reproduce the issue. I'd need a crash log if you want help. I'll reopen if you send a log.
