### ISSUE TITLE
[1.15.2] Sofas Don't Drop when Broken

### ISSUE THREAD

**Issue by sammie-qt** [MrCrayfish/MrCrayfishFurnitureMod#637]
Sofas don't drop the item when broken with a tool or hand, they simply vanish.

To reproduce: just place down a sofa (I was using Cyan, but also tested with White, Orange, and Red) and attempt to break it in survival mode.

Please complete the following information:
- Minecraft Version: 1.15.2
- Mod Version: 7.0.0-pre16

**Comment by MrCrayfish** [comment]
Unfortunately it's unlikely that the 1.15.2 version will receive more updates. This has been fixed in 1.16 version though.
