### ISSUE TITLE
[1.16.4] Bad local variable type

### ISSUE THREAD

**Issue by tajemniktv** [MrCrayfish/MrCrayfishFurnitureMod#641]
**Describe the bug**
Well, what can I say - crashreport is here. It dosn't happen when Obfuscate, Furniture and Vehicles aren't present. 

**Crash report**
[pastebin](https://pastebin.com/RqNLqzeE)

Please complete the following information:
- Minecraft Version: 1.16.4
- Mod Version: Everything latest at the time of writing

**Comment by jacksonhardaway** [comment]
Remove Optifine.

**Comment by tajemniktv** [comment]
> Remove Optifine.

Well, as much as I'd like to, there's no real alternative or at least I'm not aware of any - OF gives tremendous amout of settings and a huge performance boost :/

**Comment by jacksonhardaway** [comment]
Optifine in any version 1.13+ does not give any real performance boost, it just renders less chunks. If you want the same performance boost Optifine gives then lower your render distance.

Removing it is the only way to fix this issue as it's an incompatibility between the two

**Comment by MrCrayfish** [comment]
This is an Obfuscate mod issue, not the Furniture Mod. I am going to take a look into it soon.
