### ISSUE TITLE
does not show in curseforge launcher

### ISSUE THREAD

**Issue by ZoruaBit** [MrCrayfish/MrCrayfishFurnitureMod#642]
While 1.16.4 does work it does not show up in the curse forge launcher forsing us to drop it in ourselves
![image](https://user-images.githubusercontent.com/39221658/103031946-78a2b380-4524-11eb-91a6-c7df4a35bbde.png)

**Comment by MrCrayfish** [comment]
Alpha versions aren't displayed.

**Comment by ZoruaBit** [comment]
![image](https://user-images.githubusercontent.com/39221658/103424611-f2fdb400-4b72-11eb-98ad-fbb82e107e63.png)

probelm alpha versons ARE displayed. im asking you to add 1.16.4 to this 
![image](https://user-images.githubusercontent.com/39221658/103424598-d6fa1280-4b72-11eb-871b-9971386202fe.png) so it does show in the curseforge launcher

**Comment by MrCrayfish** [comment]
Fixed!
