### ISSUE TITLE
[1.16.4] A lot of furniture not showing up within JEI or Creative Inventory

### ISSUE THREAD

**Issue by Thisis-Casey** [MrCrayfish/MrCrayfishFurnitureMod#644]
So I downloaded the latest version from the official MrCrayfish.com website along with the Obfuscate mod just incase, and in singleplayer and multiplayer on a friends server, there is not as much furniture as it seems like there should be, I'm not sure what the issue is but hopefully, someone will be able to assist me with it.

- Minecraft Version: 1.16.4
- Mod Version: 7.0.0-pre19-1.16.3

**Comment by MrCrayfish** [comment]
It's no surprise. The furniture mod is being updated and not all furniture has been added back yet.
