### ISSUE TITLE
1.12.2 Duplication Glitch

### ISSUE THREAD

**Issue by Ashley123477** [MrCrayfish/MrCrayfishFurnitureMod#650]
Duplicate buckets via the washing machine

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Craft a bucket of soap via soap and a water bucket this will give you an empty bucket back
2. put the bucket of soap in the washing machine with any old armour piece
3. start the washing machine which will turn the soap bucket into an empty bucket leaving you with 2 buckets
4. Profit

- Minecraft Version: 1.12.2
- Mod Version: furniture-6.3.1-1.12.2

**Comment by Largosaki** [comment]
This problem can be easily solved by rebuilding the formula,
if you have the CraftTweaker installed,
Use the following to remove the original recipe and rebuild:
recipes.removeByRecipeName("cfm:item_soap_water");

**Comment by Ashley123477** [comment]
This fix does work until Crayfish updates and fixes

**Comment by Largosaki** [comment]
Yes, this is a quick temporary solution
