### ISSUE TITLE
[1.12.2] Furniture Computer GUI crash

### ISSUE THREAD

**Issue by winterSteve25** [MrCrayfish/MrCrayfishFurnitureMod#653]
**Describe the bug**
Crash when right click on the computer

**Crash report**
https://pastebin.com/JnJtki4s

**To Reproduce**
1. Place down the MrCrayFish Furniture mod computer
2. Right cilck it

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by 2ec0nd** [comment]
Crash when right click on the computer

https://pastebin.com/7sDFRwYi

minecraft version: 1.12.2
mod version: 6.3.0

help pls :<
