### ISSUE TITLE
[1.16.3] nothing shows

### ISSUE THREAD

**Issue by Sky506-afk** [MrCrayfish/MrCrayfishFurnitureMod#656]
so, half the stuff isnt in the game, like all the working items, like the bath shower tv blender ect

no crash

it just isnt there

1.16.3
furniture-7.0.0-pre19-1.16.3.jar

**Comment by animako** [comment]
Bump

**Comment by Ocelot5836** [comment]
Most of the furniture from 1.12 hasn't been implemented into 1.13+
