### ISSUE TITLE
Interaction crash

### ISSUE THREAD

**Issue by StatiK404** [MrCrayfish/MrCrayfishFurnitureMod#657]
alright so i made a good house in minecraft creative. i wanted to decorate it. i thought lanterns arent good enough so i used "modern lights". i placed them.Then after right clicking with the light switch it crashed the game.I wanted to turn on the shower but it crashed again!Every single interaction crashes the game!

**Comment by MrCrayfish** [comment]
Can you send a crash log?

**Comment by StatiK404** [comment]
> Can you send a crash log?

--- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_20.16.0.2_Forge_1.12.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 2/4/21 4:57 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to up on block cfm:wall_cabinet, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:235)
	at com.mrcrayfish.furniture.blocks.BlockWallCabinet.func_180642_a(BlockWallCabinet.java:109)
	at net.minecraft.block.Block.getStateForPlacement(Block.java:2273)
	at team.cqr.cqrepoured.structureprot.ProtectedRegionHelper.getBlockFromItem(ProtectedRegionHelper.java:192)
	at team.cqr.cqrepoured.structureprot.ProtectedRegionEventHandler.onRightClickBlockEvent(ProtectedRegionEventHandler.java:222)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_ProtectedRegionEventHandler_onRightClickBlockEvent_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:235)
	at com.mrcrayfish.furniture.blocks.BlockWallCabinet.func_180642_a(BlockWallCabinet.java:109)
	at net.minecraft.block.Block.getStateForPlacement(Block.java:2273)
	at team.cqr.cqrepoured.structureprot.ProtectedRegionHelper.getBlockFromItem(ProtectedRegionHelper.java:192)
	at team.cqr.cqrepoured.structureprot.ProtectedRegionEventHandler.onRightClickBlockEvent(ProtectedRegionEventHandler.java:222)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_ProtectedRegionEventHandler_onRightClickBlockEvent_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['StatiK_404'/206, l='MpServer', x=460.36, y=69.06, z=306.64]]
	Chunk stats: MultiplayerChunkCache: 729, 729
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (557,4,289), Chunk: (at 13,0,1 in 34,18; contains blocks 544,0,288 to 559,255,303), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 91820 game time, 91820 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityPlayerSP['StatiK_404'/206, l='MpServer', x=460.36, y=69.06, z=306.64], EntityLatchedRenderer['unknown'/358, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/358, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1589274336 bytes (1515 MB) / 3992977408 bytes (3808 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version               | Source                                        | Signature                                |
	|:------ |:--------------------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                               | 9.42                  | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                               | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core                 | 1.12.2-1.0            | minecraft.jar                                 | None                                     |
	| LCHIJA | obfuscate                         | 0.4.2                 | minecraft.jar                                 | None                                     |
	| LCHIJA | securitycraft                     | v1.8.20.2             | [1.12.2]+SecurityCraft+v1.8.20.2.jar          | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCHIJA | chameleon                         | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHIJA | chiselsandbits                    | 14.33                 | chiselsandbits-14.33.jar                      | None                                     |
	| LCHIJA | jei                               | 4.15.0.296            | jei_1.12.2-4.15.0.296.jar                     | None                                     |
	| LCHIJA | cqrepoured                        | 2.2.3B                | Chocolate_Quest_Repoured-1.12.2-2.2.3B.jar    | None                                     |
	| LCHIJA | classicbar                        | @VERSION@             | classicbar-0.5.4.jar                          | None                                     |
	| LCHIJA | clumps                            | 3.1.2                 | Clumps-3.1.2.jar                              | None                                     |
	| LCHIJA | corona                            | 1.0.0                 | CoronaMask-1.12.2-v1.jar                      | None                                     |
	| LCHIJA | cosmeticarmorreworked             | 1.12.2-v5a            | CosmeticArmorReworked-1.12.2-v5a.jar          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | csb                               | 1.4.5                 | CustomSelectionBox-1.12.2-1.4.6.jar           | None                                     |
	| LCHIJA | cdm                               | 0.4.1                 | device-mod-0.4.1-1.12.2.jar                   | None                                     |
	| LCHIJA | elenaidodge                       | 1.13.0                | ElenaiDodge-1.12.2-1.13.0.jar                 | None                                     |
	| LCHIJA | elevatorid                        | 1.3.14                | ElevatorMod-1.12.2-1.3.14.jar                 | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76         | EnderCore-1.12.2-0.5.76.jar                   | None                                     |
	| LCHIJA | enderio                           | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | enderiobase                       | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | enderioconduits                   | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183     | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | enderiomachines                   | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | enderiopowertools                 | 5.2.59                | EnderIO-1.12.2-5.2.59.jar                     | None                                     |
	| LCHIJA | mod_lavacow                       | 1.2.3                 | Fish's+Undead+Rising-1.2.3.jar                | None                                     |
	| LCHIJA | cfm                               | 6.3.1                 | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCHIJA | historicizedmedicine              | 1.12.2a               | historicizedmedicine-1.3.9.5.jar              | None                                     |
	| LCHIJA | ichunutil                         | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | inventoryhud                      | 3.1.8                 | InventoryHud_1.12.2.forge-3.1.9.jar           | None                                     |
	| LCHIJA | inventorypets                     | 2.0.6                 | inventorypets-1.12-2.0.6.jar                  | None                                     |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | ironfurnaces                      | 1.3.5                 | ironfurnaces-1.3.5.jar                        | None                                     |
	| LCHIJA | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJA | malisisdoors                      | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCHIJA | mcwbridges                        | 1.0.4                 | mcw-bridges-1.0.4-mc1.12.2.jar                | None                                     |
	| LCHIJA | mcwdoors                          | 1.0                   | mcw-doors-1.0.0-mc1.12.2.jar                  | None                                     |
	| LCHIJA | mcwfurnitures                     | 1.0.1                 | mcw-furniture-1.0.1-mc1.12.2beta.jar          | None                                     |
	| LCHIJA | mcwwindows                        | 1.0                   | mcw-windows-1.0.0-mc1.12.2.jar                | None                                     |
	| LCHIJA | mobdismemberment                  | 7.0.0                 | MobDismemberment-1.12.2-7.0.0.jar             | None                                     |
	| LCHIJA | llibrary                          | 1.7.19                | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs                       | 1.5.8                 | mowziesmobs-1.5.8.jar                         | None                                     |
	| LCHIJA | multimob                          | 1.0.5                 | multimob-1.0.5.jar                            | None                                     |
	| LCHIJA | mutantbeasts                      | 1.12.2-0.7.2          | MutantBeasts-1.12.2-0.7.2.jar                 | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
	| LCHIJA | mw                                | 0.4.4.6               | mw_2.0-0.4.4.6_mc1.12.2.jar                   | None                                     |
	| LCHIJA | pogosticks                        | 1.3.1                 | PogoSticks-1.12.2-1.3.1.jar                   | None                                     |
	| LCHIJA | portalgun                         | 7.1.0                 | PortalGun-1.12.2-7.1.0.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | primitivemobs                     | 1.2.3a                | primitivemobs-1.2.3a.jar                      | None                                     |
	| LCHIJA | silentlib                         | 3.0.13                | SilentLib-1.12.2-3.0.14+168.jar               | None                                     |
	| LCHIJA | scalinghealth                     | 1.3.37                | ScalingHealth-1.12.2-1.3.42+147.jar           | None                                     |
	| LCHIJA | storagedrawers                    | 5.2.2                 | StorageDrawers-1.12.2-5.4.2.jar               | None                                     |
	| LCHIJA | stupidthings                      | 1.1.5                 | Stupid+Things-1.12.X-1.1.5.jar                | None                                     |
	| LCHIJA | theoneprobe                       | 1.4.28                | theoneprobe-1.12-1.4.28.jar                   | None                                     |
	| LCHIJA | toolbelt                          | 1.9.13                | ToolBelt-1.12.2-1.9.13.jar                    | None                                     |
	| LCHIJA | vehicle                           | 0.44.1                | vehicle-mod-0.44.1-1.12.2.jar                 | None                                     |
	| LCHIJA | waystones                         | 4.1.0                 | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCHIJA | xaerominimap                      | 20.16.0.2             | Xaeros_Minimap_20.16.0.2_Forge_1.12.jar       | None                                     |
	| LCHIJA | xray                              | 2.0.0                 | xray-1.12.2-1.6.0.jar                         | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
XaeroMinimapPlugin (Xaeros_Minimap_20.16.0.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 452.41' Renderer: 'GeForce GTX 1660 Ti/PCIe/SSE2'
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/hp/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 452.41
	OpenGlRenderer: GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MrCrayfish** [comment]
Chocolate_Quest_Repoured is the issue. It's trying to get the UP direction on a block state that doesn't allow it.

**Comment by StatiK404** [comment]
thanks!

**Comment by MrCrayfish** [comment]
Actually this may be an issue from my own implementation. This is not something I could have foreseen.
