### ISSUE TITLE
[1.12.2] Gif Crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [MrCrayfish/MrCrayfishFurnitureMod#658]
**Describe the bug**

Swtich gif/channels and you get a crash

**Crash report**

https://paste.ee/p/W4zvx

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place a Modern TV
2. Upload gifs
3. Switch channels
4. Get crash

**Screenshots**

None since you get kicked out of your world

Please complete the following information:

- Minecraft Version: 1.12.2 (lastest forge version)
- Mod Version: Furniture Mod 6.3.1

**Comment by Krxwallo** [comment]
Don't write latest forge version write your forge version...
