### ISSUE TITLE
[1.12.2] Dedicated server crash due to spam

### ISSUE THREAD

**Issue by SekiAlpha** [MrCrayfish/MrCrayfishFurnitureMod#659]
**Describe the bug**
One a Dedicated server if someone uses the computer and spam buys something, they can crash the server.

**Crash report**
The crash report seems to be incoherent. But here are the crash reports from the times my server crashed as a result of the spam.

[crash-2021-02-17_21.07.24-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/6000048/crash-2021-02-17_21.07.24-server.txt)
[crash-2021-02-17_21.03.37-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/6000049/crash-2021-02-17_21.03.37-server.txt)
[crash-2021-02-17_20.56.14-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/6000050/crash-2021-02-17_20.56.14-server.txt)
[crash-2021-02-17_22.21.28-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/6000051/crash-2021-02-17_22.21.28-server.txt)
[crash-2021-02-17_21.22.09-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/6000052/crash-2021-02-17_21.22.09-server.txt)

**To Reproduce**
1. Interact with a computer from this mod
2. Spam buy
3. Server should crash after a while

**Screenshots**
None

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 1.3.1

**Comment by SekiAlpha** [comment]
Oh was this fixed? :D

**Comment by MrCrayfish** [comment]
No longer supporting 1.12

**Comment by gatoborrachon** [comment]
sad
