### ISSUE TITLE
[1.12.2] Game crashing on startup

### ISSUE THREAD

**Issue by PrinzFerdiVonRom** [MrCrayfish/MrCrayfishFurnitureMod#660]
Hello so i just tried adding the furniture mod v6.3.1 to my resonant rise 5 modpack which already has some more mods then the normal version but everytime i start the game it crashes at 3/7 in the startup process i then looked in to the logs to find out whats the problem and it seems like on item has a id which is already in my item list is there anyway to change specific item ids in the furniture mod?
the line in the log which made me believe that is as follows:
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
Sorry for not adding the whole log but i think its not necessary as i found the correct line in the logs
- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by MrCrayfish** [comment]
You've reached the maximum amount of blocks. _maximum id range exceeded._
