### ISSUE TITLE
1.16.4 ISSUE HERE

### ISSUE THREAD

**Issue by cameronpogchamp** [MrCrayfish/MrCrayfishFurnitureMod#661]
**Describe the bug**
Stained glass doesn't appear when using mod

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Have the mod enabled
2. Place stained glass
3. Stained glass is invisible

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.16.4
- Mod Version: Furniture Mod 7.0.0-pre19

**Comment by Catomax262** [comment]
Stained glass works fine for me. Try disabling other mods first.
