### ISSUE TITLE
SEVERAL Stuff missing needs to be added in the rewrite

### ISSUE THREAD

**Issue by Catomax262** [MrCrayfish/MrCrayfishFurnitureMod#662]
Why rewriting the mod? Is it still in process? If it is, why?

**Comment by Autovw** [comment]
Well, Minecraft version 1.13 changed a lot of code for the game which means the mod has to be rewritten to work with versions post-1.12.2.
Considering the Furniture mod for Minecraft version 1.12.2 had a lot of items, rewriting and remodelling the mod from scratch will be a lot of work.
And ofcourse, MrCrayfish has also other mods he works on and has his own personal life.

Also keep in mind that the mod for the newest versions is labaled "Alpha" which means it's not officialy out yet.

**Comment by darthvader45** [comment]
Yeah, I'm missing the modern window, fan, table/chair and that sort of stuff.  Goes well with my large modern house.  Hopefully that at the very least can be re-added, as they're simple blocks with models, and the chair is a block with a mount system for sitting on it.  Not to mention modern beds use the vanilla bed mechanics.
