### ISSUE TITLE
[1.16.5] Java Edition - TV not available as craftable item.

### ISSUE THREAD

**Issue by Sherwood321** [MrCrayfish/MrCrayfishFurnitureMod#663]
Hi

Game Version: Java 1.16.5
Mod Version: 1.16.3

Issue: 

A TV cannot be crafted even with all necessary ingredients present. Once all ingredients are in the right window for the crafting table, the item to be crafted remains blank.

Both original TV and modern TV have been attempted. 

Screenshot attached.

![TV craft](https://user-images.githubusercontent.com/5501195/111385913-6065af00-86a3-11eb-87d3-532d81d13981.jpg)

**Comment by MrCrayfish** [comment]
1.16 version is not feature parity with old versions yet

**Comment by Sherwood321** [comment]
Okie dokie 

Thanks for the clarification.
