### ISSUE TITLE
[1.16.4] Fridge Bug

### ISSUE THREAD

**Issue by SkyTheNerd** [MrCrayfish/MrCrayfishFurnitureMod#665]
**Describe the bug**
When I put a fridge around blocks, you can see through some of the blocks where the edges of the fridge are diagonal.

**Crash report**
No Crashes

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Install the mod
2. Go on Minecraft
3. Go on a Minecraft world.
4. Place A Fridge around blocks
5. Look at the edges on the fridge
6. See the error

**Screenshots**
![Big Error](https://user-images.githubusercontent.com/79011616/111874734-e8caa500-896c-11eb-9ad8-f20736781066.png)
![Small Error](https://user-images.githubusercontent.com/79011616/111874769-0992fa80-896d-11eb-904b-f04f1c89f1d2.png)

Please complete the following information:
- Minecraft Version: 1.16.4
- Mod Version: 7.0.0-pre19

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/611
