### ISSUE TITLE
[MINECRAFT VERSION HERE] ISSUE HERE

### ISSUE THREAD

**Issue by yirip** [MrCrayfish/MrCrayfishFurnitureMod#666]
**Describe the bug**
Client side crashes when they first log-in to server.
VanillaFix says the cause might be from MrCrayfish's Furniture Mod.

**Crash report**
[crash-2021-03-22_19.19.02-client.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/6186032/crash-2021-03-22_19.19.02-client.txt)

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Connect to server
2. Move around
3. Game crashes and VanillaFix says the potential cause is from MrCrayfish's Furniture Mod.

**Screenshots**
![2021-03-22 19_21_37-Minecraft 1 12 2](https://user-images.githubusercontent.com/47721566/112074292-fab27080-8b43-11eb-9a14-c7a82e6fb58d.png)

Please complete the following information:
- Minecraft Version: 1.12.2 (Server software: Magma)
- Mod Version: furniture-6.3.1-1.12.2.jar

**Comment by Autovw** [comment]
Magma breaks a lot of mods, including MrCrayfish's Furniture Mod.
