### ISSUE TITLE
Mod wont Appear when launched in 1.16.3

### ISSUE THREAD

**Issue by SpoicehNuggets** [MrCrayfish/MrCrayfishFurnitureMod#667]
I've been wanting to try this mod for a while and so I've been trying to download it in 1.16.3.
I've done all the requirements in order for a mod to work but for some reason the furniture mod just wont pop up when my game is launched. 
please help :,)

**Comment by MrCrayfish** [comment]
Probably not installed correctly. Drag into mods folder, make sure you're launching the game using the correct Minecraft folder.
