### ISSUE TITLE
[1.15/1.16] Items Missing From Both Versions

### ISSUE THREAD

**Issue by Natetdw-labs** [MrCrayfish/MrCrayfishFurnitureMod#668]
**Describe the bug**
All appliances, items, and bathroom furniture are missing, and I am confused about it. Basically these items have either disappeared from newer versions and been removed, or my slow, glitchy computer is acting up yet again.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Go to www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod
2. Click on Furniture Mod 7.0.0-pre19 Download (1.15) or Furniture Mod 7.0.0-pre16 Download (1.15)
3. Apply the mod
4. Open Minecraft and open your inventory
5. Navigate to MrCrayfish's Furniture Mod
6. Notice there are missing items

**Screenshots**
![image](https://user-images.githubusercontent.com/69441976/113522564-27648000-9567-11eb-97d6-784229f25fbf.png) 
![image](https://user-images.githubusercontent.com/69441976/113522579-57138800-9567-11eb-82a5-690ffcb2bf4f.png) 

Please complete the following information:
- Minecraft Version: 1.15 / 1.16
- Mod Version: 7.0.0 pre-19

**Comment by MrCrayfish** [comment]
Welcome to the alpha version which not all furniture have been updated
