### ISSUE TITLE
[1.16.5] Cannot craft furniture. Recipes won't unlock on server

### ISSUE THREAD

**Issue by MrJaybones** [MrCrayfish/MrCrayfishFurnitureMod#672]
I run 1.16.5 on my server and cannot craft furniture. I can craft furniture in a offline singleplayer world. I use just enough items, and also have the right blocks for the recipe but no item shows. 

Please complete the following information:
- Minecraft Version: 1.16.5
![Base Profile Screenshot 2021 05 11 - 14 25 24 42](https://user-images.githubusercontent.com/84028344/117833848-97ed7380-b26e-11eb-8c15-dd3e67896dcd.png)

- Mod Version: 1.16.5

**Comment by MrCrayfish** [comment]
Are you using the latest verison (7.0.0pre21)?

I just tested it and it's working.
![image](https://user-images.githubusercontent.com/4958241/121397352-66fa7e80-c993-11eb-9f1a-a72ee5969a03.png)
