### ISSUE TITLE
[1.16.3] Mod is not compatible with other chest mods

### ISSUE THREAD

**Issue by dhunter49** [MrCrayfish/MrCrayfishFurnitureMod#673]
**Describe the bug**
When you have different chests like oak, spruce, birch chest with quark mod, you cannot craft any of the items in the mod that require a chest

**Crash report**
not applicable

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. download any chest mod
2. try to do a fridge for example with the chest form this mod

**Screenshots**
not applicable

**Solution**
replace in recipes minecraft:chest with forge:chests/wooden

Please complete the following information:
- Minecraft Version: 1.16.3
- Mod Version: 7.0.0-pre19

**Comment by leetfin** [comment]
Similar issue with crash in 1.16.5.

**Comment by dhunter49** [comment]
i see, that in latest update it has been fixed, thank you, closing
