### ISSUE TITLE
1.16.5 Sink Texture

### ISSUE THREAD

**Issue by mAngelo-dev** [MrCrayfish/MrCrayfishFurnitureMod#674]
**Sink texture**
The light gray sink doesnt have the colour it should have

![image](https://user-images.githubusercontent.com/84293279/118414287-13d62a00-b67a-11eb-8b71-531534d1355d.png)

- Minecraft Version: 1.16.5
- Mod Version: I downloaded the recent update around 20days ago from 16/05

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/9056380b7f1dbc464194665972e955f80f122655
It's actually the counters that are wrong since it's terracotta.
