### ISSUE TITLE
[1.16.5] Duplicate items in creative tab

### ISSUE THREAD

**Issue by seancrain** [MrCrayfish/MrCrayfishFurnitureMod#675]
**Describe the bug**
Several blocks are appearing more than once in the creative tab menu.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. open creative tab

**Screenshots**
![2021-05-22_20 19 06](https://user-images.githubusercontent.com/38871906/119244981-33b69380-bb3b-11eb-9e76-7f9170679a12.png)
![2021-05-22_20 19 11](https://user-images.githubusercontent.com/38871906/119244984-39ac7480-bb3b-11eb-85d7-c8e3e47394aa.png)
![2021-05-22_20 19 17](https://user-images.githubusercontent.com/38871906/119244985-3c0ece80-bb3b-11eb-8fc3-8929bebd6f3e.png)
![2021-05-22_20 19 21](https://user-images.githubusercontent.com/38871906/119244988-3f09bf00-bb3b-11eb-8b09-64c302453044.png)

Please complete the following information:
- Minecraft Version: 1.16.5
- Mod Version: 7.0.0-pre20

**Comment by MrCrayfish** [comment]
Fixed in 2d75c8bce54ecf2d7f8d3014414c89839f2f5c05
