### ISSUE TITLE
[1.16.5] Specific Tool Not Set

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishFurnitureMod#680]
**Describe the bug**
A specific tool is not set for furniture, so breaking a wood desk with the hand breaks at the same speed as using an axe. Stone-type desks also drop when broken by hand instead of nothing.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Break stone desk with your hand, it still drops.
2. Break with a pickaxe, still breaks at the same speed.

Please complete the following information:
- `Minecraft v1.16.5`
- `Forge v36.1.24`
- `Cfm v7.0.0-pre21`

**Comment by WenXin20** [comment]
Wood furniture also breaks at the same speed with both an axe and bare hand, if that was missed.

**Comment by MrCrayfish** [comment]
Currently fixing that issue too

**Comment by WenXin20** [comment]
Alright, thanks!
