### ISSUE TITLE
[1.16.5] Random Crash

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishFurnitureMod#682]
**Describe the bug**
- I got a crash during load, which seems to be random as this is the first I've gotten the crash despite running it multiple times before.

**Crash report**
https://gist.github.com/WenXin20/92686b05cdfbd528484b2373df0accf2

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Load game
2. Crash?

Please complete the following information:
- `Minecraft v1.16.5`
- `Mod v7.0.0-pre22`

**Comment by MrCrayfish** [comment]
The crash is caused by Sodium.

**Comment by WenXin20** [comment]
Ah, thanks
