### ISSUE TITLE
1.16.3 Sinks

### ISSUE THREAD

**Issue by Alethalen** [MrCrayfish/MrCrayfishFurnitureMod#684]
To Reproduce If applicable, the steps to reproduce the behavior:

Go to '...' invetory
Click on '....'sinks and place onto a sticky piston
See error: Pistons do not function when powered under a sink i want my sinks on a sticky piston for a hidden entrance idea.
Screenshots If applicable, add screenshots to help explain your problem.

Please complete the following information:

Minecraft Version: 1.16.3
Mod Version: 7.0

**Comment by MrCrayfish** [comment]
Sinks are a tile entity, they can't be moved (just like chests)
