### ISSUE TITLE
[1.16.5] Fridge loot table for top half drops nothing.

### ISSUE THREAD

**Issue by iMahco** [MrCrayfish/MrCrayfishFurnitureMod#687]
Breaking from the base is fine, but as noted in the drop tables for both **fridge_light/dark** (top half):

`{"type":"minecraft:block","pools":[{"rolls":1,"entries":[{"type":"minecraft:item","name":"minecraft:air"}],"conditions":[{"condition":"minecraft:survives_explosion"}]}]}`

Not that big a deal but adding it in here in case it was missed!

**Comment by MrCrayfish** [comment]
It intentionally doesn't drop anything since the fridge is dropped by the freezer block.

**Comment by iMahco** [comment]
Wait-- so just to clarify, if I as a player break the fridge from the top, me losing the fridge to the void is intentional?

**Comment by MrCrayfish** [comment]
Regardless which block you break on the fridge, the bottom will drop the item.

**Comment by ocram9** [comment]
This doesn't seem to be the case. I just broke the top of the fridge but nothing was dropped.

**Comment by iMahco** [comment]
> This doesn't seem to be the case. I just broke the top of the fridge but nothing was dropped.

Can second this, which was why I posted about it initially.
A datapack can work around it so it isn't an annoyance to other players in the meantime ocram sir.
