### ISSUE TITLE
[1.12.2] Create USB port of the Device Mod for the TV and its respective graphical interface

### ISSUE THREAD

**Issue by DevWolf31** [MrCrayfish/MrCrayfishFurnitureMod#691]
Create USB port of the Device Mod for the TV and its respective graphical interface. I say this so you can see Pixel Painter Images on TV

**Comment by MrCrayfish** [comment]
The device mod is discontinued because it was too much work. Merging it into the furniture mod doesn't remove that work.

**Comment by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET** [comment]
True, im new to java, and it took me 2 hours to make minecraft not crash on load, and another 2 hours to reroute gitweb to my own repo and make the bank (partially) work
