### ISSUE TITLE
[1.16.5] Datapack error when Bayou Blues and Abundance are not present

### ISSUE THREAD

**Issue by Sunconure11** [MrCrayfish/MrCrayfishFurnitureMod#693]
[latest.log](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/6984913/latest.log)

**Comment by Sunconure11** [comment]
This only gets triggered on Mohist.

**Comment by MrCrayfish** [comment]
Sounds like a Mohist problem since it works fine on normal Forge.

**Comment by MrCrayfish** [comment]
Yes it's a problem with Mohist as this is the problematic code.
https://github.com/MohistMC/Mohist/blob/ebeabb2b11624d3a5308eb37c083a951662b5f3f/patches/minecraft/net/minecraft/loot/LootTableManager.java.patch#L43

Please open a issue on Mohist with their appropriate issue template.
