### ISSUE TITLE
1.17.1 does not work with mixins loaded

### ISSUE THREAD

**Issue by whatthedrunk** [MrCrayfish/MrCrayfishFurnitureMod#697]
On ATM7 we now use MixinBootstrap so it trys to load some mixin stuff in your mod that is not updated yet. 
https://hastepaste.com/view/6yxU
https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap/files/3437402

**Comment by MrCrayfish** [comment]
Thanks for the report, I'll get a patch out asap.
