### ISSUE TITLE
[1.16.5] Bathroom furniture not showing

### ISSUE THREAD

**Issue by DJAMIRSAM** [MrCrayfish/MrCrayfishFurnitureMod#698]
ARE YOU USING 1.12? IF SO, I NO LONGER MAINTAIN THIS VERSION AND WON'T BE FIXING BUGS. PLEASE UPDATE TO A NEWER VERSION

**Describe the bug**
The bathroom items and others are not showing in 1.16.5 forge 

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Go to 'MrCrayfish's website and download the mod'
2. Click on The furniture tab
3. No bathroom section

**Screenshots**
![image](https://user-images.githubusercontent.com/78499690/131698351-1887d66c-063d-4146-9ce2-13bc44a043ee.png)

Please complete the following information:
- 1.16.5
- Mod Version: cfm-7.0.0pre22-1.16.3.jar

**Comment by MrCrayfish** [comment]
The 7.0.0 is a beta version. The update is not fully complete since I am rewritting and remodelling everything.
