### ISSUE TITLE
[Forge 1.17.1] Incompatible with 37.0.59

### ISSUE THREAD

**Issue by Baggytrousers27** [MrCrayfish/MrCrayfishFurnitureMod#699]
Forge 1.17.1 37.0.59
catalogue-1.3.0-1.17.1
configured-1.2.0-1.17.1
cfm-7.0.0pre24-1.17.1

Crashes after launch.

[Debug log](https://pastebin.com/v5yFDwB6)

**Comment by Baggytrousers27** [comment]
Sorry for the multiple edits. Pressed enter too early.

**Comment by MrCrayfish** [comment]
1.17 version will no longer be supported.
