### ISSUE TITLE
Audio is out of sync on Cooking with the Cray

### ISSUE THREAD

**Issue by sudo-apt-get-install** [MrCrayfish/MrCrayfishFurnitureMod#70]

**Comment by darthvader45** [comment]
Yeah, TV channels have out-of-sync audio.

**Comment by MrCrayfish** [comment]
This has been fixed now due to a rewrite with the TV. Coming in v5.5.0

**Comment by darthvader45** [comment]
Awesome.  Love the new stuff.  Maybe a garage door and a way to link it
with the light switch to make a garage door opener?

Golden rule in Minecraft: Never dig straight down.
