### ISSUE TITLE
1.16.5/1.17.1 Nothing after installing mod

### ISSUE THREAD

**Issue by MegaSa1nt** [MrCrayfish/MrCrayfishFurnitureMod#702]
ARE YOU USING 1.12? IF SO, I NO LONGER MAINTAIN THIS VERSION AND WON'T BE FIXING BUGS. PLEASE UPDATE TO A NEWER VERSION

**Describe the bug**
Nothing happens after installing mod

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Download mod
2. Place to .minecraft/mods
3. Launch Minecraft
4. See nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/49565695/139750702-1569d7e1-a07c-46c5-9460-53540e0e5609.png)

Please complete the following information:
- Minecraft Version: 1.16.5/1.17.1
- Mod Version: Actual version for this Minecraft versions

**Comment by MrCrayfish** [comment]
Yeah, it's not a fabric mod...
