### ISSUE TITLE
1.17.1 Contant lag spikes

### ISSUE THREAD

**Issue by AMSG2020** [MrCrayfish/MrCrayfishFurnitureMod#704]
ARE YOU USING 1.12? IF SO, I NO LONGER MAINTAIN THIS VERSION AND WON'T BE FIXING BUGS. PLEASE UPDATE TO A NEWER VERSION

**Describe the bug**
So, I'm playing at whatever fps I'm running (ex. 50fps) about every 3 seconds or so I get a lag spike bring me to 0fps for about 1 second.

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.17.1
- Mod Version: 7.0.0pre25

**Comment by MrCrayfish** [comment]
Increase your RAM.
