### ISSUE TITLE
[1.17.1] Some furniture cannot be mined in survival. 

### ISSUE THREAD

**Issue by Howardhv99** [MrCrayfish/MrCrayfishFurnitureMod#706]
Description:
Some furniture pieces cannot be mined and collected after being placed in survival mode independent of the tool tier or enchantments applied. 
 (tested in creative, seems all stone or iron based furniture has this problem) 

To Reproduce
1.Place any iron or stone based furniture
2.Try to mine it or survival 

Additional info:. 
- Minecraft Version: 1.17.1
- Mod Version: cfm-7.0.0pre25-1.17.1
- Forge version: forge-1.17.1-37.0.112

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/32dcc5eb2527464492370dc23ec34e40f3c41570
