### ISSUE TITLE
[1.17.1] Game Crashed

### ISSUE THREAD

**Issue by TG310** [MrCrayfish/MrCrayfishFurnitureMod#707]
**Describe the bug**
The game crash when I try to join my server with the mod installed.
It's work fine when I join singleplayer world. But also crash when I try to access the creative inventory.
This has never happened before, I have played with the mod installed several weeks now.
It seem that when game try to render furniture the game crash.
**Crash report**
https://pastebin.com/27tMmezv (joining server)

- Minecraft Version: 1.17.1
- Mod Version: furniture-7.0.0-pre25-1.17.1.jar

**Comment by MrCrayfish** [comment]
Thanks for the report. I believe I have found the issue. For now and you shouldn't need it turned on anyway, turn off drawCollisionShapes in the config.

**Comment by MrCrayfish** [comment]
Didn't mean to close...
