### ISSUE TITLE
[1.18] Item disappearing after closing world

### ISSUE THREAD

**Issue by FinzoYFunzo** [MrCrayfish/MrCrayfishFurnitureMod#710]
**Describe the bug**
When you put any item in a furniture of the mod, after closing it, all items will disappear

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Put Any furniture that can contain items
2. Exit the world
3. Open it again
4. they are no longer there

Please complete the following information:
- Minecraft Version: 1.18
- Mod Version: Furniture Mod 7.0.0pre25

**Comment by UdoMorgenstern** [comment]
Same issue with crates and coolers under 7.0.0pre25

**Comment by MrCrayfish** [comment]
Patched. Download the latest updates
