### ISSUE TITLE
Crashing on start up

### ISSUE THREAD

**Issue by asturias95** [MrCrayfish/MrCrayfishFurnitureMod#712]
Crash Report
[crash-2021-12-18_11.35.06-client.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/7739138/crash-2021-12-18_11.35.06-client.txt)

**Comment by MrCrayfish** [comment]
You can't add more than 4096 blocks. Also error is not even related to my mod.

**Comment by asturias95** [comment]
Sorry for my mistake.
Could you tell me what the error is?

**Comment by MrCrayfish** [comment]
Basically you've reach the block limit. The game can't handle more than 4096 blocks registered. The only way you can fix this is by removing mods.
