### ISSUE TITLE
Door Mat don't show any message

### ISSUE THREAD

**Issue by smurfvegetariano** [MrCrayfish/MrCrayfishFurnitureMod#717]
I've installed MrCrayfishFurnitureMod in a server along with some other mods, and the message written when placing the doormat isn't showing up.

**Comment by KerndogTheBold** [comment]
When I tried placing mine in a server it crashed my game and now it's a missing chunk. RIP house.

**Comment by MrCrayfish** [comment]
If it crashed, make sure you update to the latest version.

**Comment by MrCrayfish** [comment]
Can't seem to reproduce. Make sure you're using the latest versions of the mod. If you're using 1.12.2 I won't be fixing any issues like that since it's discontinued.
