### ISSUE TITLE
[1.18.1] Mod is making game crash when connecting

### ISSUE THREAD

**Issue by DKad96** [MrCrayfish/MrCrayfishFurnitureMod#718]
An error is making the game crash as soon as a player connects to the server. We've tried removing the mod and the game loaded without any issues. Doormats, which according to the log are responsible for the problem, have been put in the server at least a week ago and haven't presented any issues apart from not showing what's written on them.

Crash report:
https://pastebin.com/gNqhYR93

Steps to reproduce:
1. Start Server on Aternos
2. Connect to Server
3. See error

Versions:
- Minecraft Version: 1.18.1
- Forge Version: 39.0.20
- Mod Version: 7.0.0-pre27

**Comment by MadCat64** [comment]
Same issue but on Single Player and Windows 10.  Unable to load into world once a doormat is placed.  

[https://pastebin.com/780xx0XX](url)

Minecraft version 1.18.1
Forge Version 39.0.45
Mod Version 7.0.0-pre27

**Comment by Tytyfhfh** [comment]
It seems to be a problem with forge 39.0.45 as they changed something with the tags but ive heard of one person getting some mods to work on newer versions but the forge change seems to have messed up a few mods, only solution so far is to go back to an earlier forge version and if you can, otherwise just wait til the developer can find some free time to fix it

**Comment by MadCat64** [comment]
Thank you for the reply.  I didn't mean to undermine the original post.  They were using Forge 39.0.20.  I probably should have made a new issue.  Maybe a different forge will work with that too.  Sorry DKad96.

**Comment by MrCrayfish** [comment]
Temporarily use a version lower than 39.0.45

**Comment by DKad96** [comment]
No prob MadCat64, I was actually wrong about the Forge version. The server was running on the newest one, but I didn't update locally. I'm unable to install an older version of Forge as I'm hosting a server on Aternos and it auto updates x.x, so I had to remove the mod in order to continue my world :/

But I think it has been updated again?

**Comment by MrCrayfish** [comment]
Update to pre28 to fix the issue
