### ISSUE TITLE
[1.18.1] Door Mat causing Fatal Server Crash

### ISSUE THREAD

**Issue by KerndogTheBold** [MrCrayfish/MrCrayfishFurnitureMod#720]
**Describe the bug**
Placing a Door Mat into the world causes the world to crash and leave a corrupted chunk in its place.

**To Reproduce**
1. Craft Door Mat
2. Place
3. Asks you to put message
4. Before message can be placed, world crashes

Please complete the following information:
- Minecraft Version: 1.18.1
- Mod Version: Latest Version/ 7.0.0-PRE27-MC1.18.1

**Comment by MrCrayfish** [comment]
Update to pre28
