### ISSUE TITLE
[1.12.2] Modern Sliding Door placed in world causing unusual amount of fps drop

### ISSUE THREAD

**Issue by wed15** [MrCrayfish/MrCrayfishFurnitureMod#721]
**Describe the bug**
Whenever Modern Sliding Doors placed in world are rendered they cause relatively noticeable fps drop, and they seem to rendered regardless of distance.
When compared with Malisis door mod which also uses tile entity model for doors and supports lot of customizability, custom malisis doors simply cost less fps and stop being rendered when you're far away or properly culled behind blocks with EntityCulling mod.

**Crash report**
none

**To Reproduce**
1. Load any world
2. Place several modern doors
3. Check the fps around the doors

**Screenshots**
Default Super flat world as is:
![2022-01-24_09 50 25](https://user-images.githubusercontent.com/86100898/150706774-646c1a75-6e0e-4547-b4e1-508181de27bf.png)
With 20 modern doors:
![2022-01-24_09 51 08](https://user-images.githubusercontent.com/86100898/150706778-995db1db-b305-41e9-9f49-3a4a80a6e785.png)
In case of custom Malisis doors:
![2022-01-24_09 53 18](https://user-images.githubusercontent.com/86100898/150707381-92ce69f7-a43a-42f3-9cbf-7b502f5ea422.png)

Also comparison in my base with lots of processing tile entities:
![2022-01-24_09 46 05](https://user-images.githubusercontent.com/86100898/150707138-4d4a4adb-886d-4813-81eb-dfef62f9b745.png)
![2022-01-24_09 46 52](https://user-images.githubusercontent.com/86100898/150707142-b67d839b-4a75-4d0b-a591-ffeac35ee167.png)

- Minecraft Version: 1.12.2
- Mod Version: 6.3.1

**Comment by MrCrayfish** [comment]
No longer maintaining the 1.12.2 version of this mod.

**Comment by xJon** [comment]
Just for reference, this is still an issue with the most recent update (6.3.2).
