### ISSUE TITLE
[1.16.5] Sink doesn't always extend existing countertops

### ISSUE THREAD

**Issue by aaron-jencks** [MrCrayfish/MrCrayfishFurnitureMod#726]
**Describe the bug**
When placing a sink next to the overhang of a counter, it doesn't extend the counter, see screenshot

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place a counter
2. Rotate player 90 degrees
3. Place Sink
4. Profit

**Screenshots**
![2022-02-03_11 37 15](https://user-images.githubusercontent.com/32805004/152397940-24c25c40-af72-4973-ab30-a10d3fde1b54.png)

Please complete the following information:
- Minecraft Version: 1.16.5
- Mod Version: I assume 7.0pre22, but I can't seem to locate the mod in All the Mods 6, or find the file to find out for sure.

**Comment by MrCrayfish** [comment]
Thanks. I will look into this soon.
