### ISSUE TITLE
[Minecraft 1.18.1] Trampoline, Grill and Post Box Block Error

### ISSUE THREAD

**Issue by NarwhalTiger** [MrCrayfish/MrCrayfishFurnitureMod#727]
Placing down either the Trampoline, Grill or Post Box block it either causes the world to crash and cannot open again or it opens but the chunk in which the block was placed in is corrupted and will not load.

When placing the Trampoline block:
(world can’t be reopened and no detailed crash report all it show is this)

![AE615833-37F4-4033-B88D-821B82C22E40](https://user-images.githubusercontent.com/99114451/152671624-492241b9-c9ab-4c78-8234-86cd6acdb1d8.png)

When placing the Grill block:
(world crashes with same error and when reopened it shows chunk missing where the Grill block was placed)

![59D27EC8-E4CB-403E-9243-94D6C8847732](https://user-images.githubusercontent.com/99114451/152671691-2416eed0-01bb-4c11-8952-6b53401835cf.png)

When placing the Post Box it crashed and received this Error: (for some reason unlike the Trampoline block the Post Box block gave a detailed crash report)

[message.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/8009696/message.txt)

Reopening the world shows a missing chunk where the Post Box block was place:

![19B6B769-DDCF-46A5-8DBC-9FC01A5B160F](https://user-images.githubusercontent.com/99114451/152672337-6c25319b-99a1-4dd2-b132-28c3df0e15cc.png)

- Minecraft Version: 1.18.1
- Mod Version: 7.0.0

**Comment by MrCrayfish** [comment]
Not using the latest version of the mod
