### ISSUE TITLE
1.18.1 - Placing Door Mat crashed game and when re-loaded will not load an area around where the mat was

### ISSUE THREAD

**Issue by CharlieOO3** [MrCrayfish/MrCrayfishFurnitureMod#729]
### **Placing Door Mat crashed game and when re-loaded will not load an area around where the mat was.**

Crash Report:
[crash-2022-02-08_20.34.11-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/8027386/crash-2022-02-08_20.34.11-server.txt)

Images:
![2022-02-08_20 46 44](https://user-images.githubusercontent.com/99291625/153073177-7aceb179-8e61-410a-acbc-853bc46060b5.png)
![2022-02-08_20 46 48](https://user-images.githubusercontent.com/99291625/153073204-af159806-3398-49fd-963d-9fee827ede75.png)
![2022-02-08_20 46 59](https://user-images.githubusercontent.com/99291625/153073214-13d02d2d-176b-419b-814d-3771a5a0c2e9.png)

**Comment by MrCrayfish** [comment]
Update to the latest version of the mod
