### ISSUE TITLE
Door mat bounding box

### ISSUE THREAD

**Issue by Spyeedy** [MrCrayfish/MrCrayfishFurnitureMod#73]
The door mat's bounding box is larger than the block itself. Was the code meant to be like this or is this an error in the code? Image attached
![2016-05-28_07 38 23](https://cloud.githubusercontent.com/assets/16463199/15623588/0ba17d58-24a8-11e6-952c-86f8a6998f31.png)

**Comment by sudo-apt-get-install** [comment]
I'm pretty sure it's not possible to shorten the the hitbox

**Comment by MrCrayfish** [comment]
It is, and will make an improved version.

**Comment by MrCrayfish** [comment]
I'm going to close because this is not an issue.
