### ISSUE TITLE
[1.18.1] chuck not loading 

### ISSUE THREAD

**Issue by uvee24** [MrCrayfish/MrCrayfishFurnitureMod#732]
ARE YOU USING 1.12? IF SO, I NO LONGER MAINTAIN THIS VERSION AND WON'T BE FIXING BUGS. PLEASE UPDATE TO A NEWER VERSION

**Describe the bug**
i placed down a grill the nest seccond it crashed and now the chunk that the grill was in is completly blank and doesnt load

**Screenshots**
![Minecraft_ 1 18 1 - Singleplayer 3_5_2022 4_15_53 PM](https://user-images.githubusercontent.com/101005903/156887147-894a0588-7a23-44c0-8457-18b00bb1ea49.png)

Please complete the following information:
- Minecraft Version:1.18.1
- Mod Version:7.0.0

**Comment by MrCrayfish** [comment]
Been fixed a while ago. Update to the latest version of the mod.
