### ISSUE TITLE
[1.18.2] Game Crash on Launch

### ISSUE THREAD

**Issue by jrbuchanan02** [MrCrayfish/MrCrayfishFurnitureMod#733]
**Describe the bug**
On Launch, Forge reports that the mod threw `java.lang.reflect.InvocationTargetException: null`
**Crash report**
(uploaded with this issue)
[crash-2022-03-06_17.10.21-fml.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/8193727/crash-2022-03-06_17.10.21-fml.txt)

**To Reproduce**
Start Minecraft 1.18.2 using the pre28 build of cfm

**Screenshots**
![image](https://user-images.githubusercontent.com/62662095/156946332-6c6c2021-67aa-4719-bc60-04e2b3eb75d0.png)

Please complete the following information:
- Minecraft Version: 1.18.2 using Forge Beta 40.02
- Mod Version: 1.18.2 pre 27 and 1.18.2 pre 28 (I've tried both)

**Comment by thedevouttrout** [comment]
i ahve also had this issue

**Comment by MrCrayfish** [comment]
New release coming soon. 1.18.2 broke the mod.
