### ISSUE TITLE
[1.18.1] Not filled all elements of the vertex at mrcrayfish.furniture.client.ClientEvents.lambda$drawShape$0(ClientEvents.java:53)

### ISSUE THREAD

**Issue by CKY-** [MrCrayfish/MrCrayfishFurnitureMod#735]
**Describe the bug**
on load
java.lang.IllegalStateException: Not filled all elements of the vertex

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.
are you ok with a crashy report ?
https://crashy.net/WEXxLFuh2nVxNyLBnmR7

here is the raw crash data 
https://crashy.net/WEXxLFuh2nVxNyLBnmR7?raw

I like dark mode 

Please complete the following information:
- Minecraft Version: 1.18.1
- Mod Version: 7.0.0-pre28-1.18.1

**Comment by MrCrayfish** [comment]
Update to the latest verison. This has been fixed for a while.

**Comment by CKY-** [comment]
![image](https://user-images.githubusercontent.com/8982158/160293279-5488188d-224e-4f64-a8c3-9721915fab1f.png)
it dont get any later then that?

**Comment by MrCrayfish** [comment]
Turn off `drawCollisionShapes` in the client config. It's a debug tool.

**Comment by CKY-** [comment]
Yes thank you this fixed the issue.
