### ISSUE TITLE
i'm so confused

### ISSUE THREAD

**Issue by TuffCat** [MrCrayfish/MrCrayfishFurnitureMod#739]
where the HECK do i download the latest versions of the mod?!?! i've checked all over the wiki and curseforge page! i was GOING to use this with all of my other mods for 1.16.5 to make a better way to play survival minecraft- i was especially hoping for opening windows- but turns out that i can't actually test anything out because there's no way to download versions later than 1.12.2! can you please send a link to a place where i can download the 1.16.5 version???

**Comment by MrCrayfish** [comment]
https://mrcrayfish.com/mods?id=cfm
or 
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/files/all

1.16.3 works with 1.16.5
