### ISSUE TITLE
[1.19 Java Forge] Game crashes after filling up a sink

### ISSUE THREAD

**Issue by QuickGurke** [MrCrayfish/MrCrayfishFurnitureMod#743]
Every time I try to fill up a sink, the game immediatly crashes.
I have tried multiple different sinks, worlds and fluids.

**Crash report**
(https://pastebin.com/T5zf3QaM)

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Place ANY sink
2. Equip ANY fluid
3. Look at sink and right click to fill it up

**Screenshots**
If applicable, add screenshots to help explain your problem. -> Game crashes immediatly, so there is no option to make a screenshot.

Please complete the following information:
- Minecraft Version: 1.19
- Mod Version: cfm-7.0.0-pre30-1.19

**Comment by MrCrayfish** [comment]
Update to latest version
