### ISSUE TITLE
MC 1.19 - DrawSelectionEvent$HighlightBlock error

### ISSUE THREAD

**Issue by Gamemassa** [MrCrayfish/MrCrayfishFurnitureMod#747]
**Description**
Tried to load with latest version of Forge and game crashed with a DrawSelectionEvent$HighlightBlock error.

**Crash report**
[crash-2022-07-09_17.21.22-fml.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/9077958/crash-2022-07-09_17.21.22-fml.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/18667108/178123145-ff965d93-a2fb-4038-a192-b7b8a8604710.png)

- Minecraft Version: 1.19
- Forge Version: 41.0.85
- Mod Version: 7.0.0-pre31

**Comment by MrCrayfish** [comment]
Forge 41.0.64 changed some internal code in their API, expect a patch soon

**Comment by Gamemassa** [comment]
Not sure if this is related, but I updated your furniture mod to 7.0.0-pre32 and Forge to 41.0.94 this morning, and I got an error message saying:

java.lang.reflect.InvocationTargetException: null

[crash-2022-07-12_08.15.07-fml.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/9092863/crash-2022-07-12_08.15.07-fml.txt)

**Comment by MrCrayfish** [comment]
pre33 fixes the issue
