### ISSUE TITLE
There is no bedside lamp

### ISSUE THREAD

**Issue by Dirtgamer** [MrCrayfish/MrCrayfishFurnitureMod#75]
![2016-05-28_08 48 40](https://cloud.githubusercontent.com/assets/19620053/15625726/a1ce666a-24b2-11e6-8682-15e81c397330.png)
There isn't

**Comment by GravityLens** [comment]
I have already covered this in an issue of my own https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/63

**Comment by sudo-apt-get-install** [comment]
Duplicate

**Comment by MrCrayfish** [comment]
#63
