### ISSUE TITLE
1.12.2 gif/images on tv's

### ISSUE THREAD

**Issue by McNubbinit** [MrCrayfish/MrCrayfishFurnitureMod#755]
Sorry if the question's already been asked, but could I get an example of whitelisting the domain for mod version 6.3.2 for game version 1.12.2? I've worked at the config file for awhile but am not sure of the syntax required to add even the i.imgur.com domain to allow for the jpeg MrCrayfish used as an example in the config file. Any examples or help would be greatly appreciated.

**Comment by Micchaell** [comment]
# List of trusted domains to download images for the TV and Photo Frame. For example, the domain of the URL (https://i.imgur.com/Jvh1OQm.jpeg) is i.imgur.com [default: ]
    S:trusted-url-domains <
        i.imgur.com
     >
}

There you go! Just write the domain between the "<" and ">"

**Comment by damqn4etoBG** [comment]
# List of trusted domains to download images for the TV and Photo Frame. For example, the domain of the URL (https://i.imgur.com/Jvh1OQm.jpeg) is i.imgur.com [default: ]
    S:trusted-url-domains <
        https://i.imgur.com/
        
        i.imgur.com
        
        im3.ezgif.com
        
        im.ezgif.com
     >
}

This is mine and it still doesn't work for some reason

**Comment by Drachie** [comment]
Hello,

I have entered the domains correctly in the config as indicated, but in the game itself I still get the message Untrsuted Domain. how do i fix the problem?

Code excerpt from the config:
     # List of trusted domains to download images for the TV and Photo Frame. For example, the domain of the URL (https://i.imgur.com/Jvh1OQm.jpeg) is i.imgur.com [default: ]
     S:trusted-url-domains <
         buergel-it.de
         mc.buergel-it.de

      >

**Comment by MrCrayfish** [comment]
Is it placed in the client version of the config?

**Comment by Drachie** [comment]
In both (Server and client).

After restart Server and client, the issue the same.

untrusted Domain…

**Comment by aman-mohammed-max** [comment]
any fix

**Comment by Bjamse** [comment]
No fix available?

**Comment by NotBlueTV** [comment]
idk what to do it says untrused something idk

**Comment by besheps** [comment]
but how the flip can i go into the config?

**Comment by Yusuf0078** [comment]
Hello, I entered the following link on the TV "https://imgur.com/Vd7GKgO.gif"
however, the television did not see it as a Gif, I tried to do it with ChatGPT, I entered the i.imgur.com and imgur.com addresses under the trusted-url-domain, but the result is that I tried to install the same mode from the beginning every time, but the result is the same every time

**Comment by hesambenenayeh-cell** [comment]
i tried it with vscode, it works
