### ISSUE TITLE
[Suggestion] Simple texture for inventory interiors

### ISSUE THREAD

**Issue by MarioSMB** [MrCrayfish/MrCrayfishFurnitureMod#762]
When you open a Minecraft chest, there is a simple two-dimensional texture covering the surface to give the illusion of a dark and full interior.  
When opening furniture in this mod (most notably the fridge) the interior is hollow and three-dimensional, which gives the appearance of a completely empty fridge! It would be a nice visual touch to use simple images in the inventories, it may even save performance not needing to render the interior models.

**Comment by MrCrayfish** [comment]
Thanks for the suggestion. This is actually how I have designed the model in the upcoming rewrite.
