### ISSUE TITLE
Trampoline

### ISSUE THREAD

**Issue by Dirtgamer** [MrCrayfish/MrCrayfishFurnitureMod#77]
![2016-05-28_08 12 08](https://cloud.githubusercontent.com/assets/19620053/15625736/db4a0912-24b2-11e6-84cc-de078a0290cb.png) 

There's still a texure problem

**Comment by MrCrayfish** [comment]
That's unfortunately how I made it, otherwise there would be too many blockstates to handle. However, the 1.9 version will fix this, 1.8.9 will stay like above.
