### ISSUE TITLE
[1.12.2] CURTAINS COLOR DEPENDS OF SIDE IT PLACED, NOT COLOR OF IT

### ISSUE THREAD

**Issue by sova91a** [MrCrayfish/MrCrayfishFurnitureMod#770]
when i place curtains, it's color does not depend of color, it depends of side it placed. on screenshot you can see SAME CURTAIN placed in different sides, it happens to every curtain color. how i can fix it? when i played this version 2 years ago i haven't seen this bug
![image](https://user-images.githubusercontent.com/114819483/193415224-1b8070fe-94bf-4f49-9d62-38182a446992.png)
(sorry for opened menu, i cant screenshot without it)

mc version: 1.12.2
mod version: 6.3.2

**Comment by MrCrayfish** [comment]
I no longer provide fixes for this version
