### ISSUE TITLE
[1.19.2] Why some furniture is not added in 1.19.2?

### ISSUE THREAD

**Issue by IlyaYezelovsky** [MrCrayfish/MrCrayfishFurnitureMod#775]
**Describe the bug**
Some furnitures, such as TV, modern bed, showers are not added in 1.19.2. I searched them in JEI, but no results.

**To Reproduce**
If applicable, the steps to reproduce the behavior:
1. Search the missing furnitures in creative inventory or JEI
2. You can't see them!

Please complete the following information:
- Minecraft Version: 1.19.2
- Mod Version: 7.0.0-pre30

**Comment by t3duk** [comment]
I'm sure due to changes in Minecraft's code it can't be ported immediately and required redoing or something like that.

**Comment by MrCrayfish** [comment]
The mod is undergoing a complete rewrite/remodel. It doesn't make sense for me to spend time adding back old code when I am writing a brand new version.

**Comment by SonicTheHedgehog58987276** [comment]
can you re-add the toilet?
