### ISSUE TITLE
1.12.2 tvs and images untrusted domain

### ISSUE THREAD

**Issue by Mjgamingmcs** [MrCrayfish/MrCrayfishFurnitureMod#777]
i put the site in config on client and server but it still says untrusted domain and it used to work but now it just says untrusted domain

**Comment by fain6789** [comment]
> i put the site in config on client and server but it still says untrusted domain and it used to work but now it just says untrusted domain

go to the .minecraft/config/cfm.cfg , at the end it has line with "trusted doamins", put your domain between < and>, like

<
i.imgur.com
>

**Comment by babewind** [comment]
> > 我将站点放在客户端和服务器上的配置中，但它仍然显示不受信任的域，它曾经有效，但现在它只是说不受信任的域
> 
> 转到 .minecraft/config/cfm.cfg ，末尾有一行“Trusted Doamins”，将您的域放在 < 和 > 之间，例如
> 
> <i.imgur.com
> 
> >

no.It doesn't work at all, I've tried all the ways to add domains, but it always just shows that untrusted domain

**Comment by SfortzaPhantom** [comment]
![image](https://github.com/user-attachments/assets/a6e458c1-4890-4424-bb45-b612af7ef273)

The fix is relatively simple, yet I don't have a clue why Crayfish doesn't explain this by himself.

Should look instead of this:

    S:trusted-url-domains <
		i.imgur.com
     >

like this:

    S:trusted-url-domains <
		i.imgur.com >

So you should remove any strings between the last URL and >.

**Comment by Jayrus10** [comment]
not work

![Image](https://github.com/user-attachments/assets/05991114-24e6-4d25-ad03-46bdefef3d24)

**Comment by tnwlss1013-sketch** [comment]
i tried to work it but it don't typed...
bc: my keyboard is broken...
