### ISSUE TITLE
1.19.3 Mod causing Minecraft to not load correctly

### ISSUE THREAD

**Issue by ehhut1** [MrCrayfish/MrCrayfishFurnitureMod#782]
Minecraft not loading correctly when mod is installed. 

**Crash report**
https://pastebin.com/5iy6wyiN

Please complete the following information:
- Minecraft Version: 1.19.3
- Mod Version: pre34 1.19

**Comment by MrCrayfish** [comment]
1.19.2 mods don't work with 1.19.3
