### ISSUE TITLE
[language update]zh_cn.json update for 1.19.2

### ISSUE THREAD

**Issue by YivanLiu** [MrCrayfish/MrCrayfishFurnitureMod#789]
[zh_cn.zip](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/10778919/zh_cn.zip)

**Comment by MrCrayfish** [comment]
Thanks. Translations has been added to the 1.20.1 version. I included credit for you on the commit here: https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/a721f906eefcc9af5806dec065f31345b2e713a4
