### ISSUE TITLE
Plates have no texture

### ISSUE THREAD

**Issue by Jeffreyman101** [MrCrayfish/MrCrayfishFurnitureMod#79]
The plates have the default black and purple box thing instead of its texture
![2016-05-30_19 22 49](https://cloud.githubusercontent.com/assets/17098923/15659644/efa31aa8-269b-11e6-9bf0-7a434ef9ded0.png)

**Comment by MrCrayfish** [comment]
Already been reported in #57 and fixed in aabb0ae14b65b8e21c46ef62d4c392e66416f523
