### ISSUE TITLE
Sausage Duplication glitch

### ISSUE THREAD

**Issue by Jeffreyman101** [MrCrayfish/MrCrayfishFurnitureMod#80]
Everytime you open up a crafting table with Sausage (in your inventory) it will pop up with 16 inside it
![2016-05-30_19 31 48](https://cloud.githubusercontent.com/assets/17098923/15659697/3ef563b2-269d-11e6-9bd5-bce1177ebc57.png)

**Comment by MrCrayfish** [comment]
Already been report (#59) and fixed.
