### ISSUE TITLE
[1.12.2] The config wont work for the TV and Picture Frame

### ISSUE THREAD

**Issue by duck-army160** [MrCrayfish/MrCrayfishFurnitureMod#804]
**Describe the bug**
Whenever I put the links in the config, it doesnt work

**To Reproduce**
If applicable, the steps to reproduce the behavior:
In the config, if you put a link to a website for the TV, it wont work

**Screenshots**
screenshot below

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: Latest 1.12.2 Version as of September 23, 2023
![Capture](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/assets/130019206/e32f61f9-4206-4381-bf70-54680cdd7aac)

**Comment by TimewarpDrive** [comment]
"literally me"

**Comment by MrCrayfish** [comment]
You need to be explicit with the domains. Media is stored on Wikipedia at `upload.wikimedia.org`, not `wikipedia.com`
