### ISSUE TITLE
[1.12.2 and 1.16.5)] Photo portrait no longer working

### ISSUE THREAD

**Issue by xlbeutel** [MrCrayfish/MrCrayfishFurnitureMod#816]
Specifically, it says "image is not a URL" for links that should work. Imgur is the site that I use, and strangely enough some images still show up, but not others. This is an issue on both single and multiplayer.

For example, this image works: https://i.imgur.com/O3MAmNz.jpg

But for whatever reason, this one does not: https://i.imgur.com/2bTu7hf.jpg

Same file type, same domain, everything. I've tried other photo uploading sites, all with the same results. 

It seems the only photos that work were ones I've used on a given server before. Any other photos, no matter the site, always say "URL is not an image" 

This only started a few months ago, which makes it all the more stranger. It can't be a site problem, since every photo dumping site seems to not work (even after approving the domains). I tried installing the mod alone outside of my custom pack to see if it was a compatibility thing, same issue. I tried the mod on different versions, same problem. I genuinely can't figure this out. 

**Screenshots**
![078w5f04aduc1](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/assets/167043773/5f59a03f-4d7f-4b65-9731-ce5ca5ef4af5)

Please complete the following information:
- Minecraft Version: 1.12.2, 1.16
- Mod Version: 6.3.2, 7.0.0pre22

**Comment by MrCrayfish** [comment]
You have to point to a direct image url. The extension on a URL doesn't mean anything. From a quick investigation, just change `.jpg` to `.jpeg`
