### ISSUE TITLE
[1.12.2 and 1.16.5] still having photo portrait issues

### ISSUE THREAD

**Issue by xlbeutel** [MrCrayfish/MrCrayfishFurnitureMod#817]
You have to point to a direct image url. The extension on a URL doesn't mean anything. From a quick investigation, just change `.jpg` to `.jpeg`

_Originally posted by @MrCrayfish in https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/816#issuecomment-2054291576_
            
            

I attempted this, it still has the same issue. Here's the updated link: https://i.imgur.com/2bTu7hf.jpeg

Though it is interesting how putting the link into the address bar takes me to the imgur page, rather than the direct image itself, even though this is the link (altered to .jpeg from .jpg, though it redirects the same regardless) you get from "open image in new tab."

Any ideas?
            
            
![uno](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/assets/167043773/2cacd587-3780-4c23-ad23-1e3a1141b5ab)
![dos](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/assets/167043773/08837a0a-22a8-405e-881b-4f9e71395ece)

**Comment by MrCrayfish** [comment]
It's within Imgurs rights to change how their service works, and redirect any direct links back to a real website. You'll have to use a different service since I am not Imgur. This version of the mod is also no longer supported, so any bugs that arise won't be fixed.
