### ISSUE TITLE
[1.20] Mod won´t work with Minecraft 1.20

### ISSUE THREAD

**Issue by CyanideGoo** [MrCrayfish/MrCrayfishFurnitureMod#820]
In order to keep using certain mods, some friends and I created a server through Aternos using version 1.20 of Minecraft. 
I installed this mod for version 1.19.2 (cfm-7.0.0-pre35-1.19.2), and read whatever file was readable in the .jar. According to the file [mods.toml], this version should be compatible with Minecraft 1.20, but when starting up the game an error comes up (screenshots below). I'm very new to modded Minecraft so I have no idea on how to solve this.

![Captura de pantalla -2024-07-01 19-25-50](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/assets/174369395/00fb4cc0-e6b8-47ac-9b5a-1db8db925c2d)
![Captura de pantalla -2024-07-01 19-21-50](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/assets/174369395/549e6cc8-6f44-4b9e-bb01-e2182887269e)

- Minecraft Version: 1.20
- Mod Version: cfm-7.0.0-pre35-1.19.2

**Comment by MrCrayfish** [comment]
`[1.19.2, 1.20)` translates into minecraft versions greater or equal to `1.19.2` but less than `1.20`. The message on the error log says this.
