### ISSUE TITLE
Lamp(Pre-Release"The Outdoor Update")

### ISSUE THREAD

**Issue by SpaneBoswell** [MrCrayfish/MrCrayfishFurnitureMod#84]
You can not find the lamp in the creative inventory.

I am pretty sure it is just the modeling of the icon being the reason you can not get in the creative inventory.

I am pretty sure about this because with JEI(JustEnoughItems) you can get the lamp however it still has its old modeling

Also probably already mentioned but when you open a crafting table you get free sausage or is the WOP for the crafting recipe and temporary way to get it.

**Comment by sudo-apt-get-install** [comment]
Already fixed
