### ISSUE TITLE
Free Sausages in creating table (The Outside Update)

### ISSUE THREAD

**Issue by Sweetdude26** [MrCrayfish/MrCrayfishFurnitureMod#85]
I was playing survival and I found that there was a bug because whenever I put an item in the crafting area and took it out. After there were 16 sausages. I have a preview.

![mr crayfish crafting bug](https://cloud.githubusercontent.com/assets/19697607/15728093/51dc32ba-2852-11e6-9e20-cfc068ad1ff3.gif)

- Thanks

-I hope this will help the mod (progress)

**Comment by sudo-apt-get-install** [comment]
Already fixed 
Sorry man, you didn't help.
