### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by MisterSandFR** [MrCrayfish/MrCrayfishFurnitureMod#87]
Hello,
I'm actually working with your 1.6.4 version (yes i know it's an old version, but actually i don't have the choice...)
I have few problem with ur 1.6.4 version, so are you available to publish ur 1.6.4 sources.

**Comment by AlexTheGreat4000** [comment]
1.6.4 is so old, I highly doubt that any modder would still support a version of Minecraft and Forge that over 2 years old. Also why do you have no choice but to use an older version of Forge.

**Comment by coupaul** [comment]
Actually i have a big community on my 1.6.4, the first problem is : icbm doesn't work on newer version and the second is if intry to upgrade my map i loose all chisels blocks, that's why i don't moove to a newer version.

**Comment by Nekroido** [comment]
Are you talking about this ICBM? http://mods.curse.com/mc-mods/minecraft/225502-icbm It is available for 1.7.10.

**Comment by coupaul** [comment]
and the second is if intry to upgrade my map i loose all chisels blocks,

**Comment by Malongyes** [comment]
i want github 1.6.2- 1.6.4 please T^T
