### ISSUE TITLE
STILL NOT WORKING

### ISSUE THREAD

**Issue by Surawsome** [MrCrayfish/MrCrayfishFurnitureMod#93]
Mr. Crayfish, The Microwave and oven are STILL NOT WORKING. Please Fix -Surawsome

**Comment by MrCrayfish** [comment]
Can you describe exactly what's wrong besides "NOT WORKING". It doesn't help me locate the problem.

**Comment by Surawsome** [comment]
Instead of showing glass for the door, it shows white. Also, clicking start on the microwave doesn't start cooking the meat.

**Comment by RackieW** [comment]
uum i think you are the only one with that problem...

**Comment by Surawsome** [comment]
Do you know how I can fix it?

**Comment by HoldYourWaffle** [comment]
Java version?
Forge version?
Optifine?
Log?

**Comment by Surawsome** [comment]
Java version 8 v91 64bit
Forge verson 1.8.9-11.15.1.1902
Optifine H6

**Comment by HoldYourWaffle** [comment]
Try to remove optifine.
And post a log please.
