### ISSUE TITLE
Multibugs for multiblocks in 4.0

### ISSUE THREAD

**Issue by Nekroido** [MrCrayfish/MrCrayfishFurnitureMod#95]
Good day and thank you for this update! I have encountered some bugs though.
Grand Chair will drop only its top part if you break it by top. When you place the top part anywhere and break it, it will destroy the block beneath it, even bedrock. The Chair will also make you stuck when trying to stand up if its sides are blocked.
Instead of Fridge tile.freezer.name is being crafted. When placed its top part is Fridge and the bottom one is tile.freezer.name. When Fridge is broken tile.freezer.name (and any other block including bedrock) is destroyed.
And most of the new items don't have any durability and are destroyed in one hit.

**Comment by MrCrayfish** [comment]
Please seperate into multiple bug reports please
