### ISSUE TITLE
4.0 - Fridge bug

### ISSUE THREAD

**Issue by Nekroido** [MrCrayfish/MrCrayfishFurnitureMod#97]
Instead of Fridge tile.freezer.name is being crafted. When placed its top part is Fridge and the bottom one is tile.freezer.name. When Fridge is broken tile.freezer.name (and any other block including bedrock) is destroyed.
Might be related to #96

**Comment by MrCrayfish** [comment]
So you're saying, if any block above tile.freezer will break? It's the intended behaviour as it should always be the fridge block above.

**Comment by Nekroido** [comment]
No, anything below Fridge will break. The behavior is exactly like with Grand Chair: drops only top part when broken by top part. And this top part can be really nasty as can destroy blocks that shouldn't be destroyed. Breaking bottom part (tile.freezer.name) is totally okay: it drops tile.freezer.name that makes the usual fridge multiblock when placed.
