### ISSUE TITLE
Grill MP bug

### ISSUE THREAD

**Issue by Nekroido** [MrCrayfish/MrCrayfishFurnitureMod#98]
Grill doesn't work in multiplayer: neither sausages nor kebabs can be placed on it. And it also cannot be destroyed: I get the breaking animation after one hit, but the block stays there invisible and re-appears after right clicking, relogging or chunk reloading.
When I right click with Spatula on a Grill I get this error in my server's log:

> [07:17:07] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: leftFlipCount
>         at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_05]
>         at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_05]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
> Caused by: java.lang.NoSuchFieldError: leftFlipCount
>         at com.mrcrayfish.furniture.tileentity.TileEntityGrill.<init>(TileEntityGrill.java:44) ~[TileEntityGrill.class:?]
>         at com.mrcrayfish.furniture.blocks.BlockGrill.func_149915_a(BlockGrill.java:121) ~[BlockGrill.class:?]
>         at net.minecraft.block.Block.createTileEntity(Block.java:1309) ~[afh.class:?]
>         at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:831) ~[amy.class:?]
>         at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:848) ~[amy.class:?]
>         at net.minecraft.world.World.func_175625_s(World.java:2295) ~[adm.class:?]
>         at com.mrcrayfish.furniture.blocks.BlockGrill.func_180639_a(BlockGrill.java:71) ~[BlockGrill.class:?]
>         at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:427) ~[lg.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:588) ~[lm.class:?]
>         at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
>         at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_05]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_05]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
>         ... 5 more

**Comment by MrCrayfish** [comment]
Thansk for the report. Fixed th NoSuchFieldError in 4f6f643318ef0310b16d95ebe4f773ca04506e58 and fixed not being able to place sausages and kebab in 2a254f937362b3c0b7f913ea015f235d81d37a2f. Hardness was also fixed for all blocks in ce5dd1c63c783e32f10b57f06e3a1652c0c329e9 so it doesn't break instantly. I couldn't replicate the reappearing block after break.
