### ISSUE TITLE
Achievement Bug 

### ISSUE THREAD

**Issue by MikoSphinx** [MrCrayfish/MrCrayfishFurnitureMod#99]
The achievements don't keep what you have earned for achievements from the mod. You keep getting the same ones when placing down each one that had an achievement behind it. The only true one that stays on the server info for who got the first achievement is "You've Been Installed!" How can this be fixed?

**Comment by MrCrayfish** [comment]
What version of Minecraft and my mod are you using? I remember fixing this a long time ago.

**Comment by MikoSphinx** [comment]
Tis 1.7.10 minecraft version  and as well as 1.7.10 for your mod. It seems to happen every time reboot the server.

**Comment by robin840211** [comment]
※If I do something break the rules or impolite, please tell me asap.
Though I'm just a rookie here, I finally made a fix for 1.7.10 server's achievement bug, which just ported newer repository code to 1.7.10, and only replace a class file in jar file; also tested it will do a correct `registerstat()` and normally display like screenshot shows.
![image](https://user-images.githubusercontent.com/25872392/39909836-170a23be-5527-11e8-8ffe-a6d0560bffdc.png)

extract this archive from below, and drag into v3.4.8 (1.7.10)'s jar or corresponding location inside to fix that.
~~https://drive.google.com/open?id=1XR5AWgNBtf_AB5RbYQdC_UfSbsCepfmM~~
2023.11.22 link updated where old link dead:
[https://drive.google.com/file/d/1srrkVJsijebwYPejXk5cEKC5J0Aj0WYc/view?usp=drive_link](https://drive.google.com/file/d/1srrkVJsijebwYPejXk5cEKC5J0Aj0WYc/view?usp=drive_link)
Fix on server side only won't affect client playing, while achievement will state invalid in client, but actually working in server side.

enjoy :)

btw, love MrCrayFish's furniture mods very much <3
